import {
  defineTheme,
  displayStack,
  helveticaStack,
  monoStack,
  orbitronStack,
  plexSans,
  serifStack,
} from "./helpers";
import type { RetroTheme } from "./types";

export const aestheticThemes: RetroTheme[] = [
  defineTheme({
    id: "cassette-futurism",
    slug: "cassette-futurism",
    name: "Cassette Futurism",
    year: 1979,
    era: "Sci-Fi",
    description: "Chunky analog future: amber CRTs, ribbed plastic, toggle banks, and warm metal.",
    tags: ["scifi", "analog", "amber"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "noise",
    fonts: { ui: plexSans, mono: monoStack, display: orbitronStack },
    tokens: {
      desktop: "#0a0704",
      surface: "#1a1510",
      surfaceAlt: "#241d15",
      text: "#ffd470",
      textMuted: "#8a5c00",
      accent: "#ffb000",
      accentHover: "#ffd470",
      titlebarBg: "#241d15",
      titlebarText: "#ffb000",
      titlebarInactiveBg: "#1a1510",
      titlebarInactiveText: "#8a5c00",
      borderHigh: "#d9a85e",
      borderLight: "#3a2f22",
      borderDark: "#000000",
      borderLow: "#ffb000",
      fieldBg: "#0a0704",
      fieldText: "#ffd470",
      selectionBg: "#8a5c00",
      selectionText: "#ffd470",
      focus: "#ffb000",
      danger: "#ff5a2a",
      success: "#c0ff70",
      warning: "#ffb000",
      disabled: "#1a1510",
      disabledText: "#8a5c00",
      controlBg: "#241d15",
      controlBgHover: "#3a2f22",
      controlBgActive: "#1a1510",
      controlBgPrimary: "#ffb000",
      controlTextPrimary: "#0a0704",
      shadowOutset: "inset 0 1px 0 #3a2f22, 0 2px 0 #000000",
      shadowInset: "inset 0 2px 8px #000000",
      shadowWindow: "0 12px 0 #000000",
      radius: "2px",
      radiusWindow: "4px",
      radiusControl: "2px",
      borderWidth: "2px",
      fontSize: "13px",
      controlHeight: "28px",
      titlebarHeight: "26px",
      letterSpacing: "0.08em",
    },
  }),
  defineTheme({
    id: "vaporwave",
    slug: "vaporwave",
    name: "Vaporwave",
    year: 2011,
    era: "Aesthetic",
    description: "Pastel sundown, chrome grid horizon, magenta/cyan split, mallsoft type.",
    tags: ["vaporwave", "pastel", "synth"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "perspective",
    fonts: { ui: plexSans, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#1a0b2e",
      surface: "#2a1450",
      surfaceAlt: "#3a1a68",
      text: "#f8f8ff",
      textMuted: "#b967ff",
      accent: "#ff71ce",
      accentHover: "#01cdfe",
      titlebarBg: "linear-gradient(90deg, #ff71ce, #b967ff, #01cdfe)",
      titlebarText: "#1a0b2e",
      titlebarInactiveBg: "#2a1450",
      titlebarInactiveText: "#b967ff",
      borderHigh: "#05ffa1",
      borderLight: "#01cdfe",
      borderDark: "#b967ff",
      borderLow: "#ff71ce",
      fieldBg: "#1a0b2e",
      fieldText: "#f8f8ff",
      selectionBg: "#ff71ce",
      selectionText: "#1a0b2e",
      focus: "#05ffa1",
      danger: "#ff00e5",
      success: "#05ffa1",
      warning: "#fffb96",
      disabled: "#2a1450",
      disabledText: "#b967ff",
      controlBg: "#3a1a68",
      controlBgHover: "#4a2480",
      controlBgActive: "#2a1450",
      controlBgPrimary: "linear-gradient(90deg, #ff71ce, #01cdfe)",
      controlTextPrimary: "#1a0b2e",
      shadowOutset: "4px 4px 0 #01cdfe",
      shadowInset: "inset 0 0 0 2px #ff71ce",
      shadowWindow: "0 0 32px rgba(255, 113, 206, 0.35)",
      radius: "0px",
      borderWidth: "2px",
      fontSize: "14px",
      controlHeight: "32px",
      titlebarHeight: "32px",
      letterSpacing: "0.12em",
    },
  }),
  defineTheme({
    id: "memphis",
    slug: "memphis",
    name: "Memphis",
    year: 1981,
    era: "Design",
    description: "Sottsass postmodern: squiggles, terrazzo, primaries, and playful geometry.",
    tags: ["memphis", "postmodern", "squiggle"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "dots",
    fonts: { ui: displayStack, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#ffe034",
      surface: "#ffffff",
      surfaceAlt: "#12c3ce",
      text: "#000000",
      textMuted: "#2e4bff",
      accent: "#ff4fa3",
      accentHover: "#ff2e2e",
      titlebarBg: "#ff4fa3",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#12c3ce",
      titlebarInactiveText: "#000000",
      borderHigh: "#000000",
      borderLight: "#000000",
      borderDark: "#000000",
      borderLow: "#000000",
      fieldBg: "#ffffff",
      selectionBg: "#2e4bff",
      selectionText: "#ffffff",
      focus: "#ff2e2e",
      danger: "#ff2e2e",
      success: "#12c3ce",
      warning: "#ffe034",
      controlBg: "#ffe034",
      controlBgHover: "#fff0a0",
      controlBgActive: "#12c3ce",
      controlBgPrimary: "#2e4bff",
      controlTextPrimary: "#ffffff",
      shadowOutset: "5px 5px 0 #000000",
      shadowInset: "inset 3px 3px 0 #000000",
      shadowWindow: "8px 8px 0 #ff4fa3",
      radius: "0px",
      radiusWindow: "0px",
      radiusControl: "999px",
      borderWidth: "3px",
      fontSize: "15px",
      controlHeight: "36px",
      titlebarHeight: "36px",
    },
  }),
  defineTheme({
    id: "braun-rams",
    slug: "braun-rams",
    name: "Braun / Dieter Rams",
    year: 1960,
    era: "Design",
    description: "Less but better: pale housing, graphite type, a single orange accent.",
    tags: ["braun", "functional", "industrial"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "#f4f3f0",
      surface: "#ffffff",
      surfaceAlt: "#e4e3e0",
      text: "#1a1a1a",
      textMuted: "#6a6965",
      accent: "#f2642a",
      accentHover: "#ff7a40",
      titlebarBg: "#f4f3f0",
      titlebarText: "#1a1a1a",
      titlebarInactiveBg: "#e4e3e0",
      titlebarInactiveText: "#6a6965",
      borderHigh: "#ffffff",
      borderLight: "#e4e3e0",
      borderDark: "#b8b7b3",
      borderLow: "#2a2a28",
      fieldBg: "#ffffff",
      selectionBg: "#1a1a1a",
      selectionText: "#ffffff",
      focus: "#f2642a",
      danger: "#f2642a",
      success: "#2a2a28",
      warning: "#f2642a",
      controlBg: "#e4e3e0",
      controlBgHover: "#f4f3f0",
      controlBgActive: "#d4d3d0",
      controlBgPrimary: "#1a1a1a",
      controlTextPrimary: "#ffffff",
      shadowOutset: "0 1px 0 #ffffff",
      shadowInset: "inset 0 1px 0 #e4e3e0",
      shadowWindow: "0 1px 0 #b8b7b3",
      radius: "2px",
      radiusWindow: "2px",
      radiusControl: "2px",
      borderWidth: "1px",
      fontSize: "14px",
      controlHeight: "32px",
      titlebarHeight: "36px",
      letterSpacing: "0.04em",
    },
  }),
  defineTheme({
    id: "jurassic-park-unix",
    slug: "jurassic-park-unix",
    name: "Jurassic Park UNIX",
    year: 1993,
    era: "Sci-Fi",
    description:
      "It's a UNIX system: the fsn grid over black, phosphor-green readouts, silver program-access buttons, amber alerts.",
    tags: ["jurassic-park", "unix", "sgi", "movie"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "perspective",
    fonts: { ui: monoStack, mono: monoStack, display: monoStack },
    tokens: {
      desktop: "#000000",
      surface: "#0d130e",
      surfaceAlt: "#152016",
      text: "#39ff5c",
      textMuted: "#1f8a3c",
      textOnAccent: "#101408",
      accent: "#39ff5c",
      accentHover: "#7dffa0",
      titlebarBg: "#111a12",
      titlebarText: "#39ff5c",
      titlebarInactiveBg: "#0c110d",
      titlebarInactiveText: "#1f8a3c",
      titleLabelBg: "transparent",
      borderHigh: "#c2ccc2",
      borderLight: "#8a958a",
      borderDark: "#1c231c",
      borderLow: "#000000",
      fieldBg: "#020a04",
      fieldText: "#39ff5c",
      selectionBg: "#1f8a3c",
      selectionText: "#eafff0",
      focus: "#ffb400",
      danger: "#ff3b30",
      success: "#39ff5c",
      warning: "#ffb400",
      disabled: "#131a14",
      disabledText: "#2a6a3a",
      controlBg: "#8f9a90",
      controlBgHover: "#a5b0a6",
      controlBgActive: "#636d64",
      controlBgPrimary: "#ffb400",
      controlTextPrimary: "#161208",
      controlText: "#101510",
      shadowOutset:
        "inset -1px -1px #000000, inset 1px 1px #dfe6df, inset -2px -2px #232b23, inset 2px 2px #aab4aa",
      shadowInset:
        "inset 1px 1px #000000, inset -1px -1px #dfe6df, inset 2px 2px #232b23, inset -2px -2px #aab4aa",
      shadowWindow: "0 0 24px rgba(57, 255, 92, 0.28)",
      fontSize: "14px",
      controlHeight: "30px",
      titlebarHeight: "26px",
      letterSpacing: "0.06em",
    },
  }),
  defineTheme({
    id: "tron-vector",
    slug: "tron-vector",
    name: "Tron Vector",
    year: 1982,
    era: "Sci-Fi",
    description: "Light-cycle grid: cyan strokes on void, orange opposition, circuit panels.",
    tags: ["tron", "vector", "cyan"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "grid",
    fonts: { ui: orbitronStack, mono: monoStack, display: orbitronStack },
    tokens: {
      desktop: "#000008",
      surface: "#0a1a3a",
      surfaceAlt: "#051028",
      text: "#a0f4ff",
      textMuted: "#007a8a",
      accent: "#00e4ff",
      accentHover: "#a0f4ff",
      titlebarBg: "#000008",
      titlebarText: "#00e4ff",
      titlebarInactiveBg: "#000008",
      titlebarInactiveText: "#007a8a",
      borderHigh: "#00e4ff",
      borderLight: "#00e4ff",
      borderDark: "#007a8a",
      borderLow: "#ff7a00",
      fieldBg: "#000008",
      fieldText: "#a0f4ff",
      selectionBg: "#00e4ff",
      selectionText: "#000008",
      focus: "#ff7a00",
      danger: "#ff2040",
      success: "#00e4ff",
      warning: "#ff7a00",
      disabled: "#0a1a3a",
      disabledText: "#007a8a",
      controlBg: "#0a1a3a",
      controlBgHover: "#102850",
      controlBgActive: "#051028",
      controlBgPrimary: "#00e4ff",
      controlTextPrimary: "#000008",
      shadowOutset: "0 0 12px #00e4ff",
      shadowInset: "inset 0 0 12px rgba(0,228,255,0.25)",
      shadowWindow: "0 0 24px rgba(0,228,255,0.35)",
      radius: "0px",
      borderWidth: "1px",
      fontSize: "12px",
      controlHeight: "28px",
      titlebarHeight: "28px",
      letterSpacing: "0.18em",
    },
  }),
  defineTheme({
    id: "vhs-tracking",
    slug: "vhs-tracking",
    name: "VHS Tracking",
    year: 1980,
    era: "Analog",
    description: "Tracking errors, scanline jitter, REC red, and analog rainbow noise.",
    tags: ["vhs", "glitch", "analog"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "scanlines",
    fonts: { ui: `"Special Elite", ${serifStack}`, mono: monoStack, display: `"Special Elite", ${serifStack}` },
    tokens: {
      desktop: "#0a0a0a",
      surface: "#141014",
      surfaceAlt: "#1c1418",
      text: "#f4f4f4",
      textMuted: "#a09090",
      accent: "#ff1a1a",
      accentHover: "#ff4a4a",
      titlebarBg: "#ff1a1a",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#141014",
      titlebarInactiveText: "#a09090",
      borderHigh: "#ffe84a",
      borderLight: "#4ae2ff",
      borderDark: "#ff1a1a",
      borderLow: "#2aff2a",
      fieldBg: "#0a0a0a",
      fieldText: "#f4f4f4",
      selectionBg: "#ff1a1a",
      selectionText: "#ffffff",
      focus: "#4ae2ff",
      danger: "#ff2a2a",
      success: "#2aff2a",
      warning: "#ffe84a",
      disabled: "#141014",
      disabledText: "#6a5a5a",
      controlBg: "#1c1418",
      controlBgHover: "#2a1c22",
      controlBgActive: "#0a0a0a",
      controlBgPrimary: "#ff1a1a",
      controlTextPrimary: "#ffffff",
      shadowOutset: "0 0 0 1px #ff1a1a",
      shadowInset: "inset 0 0 20px rgba(255,26,26,0.2)",
      shadowWindow: "4px 0 0 #4ae2ff, -4px 0 0 #ff1a1a",
      radius: "0px",
      borderWidth: "2px",
      fontSize: "14px",
      controlHeight: "28px",
      titlebarHeight: "24px",
      letterSpacing: "0.08em",
    },
  }),
  defineTheme({
    id: "risograph",
    slug: "risograph",
    name: "Risograph",
    year: 1986,
    era: "Print",
    description: "Soy ink overlays: fluorescent pink, federal blue, grain, and misregistration.",
    tags: ["riso", "print", "duotone"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "noise",
    fonts: { ui: plexSans, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#f3efe4",
      surface: "#e6dfcb",
      surfaceAlt: "#f3efe4",
      text: "#1a1a1a",
      textMuted: "#0078b4",
      accent: "#ff4fa5",
      accentHover: "#ffb8db",
      titlebarBg: "#ff4fa5",
      titlebarText: "#f3efe4",
      titlebarInactiveBg: "#0078b4",
      titlebarInactiveText: "#e6dfcb",
      borderHigh: "#1a1a1a",
      borderLight: "#1a1a1a",
      borderDark: "#1a1a1a",
      borderLow: "#0078b4",
      fieldBg: "#f3efe4",
      selectionBg: "#0078b4",
      selectionText: "#f3efe4",
      focus: "#ff4fa5",
      danger: "#ff4fa5",
      success: "#00a03c",
      warning: "#f6d800",
      controlBg: "#f3efe4",
      controlBgHover: "#e6dfcb",
      controlBgActive: "#ffb8db",
      controlBgPrimary: "#0078b4",
      controlTextPrimary: "#f3efe4",
      shadowOutset: "4px 4px 0 #0078b4",
      shadowInset: "2px 2px 0 #ff4fa5",
      shadowWindow: "6px 6px 0 #ff4fa5",
      radius: "0px",
      borderWidth: "2px",
      fontSize: "15px",
      controlHeight: "36px",
      titlebarHeight: "36px",
    },
  }),
  defineTheme({
    id: "blueprint-cad",
    slug: "blueprint-cad",
    name: "Blueprint / CAD",
    year: 1980,
    era: "Technical",
    description: "Cyanotype drafting: white ink on Prussian blue, title blocks, and grid paper.",
    tags: ["blueprint", "cad", "grid"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "grid",
    fonts: { ui: `"IBM Plex Mono", ${monoStack}`, mono: `"IBM Plex Mono", ${monoStack}`, display: plexSans },
    tokens: {
      desktop: "#0d3a6b",
      surface: "#082852",
      surfaceAlt: "#0d3a6b",
      text: "#c0daf4",
      textMuted: "#6892c4",
      accent: "#eaf2fb",
      accentHover: "#ffffff",
      titlebarBg: "#082852",
      titlebarText: "#eaf2fb",
      titlebarInactiveBg: "#082852",
      titlebarInactiveText: "#6892c4",
      borderHigh: "#c0daf4",
      borderLight: "#6892c4",
      borderDark: "#082852",
      borderLow: "#ffe066",
      fieldBg: "#082852",
      fieldText: "#eaf2fb",
      selectionBg: "#c0daf4",
      selectionText: "#082852",
      focus: "#ffe066",
      danger: "#ff6b6b",
      success: "#c0daf4",
      warning: "#ffe066",
      disabled: "#082852",
      disabledText: "#6892c4",
      controlBg: "#0d3a6b",
      controlBgHover: "#164a80",
      controlBgActive: "#082852",
      controlBgPrimary: "#c0daf4",
      controlTextPrimary: "#082852",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "0 0 0 1px #c0daf4",
      radius: "0px",
      borderWidth: "1px",
      fontSize: "13px",
      controlHeight: "28px",
      titlebarHeight: "28px",
      letterSpacing: "0.06em",
    },
  }),
  defineTheme({
    id: "swiss-intl",
    slug: "swiss-intl",
    name: "Swiss Style",
    year: 1950,
    era: "Design",
    description: "International Typographic Style: Helvetica, modular grid, red accent, no ornament.",
    tags: ["swiss", "helvetica", "grid"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "#f4f3ee",
      surface: "#ffffff",
      surfaceAlt: "#f4f3ee",
      text: "#0a0a0a",
      textMuted: "#6a6a6a",
      accent: "#e63946",
      accentHover: "#c01f2c",
      titlebarBg: "#0a0a0a",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#6a6a6a",
      titlebarInactiveText: "#ffffff",
      borderHigh: "#0a0a0a",
      borderLight: "#0a0a0a",
      borderDark: "#0a0a0a",
      borderLow: "#e63946",
      fieldBg: "#ffffff",
      selectionBg: "#e63946",
      selectionText: "#ffffff",
      focus: "#e63946",
      danger: "#e63946",
      success: "#0a0a0a",
      warning: "#e63946",
      controlBg: "#ffffff",
      controlBgHover: "#f4f3ee",
      controlBgActive: "#e8e7e2",
      controlBgPrimary: "#e63946",
      controlTextPrimary: "#ffffff",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "none",
      radius: "0px",
      borderWidth: "1px",
      fontSize: "14px",
      controlHeight: "40px",
      titlebarHeight: "48px",
      letterSpacing: "-0.02em",
    },
  }),
  defineTheme({
    id: "bauhaus",
    slug: "bauhaus",
    name: "Bauhaus",
    year: 1919,
    era: "Design",
    description: "Primary geometry: circle, triangle, square; red yellow blue; workshop type.",
    tags: ["bauhaus", "primary", "geometric"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: displayStack, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#f0ebe0",
      surface: "#ffffff",
      surfaceAlt: "#f0ebe0",
      text: "#0a0a0a",
      textMuted: "#1c4fb5",
      accent: "#d32027",
      accentHover: "#1c4fb5",
      titlebarBg: "#d32027",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#1c4fb5",
      titlebarInactiveText: "#ffffff",
      borderHigh: "#0a0a0a",
      borderLight: "#0a0a0a",
      borderDark: "#0a0a0a",
      borderLow: "#0a0a0a",
      fieldBg: "#ffffff",
      selectionBg: "#f5c518",
      selectionText: "#0a0a0a",
      focus: "#1c4fb5",
      danger: "#d32027",
      success: "#1c4fb5",
      warning: "#f5c518",
      controlBg: "#f5c518",
      controlBgHover: "#ffe56a",
      controlBgActive: "#d32027",
      controlBgPrimary: "#1c4fb5",
      controlTextPrimary: "#ffffff",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "none",
      radius: "0px",
      radiusControl: "0px",
      borderWidth: "4px",
      fontSize: "16px",
      controlHeight: "40px",
      titlebarHeight: "44px",
    },
  }),
  defineTheme({
    id: "pop-art",
    slug: "pop-art",
    name: "Pop Art",
    year: 1960,
    era: "Art",
    description: "Ben-Day dots, comic punch, primary speech, heavy ink outlines.",
    tags: ["popart", "halftone", "comic"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "halftone",
    fonts: { ui: displayStack, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#fffef8",
      surface: "#ffffff",
      surfaceAlt: "#ffd6c7",
      text: "#0a0a0a",
      textMuted: "#1b4ea0",
      accent: "#ed1c24",
      accentHover: "#ffde00",
      titlebarBg: "#ed1c24",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#1b4ea0",
      titlebarInactiveText: "#ffffff",
      borderHigh: "#0a0a0a",
      borderLight: "#0a0a0a",
      borderDark: "#0a0a0a",
      borderLow: "#0a0a0a",
      fieldBg: "#ffffff",
      selectionBg: "#ffde00",
      selectionText: "#0a0a0a",
      focus: "#ed1c24",
      danger: "#ed1c24",
      success: "#1b4ea0",
      warning: "#ffde00",
      controlBg: "#ffde00",
      controlBgHover: "#fff3a0",
      controlBgActive: "#ed1c24",
      controlBgPrimary: "#ed1c24",
      controlTextPrimary: "#ffffff",
      shadowOutset: "4px 4px 0 #0a0a0a",
      shadowInset: "inset 0 0 0 3px #0a0a0a",
      shadowWindow: "6px 6px 0 #0a0a0a",
      radius: "0px",
      borderWidth: "4px",
      fontSize: "16px",
      controlHeight: "40px",
      titlebarHeight: "40px",
    },
  }),
  defineTheme({
    id: "op-art",
    slug: "op-art",
    name: "Op Art",
    year: 1964,
    era: "Art",
    description: "Vasarely / Riley: high-frequency black-white vibration and a single red interrupt.",
    tags: ["opart", "illusion", "bw"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "checker",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "#0a0a0a",
      surface: "#f5f5f5",
      surfaceAlt: "#0a0a0a",
      text: "#0a0a0a",
      textMuted: "#0a0a0a",
      accent: "#ec1e23",
      accentHover: "#ec1e23",
      titlebarBg: "#0a0a0a",
      titlebarText: "#f5f5f5",
      titlebarInactiveBg: "#f5f5f5",
      titlebarInactiveText: "#0a0a0a",
      borderHigh: "#0a0a0a",
      borderLight: "#0a0a0a",
      borderDark: "#0a0a0a",
      borderLow: "#ec1e23",
      fieldBg: "#f5f5f5",
      selectionBg: "#0a0a0a",
      selectionText: "#f5f5f5",
      focus: "#ec1e23",
      danger: "#ec1e23",
      success: "#0a0a0a",
      warning: "#ec1e23",
      controlBg: "#f5f5f5",
      controlBgHover: "#ffffff",
      controlBgActive: "#0a0a0a",
      controlBgPrimary: "#0a0a0a",
      controlTextPrimary: "#f5f5f5",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "0 0 0 8px #0a0a0a",
      radius: "0px",
      borderWidth: "2px",
      fontSize: "14px",
      controlHeight: "32px",
      titlebarHeight: "32px",
    },
  }),
  defineTheme({
    id: "hypnagogic",
    slug: "hypnagogic",
    name: "Hypnagogic",
    year: 2015,
    era: "Aesthetic",
    description: "Liminal dusk: honeyed gradients, soft vignette, half-remembered motel lighting.",
    tags: ["dreamy", "gradient", "liminal"],
    engine: "soft",
    controls: "none",
    desktopPattern: "horizon",
    fonts: { ui: serifStack, mono: monoStack, display: serifStack },
    tokens: {
      desktop: "#c89050",
      surface: "rgba(232,216,176,0.88)",
      surfaceAlt: "rgba(255,244,200,0.7)",
      text: "#2a2418",
      textMuted: "#6a5530",
      accent: "#3d5a80",
      accentHover: "#8a7a54",
      titlebarBg: "linear-gradient(#fff4c8, #c89050)",
      titlebarText: "#2a2418",
      titlebarInactiveBg: "#dcc89a",
      titlebarInactiveText: "#6a5530",
      borderHigh: "#fff4c8",
      borderLight: "#e8d8b0",
      borderDark: "#8a7a54",
      borderLow: "#6a5530",
      fieldBg: "#fff4c8",
      selectionBg: "#3d5a80",
      selectionText: "#fff4c8",
      focus: "#3d5a80",
      danger: "#8a4030",
      success: "#5a7040",
      warning: "#c89050",
      controlBg: "linear-gradient(#fff4c8, #e8d8b0)",
      controlBgHover: "#fff4c8",
      controlBgActive: "#dcc89a",
      controlBgPrimary: "#3d5a80",
      controlTextPrimary: "#fff4c8",
      shadowOutset: "0 10px 30px rgba(42,36,24,0.18)",
      shadowInset: "inset 0 1px 0 #fff4c8",
      shadowWindow: "0 20px 50px rgba(42,36,24,0.25)",
      radius: "6px",
      radiusWindow: "8px",
      radiusControl: "6px",
      borderWidth: "1px",
      fontSize: "15px",
      controlHeight: "32px",
      titlebarHeight: "36px",
    },
  }),
  defineTheme({
    id: "monochrome-zen",
    slug: "monochrome-zen",
    name: "Monochrome Zen",
    year: 2010,
    era: "Design",
    description: "Ink and paper only. Quiet spacing, hairline rules, no chrome noise.",
    tags: ["mono", "zen", "minimal"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: serifStack, mono: monoStack, display: serifStack },
    tokens: {
      desktop: "#fafaf7",
      surface: "#fafaf7",
      surfaceAlt: "#f0f0ec",
      text: "#0a0a0a",
      textMuted: "#6a6a6a",
      accent: "#0a0a0a",
      accentHover: "#333333",
      titlebarBg: "#fafaf7",
      titlebarText: "#0a0a0a",
      titlebarInactiveBg: "#fafaf7",
      titlebarInactiveText: "#6a6a6a",
      borderHigh: "#0a0a0a",
      borderLight: "#0a0a0a",
      borderDark: "#0a0a0a",
      borderLow: "#0a0a0a",
      fieldBg: "#ffffff",
      selectionBg: "#0a0a0a",
      selectionText: "#fafaf7",
      focus: "#0a0a0a",
      danger: "#0a0a0a",
      success: "#0a0a0a",
      warning: "#0a0a0a",
      controlBg: "#fafaf7",
      controlBgHover: "#f0f0ec",
      controlBgActive: "#e4e4e0",
      controlBgPrimary: "#0a0a0a",
      controlTextPrimary: "#fafaf7",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "none",
      radius: "0px",
      borderWidth: "1px",
      fontSize: "16px",
      controlHeight: "36px",
      titlebarHeight: "40px",
      letterSpacing: "0.08em",
    },
  }),
  defineTheme({
    id: "wireframe-sketch",
    slug: "wireframe-sketch",
    name: "Wireframe Sketch",
    year: 2010,
    era: "Technical",
    description: "Lo-fi annotations: dashed boxes, handwriting, and placeholder gray.",
    tags: ["wireframe", "sketch", "lofi"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: `"Special Elite", ${serifStack}`, mono: monoStack, display: `"Special Elite", ${serifStack}` },
    tokens: {
      desktop: "#fbfaf4",
      surface: "#fbfaf4",
      surfaceAlt: "#f0eee4",
      text: "#2a2a2a",
      textMuted: "#8a8a8a",
      accent: "#2a2a2a",
      accentHover: "#000000",
      titlebarBg: "#fbfaf4",
      titlebarText: "#2a2a2a",
      titlebarInactiveBg: "#fbfaf4",
      titlebarInactiveText: "#8a8a8a",
      borderHigh: "#2a2a2a",
      borderLight: "#2a2a2a",
      borderDark: "#2a2a2a",
      borderLow: "#2a2a2a",
      fieldBg: "#ffffff",
      selectionBg: "#d4d1c4",
      selectionText: "#2a2a2a",
      focus: "#2a2a2a",
      danger: "#2a2a2a",
      success: "#2a2a2a",
      warning: "#2a2a2a",
      controlBg: "#fbfaf4",
      controlBgHover: "#f0eee4",
      controlBgActive: "#d4d1c4",
      controlBgPrimary: "#2a2a2a",
      controlTextPrimary: "#fbfaf4",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "2px 2px 0 #2a2a2a",
      radius: "2px",
      borderWidth: "1px",
      fontSize: "14px",
      controlHeight: "32px",
      titlebarHeight: "32px",
    },
  }),
  defineTheme({
    id: "glitch-databend",
    slug: "glitch-databend",
    name: "Glitch Databend",
    year: 2010,
    era: "Aesthetic",
    description: "Channel-shifted RGB, corrupt blocks, and datamosh edges.",
    tags: ["glitch", "databend", "rgb"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "noise",
    fonts: { ui: plexSans, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#0a0a0a",
      surface: "#141414",
      surfaceAlt: "#1c1c1c",
      text: "#f0f0f0",
      textMuted: "#888888",
      accent: "#ff004d",
      accentHover: "#00f4ff",
      titlebarBg: "#0a0a0a",
      titlebarText: "#00f4ff",
      titlebarInactiveBg: "#0a0a0a",
      titlebarInactiveText: "#888888",
      borderHigh: "#00f4ff",
      borderLight: "#00ff8c",
      borderDark: "#ff004d",
      borderLow: "#ffe600",
      fieldBg: "#000000",
      fieldText: "#f0f0f0",
      selectionBg: "#ff00ae",
      selectionText: "#ffffff",
      focus: "#00f4ff",
      danger: "#ff004d",
      success: "#00ff8c",
      warning: "#ffe600",
      disabled: "#141414",
      disabledText: "#555555",
      controlBg: "#1c1c1c",
      controlBgHover: "#2a2a2a",
      controlBgActive: "#000000",
      controlBgPrimary: "#ff004d",
      controlTextPrimary: "#ffffff",
      shadowOutset: "3px 0 0 #00f4ff, -3px 0 0 #ff004d",
      shadowInset: "inset 2px 0 0 #00f4ff, inset -2px 0 0 #ff004d",
      shadowWindow: "4px 0 0 #00f4ff, -4px 0 0 #ff004d",
      radius: "0px",
      borderWidth: "2px",
      fontSize: "13px",
      controlHeight: "30px",
      titlebarHeight: "28px",
      letterSpacing: "0.04em",
    },
  }),
  defineTheme({
    id: "duotone-poster",
    slug: "duotone-poster",
    name: "Duotone Poster",
    year: 2015,
    era: "Print",
    description: "Two-ink posters: cream ground, punch red, midnight navy. Huge type.",
    tags: ["duotone", "poster", "bold"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: displayStack, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#f4ead3",
      surface: "#f4ead3",
      surfaceAlt: "#1a1a3a",
      text: "#1a1a3a",
      textMuted: "#1a1a3a",
      accent: "#ff3a38",
      accentHover: "#1a1a3a",
      titlebarBg: "#1a1a3a",
      titlebarText: "#f4ead3",
      titlebarInactiveBg: "#ff3a38",
      titlebarInactiveText: "#f4ead3",
      borderHigh: "#1a1a3a",
      borderLight: "#1a1a3a",
      borderDark: "#1a1a3a",
      borderLow: "#ff3a38",
      fieldBg: "#f4ead3",
      selectionBg: "#ff3a38",
      selectionText: "#f4ead3",
      focus: "#ff3a38",
      danger: "#ff3a38",
      success: "#1a1a3a",
      warning: "#ff3a38",
      controlBg: "#f4ead3",
      controlBgHover: "#efe2c4",
      controlBgActive: "#1a1a3a",
      controlBgPrimary: "#ff3a38",
      controlTextPrimary: "#f4ead3",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "none",
      radius: "0px",
      borderWidth: "6px",
      fontSize: "16px",
      controlHeight: "44px",
      titlebarHeight: "48px",
      letterSpacing: "0.08em",
    },
  }),
  defineTheme({
    id: "grid-paper",
    slug: "grid-paper",
    name: "Grid Paper",
    year: 1980,
    era: "Technical",
    description: "Engineering pad: cream sheet, 5mm blue grid, red margin, graphite notes.",
    tags: ["grid", "paper", "engineering"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "grid",
    fonts: { ui: `"Special Elite", ${serifStack}`, mono: `"IBM Plex Mono", ${monoStack}`, display: plexSans },
    tokens: {
      desktop: "#fafaf0",
      surface: "#fafaf0",
      surfaceAlt: "#f3f3e8",
      text: "#1a2847",
      textMuted: "#4a5a6e",
      accent: "#c83030",
      accentHover: "#2a7a3a",
      titlebarBg: "#fafaf0",
      titlebarText: "#1a2847",
      titlebarInactiveBg: "#fafaf0",
      titlebarInactiveText: "#4a5a6e",
      borderHigh: "#c8d4e0",
      borderLight: "#c8d4e0",
      borderDark: "#8aa0b8",
      borderLow: "#c83030",
      fieldBg: "#ffffff",
      selectionBg: "#d0e4f8",
      selectionText: "#1a2847",
      focus: "#c83030",
      danger: "#c83030",
      success: "#2a7a3a",
      warning: "#c83030",
      controlBg: "#fafaf0",
      controlBgHover: "#f3f3e8",
      controlBgActive: "#e8e8dc",
      controlBgPrimary: "#1a2847",
      controlTextPrimary: "#fafaf0",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "0 1px 0 #c8d4e0",
      radius: "0px",
      borderWidth: "1px",
      fontSize: "14px",
      controlHeight: "28px",
      titlebarHeight: "28px",
    },
  }),
];
