import { defineTheme, helveticaStack, monoStack } from "./helpers";

const roundedStack = `ui-rounded, "SF Pro Rounded", "Arial Rounded MT Bold", "Segoe UI", sans-serif`;

/**
 * Console system software — the shells players lived in between games.
 */
export const consoleThemes = [
  defineTheme({
    id: "ps3-xmb",
    slug: "ps3-xmb",
    name: "PS3 XMB",
    year: 2006,
    era: "Gaming",
    description:
      "The XrossMediaBar: midnight-blue depths, a drifting wave of light, thin white type with a soft glow, and the clock pinned top-right.",
    tags: ["sony", "playstation", "xmb", "psp", "dark"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    taskbarPosition: "top",
    fonts: { ui: "Inter, \"Segoe UI\", sans-serif", mono: monoStack, display: "Inter, \"Segoe UI\", sans-serif" },
    tokens: {
      desktop:
        "linear-gradient(180deg, #040711 0%, #0b1533 55%, #16295c 100%), radial-gradient(140% 60% at 30% 90%, rgba(158, 180, 255, 0.28), rgba(158, 180, 255, 0) 55%)",
      surface: "#111a30",
      surfaceAlt: "#182447",
      text: "#f4f6ff",
      textMuted: "#9aa4c0",
      textOnAccent: "#ffffff",
      accent: "#a8c8ff",
      accentHover: "#c8dcff",
      titlebarBg: "#0c142c",
      titlebarText: "#f4f6ff",
      titlebarInactiveBg: "#0a1122",
      titlebarInactiveText: "#5a6684",
      titleLabelBg: "transparent",
      borderHigh: "rgba(190, 210, 255, 0.35)",
      borderLight: "rgba(150, 175, 235, 0.22)",
      borderDark: "#060b18",
      borderLow: "#03060e",
      fieldBg: "#0a1122",
      fieldText: "#f4f6ff",
      selectionBg: "#2a52b0",
      selectionText: "#ffffff",
      focus: "#cfe0ff",
      danger: "#ff6a6a",
      success: "#9ade6a",
      warning: "#ffd27a",
      disabled: "#101830",
      disabledText: "#5a6684",
      controlBg: "#18244a",
      controlBgHover: "#1f2e5c",
      controlBgActive: "#26366c",
      controlBgPrimary: "#a8c8ff",
      controlTextPrimary: "#0a1122",
      shadowOutset: "inset 0 0 0 1px rgba(190, 210, 255, 0.14)",
      shadowInset: "inset 0 2px 6px rgba(0, 0, 0, 0.5)",
      shadowWindow: "0 0 40px rgba(80, 110, 220, 0.35), 0 8px 24px rgba(0, 0, 0, 0.5)",
      radius: "4px",
      radiusWindow: "6px",
      radiusControl: "4px",
      borderWidth: "1px",
      fontSize: "14px",
      lineHeight: "1.4",
      controlHeight: "34px",
      titlebarHeight: "30px",
      space: "12px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "xbox-blades",
    slug: "xbox-blades",
    name: "Xbox 360 Blades",
    year: 2005,
    era: "Gaming",
    description:
      "The launch dashboard: brushed-silver panels sliding in from the edges, translucent frosted chrome, and that green guide orb.",
    tags: ["microsoft", "xbox", "dashboard", "blades", "silver"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "linear-gradient(180deg, #d9dee3, #aab3bb 55%, #7e8993)",
      surface: "#e8ecef",
      surfaceAlt: "#d5dbdf",
      text: "#1c222a",
      textMuted: "#5a6570",
      textOnAccent: "#ffffff",
      accent: "#8dc63f",
      accentHover: "#a4dd55",
      titlebarBg: "linear-gradient(180deg, rgba(70, 80, 90, 0.95), rgba(40, 48, 56, 0.95))",
      titlebarText: "#f4f6f8",
      titlebarInactiveBg: "#c3cad0",
      titlebarInactiveText: "#5a6570",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#eef1f3",
      borderDark: "#9aa6ae",
      borderLow: "#76828a",
      fieldBg: "#ffffff",
      fieldText: "#1c222a",
      selectionBg: "#7ab640",
      selectionText: "#ffffff",
      focus: "#8dc63f",
      danger: "#c85040",
      success: "#8dc63f",
      warning: "#e0a030",
      disabled: "#dde2e6",
      disabledText: "#9aa6ae",
      controlBg: "linear-gradient(#ffffff, #d9dfe4)",
      controlBgHover: "linear-gradient(#ffffff, #e6ebef)",
      controlBgActive: "#ccd3d8",
      controlBgPrimary: "linear-gradient(#a4dd55, #6faf2a)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 3px rgba(20, 28, 36, 0.3)",
      shadowInset: "inset 0 2px 4px rgba(20, 28, 36, 0.18)",
      shadowWindow: "0 6px 20px rgba(20, 28, 36, 0.4)",
      radius: "4px",
      radiusWindow: "6px",
      radiusControl: "4px",
      borderWidth: "1px",
      fontSize: "13px",
      lineHeight: "1.4",
      controlHeight: "32px",
      titlebarHeight: "30px",
      space: "10px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "wii-menu",
    slug: "wii-menu",
    name: "Wii Menu",
    year: 2006,
    era: "Gaming",
    description:
      "Bright white channel grid: squircle tiles, soft rounded gray buttons, the health-and-safety calm of Nintendo's friendliest OS.",
    tags: ["nintendo", "wii", "channels", "light", "console"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "linear-gradient(180deg, #ffffff, #e8ecef)",
      surface: "#ffffff",
      surfaceAlt: "#f0f2f4",
      text: "#3a4650",
      textMuted: "#8a97a0",
      textOnAccent: "#ffffff",
      accent: "#0f8fd6",
      accentHover: "#2aa8ea",
      titlebarBg: "linear-gradient(#f8fafc, #dde3e8)",
      titlebarText: "#3a4650",
      titlebarInactiveBg: "#eceff2",
      titlebarInactiveText: "#8a97a0",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#f2f4f6",
      borderDark: "#c6cdd3",
      borderLow: "#9aa6ae",
      fieldBg: "#ffffff",
      fieldText: "#3a4650",
      selectionBg: "#0f8fd6",
      selectionText: "#ffffff",
      focus: "#0f8fd6",
      danger: "#d05050",
      success: "#58a848",
      warning: "#e8a33d",
      disabled: "#f0f2f4",
      disabledText: "#b4bdc3",
      controlBg: "linear-gradient(#ffffff, #e2e7eb)",
      controlBgHover: "linear-gradient(#ffffff, #ecf0f3)",
      controlBgActive: "#d6dde2",
      controlBgPrimary: "#0f8fd6",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 3px rgba(30, 50, 70, 0.2)",
      shadowInset: "inset 0 2px 3px rgba(30, 50, 70, 0.14)",
      shadowWindow: "0 6px 18px rgba(30, 50, 70, 0.25)",
      radius: "10px",
      radiusWindow: "12px",
      radiusControl: "10px",
      borderWidth: "1px",
      fontSize: "14px",
      lineHeight: "1.4",
      controlHeight: "34px",
      titlebarHeight: "32px",
      space: "12px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "switch-home",
    slug: "switch-home",
    name: "Switch Home",
    year: 2017,
    era: "Gaming",
    description:
      "Big friendly tiles on pale gray, pill-shaped charcoal buttons, a floating dock of round icons — Nintendo's calmest hardware smile.",
    tags: ["nintendo", "switch", "console", "rounded", "modern"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: roundedStack, mono: monoStack, display: roundedStack },
    tokens: {
      desktop: "linear-gradient(180deg, #f6f7f9, #e4e7ea)",
      surface: "#ffffff",
      surfaceAlt: "#f2f3f5",
      text: "#2c3038",
      textMuted: "#8a8f98",
      textOnAccent: "#ffffff",
      accent: "#e60012",
      accentHover: "#ff2435",
      titlebarBg: "#ffffff",
      titlebarText: "#2c3038",
      titlebarInactiveBg: "#f2f3f5",
      titlebarInactiveText: "#8a8f98",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#f4f5f7",
      borderDark: "#d8dade",
      borderLow: "#b8bcc2",
      fieldBg: "#ffffff",
      fieldText: "#2c3038",
      selectionBg: "#e8e8ea",
      selectionText: "#2c3038",
      focus: "#e60012",
      danger: "#e60012",
      success: "#02c39a",
      warning: "#f4a320",
      disabled: "#f2f3f5",
      disabledText: "#b8bcc2",
      controlBg: "#ffffff",
      controlBgHover: "#f2f3f5",
      controlBgActive: "#e8e8ea",
      controlBgPrimary: "#2d3138",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 0 0 1px #d8dade",
      shadowInset: "inset 0 2px 4px rgba(20, 24, 32, 0.1)",
      shadowWindow: "0 4px 16px rgba(20, 24, 32, 0.18)",
      radius: "12px",
      radiusWindow: "14px",
      radiusControl: "12px",
      borderWidth: "0px",
      fontSize: "14px",
      lineHeight: "1.45",
      controlHeight: "36px",
      titlebarHeight: "32px",
      space: "12px",
      letterSpacing: "0",
    },
  }),
];
