import {
  defineTheme,
  genevaStack,
  helveticaStack,
  lucidaStack,
  monoStack,
  tahomaStack,
  ubuntuStack,
} from "./helpers";

/**
 * Cult operating systems — research machines, cancelled futures,
 * and the communities that kept them alive.
 */
export const cultOsThemes = [
  defineTheme({
    id: "serenityos",
    slug: "serenityos",
    name: "SerenityOS",
    year: 2019,
    era: "Desktop OS",
    description:
      "Andreas Kling's love letter: Windows-NT bevels rebuilt with web-generation gradients, a green desktop, and a taskbar that feels like coming home.",
    tags: ["serenityos", "retro-futurist", "unix", "bevel", "community"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {
      desktop: "linear-gradient(180deg, #2e5a35, #1d3a24)",
      surface: "#c8c8c8",
      surfaceAlt: "#dcdcdc",
      text: "#101010",
      textMuted: "#4a4a4a",
      textOnAccent: "#ffffff",
      accent: "#3a6ab5",
      accentHover: "#4a7ac8",
      titlebarBg: "linear-gradient(#6a9ae2, #3a6ab5)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "linear-gradient(#a8a8a8, #808080)",
      titlebarInactiveText: "#d8d8d8",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#dfdfdf",
      borderDark: "#808080",
      borderLow: "#000000",
      fieldBg: "#ffffff",
      fieldText: "#101010",
      selectionBg: "#3a6ab5",
      selectionText: "#ffffff",
      focus: "#101010",
      danger: "#8a2a22",
      success: "#2a7a3a",
      warning: "#b8912f",
      disabled: "#c0c0c0",
      disabledText: "#808080",
      controlBg: "#c8c8c8",
      controlBgHover: "#dcdcdc",
      controlBgActive: "#b4b4b4",
      controlBgPrimary: "#3a6ab5",
      controlTextPrimary: "#ffffff",
      shadowOutset:
        "inset -1px -1px #000000, inset 1px 1px #ffffff, inset -2px -2px #808080, inset 2px 2px #dfdfdf",
      shadowInset:
        "inset -1px -1px #ffffff, inset 1px 1px #000000, inset -2px -2px #dfdfdf, inset 2px 2px #808080",
      shadowWindow: "2px 2px 0 rgba(0, 0, 0, 0.4)",
      radius: "0px",
      radiusWindow: "0px",
      radiusControl: "0px",
      borderWidth: "0px",
      fontSize: "12px",
      lineHeight: "1.25",
      controlHeight: "23px",
      titlebarHeight: "20px",
      space: "8px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "haiku-os",
    slug: "haiku-os",
    name: "Haiku",
    year: 2018,
    era: "Desktop OS",
    description:
      "The BeOS resurrection, refined: yellow title tabs, clean gray chrome, a Deskbar in the corner, and speed as a design principle.",
    tags: ["haiku", "beos", "yellow-tabs", "open-source", "community"],
    engine: "beos",
    controls: "beos",
    desktopPattern: "none",
    fonts: { ui: "Noto Sans, \"Segoe UI\", sans-serif", mono: monoStack, display: "Noto Sans, \"Segoe UI\", sans-serif" },
    tokens: {
      desktop: "linear-gradient(180deg, #1f3050, #0d1526)",
      surface: "#d4d4d4",
      surfaceAlt: "#e6e6e6",
      text: "#1e1e1e",
      textMuted: "#5a5a5a",
      textOnAccent: "#ffffff",
      accent: "#336ea0",
      accentHover: "#4384ba",
      titlebarBg: "#c8c8c8",
      titlebarText: "#1e1e1e",
      titlebarInactiveBg: "#b8b8b8",
      titlebarInactiveText: "#5a5a5a",
      titleLabelBg: "#ffcb2e",
      borderHigh: "#ffffff",
      borderLight: "#e8e8e8",
      borderDark: "#8a8a8a",
      borderLow: "#5a5a5a",
      fieldBg: "#ffffff",
      fieldText: "#1e1e1e",
      selectionBg: "#336ea0",
      selectionText: "#ffffff",
      focus: "#336ea0",
      danger: "#a83232",
      success: "#2a7a3a",
      warning: "#b8912f",
      disabled: "#c8c8c8",
      disabledText: "#8a8a8a",
      controlBg: "#d4d4d4",
      controlBgHover: "#e0e0e0",
      controlBgActive: "#c0c0c0",
      controlBgPrimary: "#336ea0",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset -1px -1px #8a8a8a, inset 1px 1px #ffffff",
      shadowInset: "inset -1px -1px #ffffff, inset 1px 1px #8a8a8a",
      shadowWindow: "2px 2px 0 rgba(0, 0, 0, 0.35)",
      radius: "3px",
      radiusWindow: "4px",
      radiusControl: "3px",
      borderWidth: "1px",
      fontSize: "13px",
      lineHeight: "1.3",
      controlHeight: "26px",
      titlebarHeight: "22px",
      space: "8px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "elementary-os",
    slug: "elementary-os",
    name: "elementary OS",
    year: 2013,
    era: "Desktop OS",
    description:
      "Pantheon's quiet discipline: airy light chrome, pill-shaped indicators, a dock of silent icons, typography doing all the talking.",
    tags: ["elementary", "pantheon", "linux", "design", "minimal"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    taskbarPosition: "top",
    fonts: { ui: "Inter, \"Segoe UI\", sans-serif", mono: monoStack, display: "Inter, \"Segoe UI\", sans-serif" },
    tokens: {
      desktop: "linear-gradient(180deg, #455a6d, #26313d)",
      surface: "#fcfcfc",
      surfaceAlt: "#f2f4f6",
      text: "#2e3440",
      textMuted: "#7f8c98",
      textOnAccent: "#ffffff",
      accent: "#41a9e4",
      accentHover: "#5cbaf0",
      titlebarBg: "linear-gradient(#fafbfb, #eceef0)",
      titlebarText: "#2e3440",
      titlebarInactiveBg: "#f2f4f6",
      titlebarInactiveText: "#7f8c98",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#eef0f2",
      borderDark: "#d3d8dc",
      borderLow: "#b0b8be",
      fieldBg: "#ffffff",
      fieldText: "#2e3440",
      selectionBg: "#41a9e4",
      selectionText: "#ffffff",
      focus: "#41a9e4",
      danger: "#d0433a",
      success: "#3f9a5c",
      warning: "#f0a020",
      disabled: "#f2f4f6",
      disabledText: "#b8c0c6",
      controlBg: "#ffffff",
      controlBgHover: "#f2f4f6",
      controlBgActive: "#e6eaee",
      controlBgPrimary: "#41a9e4",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 0 0 1px #d3d8dc",
      shadowInset: "inset 0 1px 2px rgba(46, 52, 64, 0.06)",
      shadowWindow: "0 6px 20px rgba(30, 40, 52, 0.22)",
      radius: "6px",
      radiusWindow: "8px",
      radiusControl: "6px",
      borderWidth: "0px",
      fontSize: "13px",
      lineHeight: "1.45",
      controlHeight: "32px",
      titlebarHeight: "34px",
      space: "12px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "ubuntu-unity",
    slug: "ubuntu-unity",
    name: "Ubuntu Unity",
    year: 2011,
    era: "Desktop OS",
    description:
      "The aubergine years: dark Ambiance chrome with orange selections, a launcher down the left, and window buttons exiled to the top panel.",
    tags: ["ubuntu", "unity", "ambiance", "linux", "aubergine"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    taskbarPosition: "top",
    fonts: { ui: ubuntuStack, mono: monoStack, display: ubuntuStack },
    tokens: {
      desktop: "#2c001e",
      surface: "#f2f1f0",
      surfaceAlt: "#e8e6e4",
      text: "#2c2c2c",
      textMuted: "#7a756d",
      textOnAccent: "#ffffff",
      accent: "#e95420",
      accentHover: "#f3743a",
      titlebarBg: "linear-gradient(#4d4c48, #383733)",
      titlebarText: "#dfdbd2",
      titlebarInactiveBg: "#3c3b37",
      titlebarInactiveText: "#8f887d",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#f4f3f2",
      borderDark: "#c8c5c1",
      borderLow: "#a09c95",
      fieldBg: "#ffffff",
      fieldText: "#2c2c2c",
      selectionBg: "#e95420",
      selectionText: "#ffffff",
      focus: "#e95420",
      danger: "#c7412b",
      success: "#3aa04a",
      warning: "#f0a020",
      disabled: "#e8e6e4",
      disabledText: "#a8a49c",
      controlBg: "#faf9f8",
      controlBgHover: "#ffffff",
      controlBgActive: "#e8e6e4",
      controlBgPrimary: "#e95420",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 0 0 1px #c8c5c1",
      shadowInset: "inset 0 1px 2px rgba(44, 44, 44, 0.08)",
      shadowWindow: "0 6px 18px rgba(20, 10, 14, 0.35)",
      radius: "5px",
      radiusWindow: "7px",
      radiusControl: "5px",
      borderWidth: "0px",
      fontSize: "13px",
      lineHeight: "1.4",
      controlHeight: "30px",
      titlebarHeight: "32px",
      space: "10px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "longhorn",
    slug: "longhorn",
    name: "Windows Longhorn",
    year: 2003,
    era: "Desktop OS",
    description:
      "The Vista that never was, at its Plex peak: slate-blue gradients, a Sidebar of gadgets, and optimism you could install from a torrent.",
    tags: ["microsoft", "longhorn", "plex", "cancelled", "milestone"],
    engine: "aero",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: "\"Segoe UI\", Tahoma, sans-serif", mono: monoStack, display: "\"Segoe UI\", Tahoma, sans-serif" },
    tokens: {
      desktop: "linear-gradient(180deg, #3a5a7a, #1d3448)",
      surface: "#eceff2",
      surfaceAlt: "#e0e5ea",
      text: "#1c2830",
      textMuted: "#5a6874",
      textOnAccent: "#ffffff",
      accent: "#4a78a8",
      accentHover: "#5c8abc",
      titlebarBg: "linear-gradient(#8fb0d8, #5878a8)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "linear-gradient(#b4c2d4, #8a9cb2)",
      titlebarInactiveText: "#e8eef4",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#eef2f6",
      borderDark: "#a8b6c4",
      borderLow: "#8494a4",
      fieldBg: "#ffffff",
      fieldText: "#1c2830",
      selectionBg: "#3a6a9e",
      selectionText: "#ffffff",
      focus: "#4a78a8",
      danger: "#b04a3a",
      success: "#3a8a4a",
      warning: "#d9982a",
      disabled: "#e0e5ea",
      disabledText: "#a0acb6",
      controlBg: "linear-gradient(#f8fafc, #d8e0e8)",
      controlBgHover: "linear-gradient(#ffffff, #e4ebf2)",
      controlBgActive: "#c8d4de",
      controlBgPrimary: "linear-gradient(#6a96c4, #406898)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 3px rgba(20, 36, 52, 0.3)",
      shadowInset: "inset 0 2px 4px rgba(20, 36, 52, 0.18)",
      shadowWindow: "0 8px 24px rgba(20, 36, 52, 0.4)",
      radius: "4px",
      radiusWindow: "6px",
      radiusControl: "3px",
      borderWidth: "1px",
      fontSize: "12px",
      lineHeight: "1.35",
      controlHeight: "26px",
      titlebarHeight: "28px",
      space: "8px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "geos",
    slug: "geos",
    name: "GeoWorks Ensemble",
    year: 1990,
    era: "Desktop OS",
    description:
      "A full GUI in 16 colors for your 286: warm gray chrome, chunky bevels, drive icons, and menus that felt like magic on DOS.",
    tags: ["geoworks", "geos", "dos-era", "16-color", "gui"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: genevaStack, mono: monoStack, display: genevaStack },
    tokens: {
      desktop: "#aab2aa",
      surface: "#d8d4c8",
      surfaceAlt: "#c8c4b6",
      text: "#101010",
      textMuted: "#4a4a44",
      textOnAccent: "#ffffff",
      accent: "#1a3a6a",
      accentHover: "#2a4c84",
      titlebarBg: "#1a3a6a",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#8a887c",
      titlebarInactiveText: "#d8d4c8",
      titleLabelBg: "transparent",
      borderHigh: "#f4f2ea",
      borderLight: "#e4e0d4",
      borderDark: "#8a8676",
      borderLow: "#5a564a",
      fieldBg: "#ffffff",
      fieldText: "#101010",
      selectionBg: "#1a3a6a",
      selectionText: "#ffffff",
      focus: "#101010",
      danger: "#8a2a22",
      success: "#2a6a2a",
      warning: "#997a1a",
      disabled: "#c8c4b6",
      disabledText: "#8a8676",
      controlBg: "#d8d4c8",
      controlBgHover: "#e4e0d4",
      controlBgActive: "#c8c4b6",
      controlBgPrimary: "#1a3a6a",
      controlTextPrimary: "#ffffff",
      shadowOutset:
        "inset -1px -1px #5a564a, inset 1px 1px #f4f2ea, inset -2px -2px #8a8676, inset 2px 2px #e4e0d4",
      shadowInset:
        "inset -1px -1px #f4f2ea, inset 1px 1px #5a564a, inset -2px -2px #e4e0d4, inset 2px 2px #8a8676",
      shadowWindow: "2px 2px 0 rgba(0, 0, 0, 0.4)",
      radius: "0px",
      radiusWindow: "0px",
      radiusControl: "0px",
      borderWidth: "0px",
      fontSize: "12px",
      lineHeight: "1.25",
      controlHeight: "24px",
      titlebarHeight: "20px",
      space: "8px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "plan-9",
    slug: "plan-9",
    name: "Plan 9",
    year: 1992,
    era: "Desktop OS",
    description:
      "Bell Labs' answer: rio's bare gray expanse, acme's pale-yellow columns, one-pixel black borders, and everything is a file — even the window.",
    tags: ["bell-labs", "plan9", "rio", "acme", "research"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: lucidaStack, mono: monoStack, display: lucidaStack },
    tokens: {
      desktop: "#8a8a8a",
      surface: "#f8f4dc",
      surfaceAlt: "#eae6c4",
      text: "#000000",
      textMuted: "#555555",
      textOnAccent: "#ffffff",
      accent: "#355a9f",
      accentHover: "#4a6fb8",
      titlebarBg: "#e8e4c4",
      titlebarText: "#000000",
      titlebarInactiveBg: "#d8d4b4",
      titlebarInactiveText: "#555555",
      titleLabelBg: "transparent",
      borderHigh: "#000000",
      borderLight: "#d8d4b4",
      borderDark: "#000000",
      borderLow: "#000000",
      fieldBg: "#ffffff",
      fieldText: "#000000",
      selectionBg: "#9db4dd",
      selectionText: "#000000",
      focus: "#355a9f",
      danger: "#8a2a2a",
      success: "#2a6a3a",
      warning: "#8a6a2a",
      disabled: "#d8d4b4",
      disabledText: "#8a8a7a",
      controlBg: "#e8e4c4",
      controlBgHover: "#f2eecf",
      controlBgActive: "#d8d4b4",
      controlBgPrimary: "#355a9f",
      controlTextPrimary: "#ffffff",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "1px 1px 0 #000000",
      radius: "0px",
      radiusWindow: "0px",
      radiusControl: "0px",
      borderWidth: "1px",
      fontSize: "12px",
      lineHeight: "1.35",
      controlHeight: "26px",
      titlebarHeight: "24px",
      space: "8px",
      letterSpacing: "0",
    },
  }),
];
