import {
  bevelWin95,
  chicagoStack,
  defineTheme,
  genevaStack,
  helveticaStack,
  lucidaStack,
  monoStack,
  plexSans,
  tahomaStack,
  vtStack,
} from "./helpers";
import type { RetroTheme } from "./types";

export const desktopOsThemes: RetroTheme[] = [
  defineTheme({
    id: "mac-system-7",
    slug: "mac-system-7",
    name: "Mac System 7",
    year: 1991,
    era: "Desktop OS",
    taskbarPosition: "top",
    description:
      "One-bit Macintosh chrome: Chicago titles, Geneva body, striped title bars, and dithered desktop grays.",
    tags: ["mac", "monochrome", "classic"],
    engine: "system7",
    controls: "mac",
    desktopPattern: "weave",
    fonts: { ui: chicagoStack, mono: monoStack, display: chicagoStack },
    tokens: {
      desktop: "#999999",
      surface: "#ffffff",
      surfaceAlt: "#dddddd",
      text: "#000000",
      textMuted: "#404040",
      accent: "#000000",
      accentHover: "#222222",
      titlebarBg: "#ffffff",
      titlebarText: "#000000",
      titlebarInactiveBg: "#ffffff",
      titlebarInactiveText: "#666666",
      titleLabelBg: "#ffffff",
      borderHigh: "#000000",
      borderLight: "#000000",
      borderDark: "#000000",
      borderLow: "#000000",
      fieldBg: "#ffffff",
      selectionBg: "#000000",
      selectionText: "#ffffff",
      focus: "#000000",
      controlBg: "#ffffff",
      controlBgHover: "#eeeeee",
      controlBgActive: "#dddddd",
      controlBgPrimary: "#ffffff",
      shadowOutset: "2px 2px 0 #000000",
      shadowInset: "inset 1px 1px 0 #000000",
      shadowWindow: "2px 2px 0 #000000",
      radius: "0px",
      fontSize: "13px",
      controlHeight: "22px",
      titlebarHeight: "20px",
    },
  }),
  defineTheme({
    id: "windows-95",
    slug: "windows-95",
    name: "Windows 95",
    year: 1995,
    era: "Desktop OS",
    description:
      "The canonical silver 3D bevel, solid navy title bars, teal desktop, and MS Sans / Tahoma chrome.",
    tags: ["windows", "bevel", "classic"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {},
  }),
  defineTheme({
    id: "windows-98",
    slug: "windows-98",
    name: "Windows 98",
    year: 1998,
    era: "Desktop OS",
    description:
      "Windows 95 chrome with the navy-to-sky title-bar gradient and slightly warmer desktop teal.",
    tags: ["windows", "bevel", "gradient"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {
      desktop: "#008080",
      titlebarBg: "linear-gradient(to right, #000080, #1084d0)",
      titlebarInactiveBg: "linear-gradient(to right, #808080, #c0c0c0)",
    },
  }),
  defineTheme({
    id: "windows-2000",
    slug: "windows-2000",
    name: "Windows 2000",
    year: 2000,
    era: "Desktop OS",
    description:
      "Warmer khaki button face, Tahoma everywhere, and the deep-blue to powder-blue title gradient.",
    tags: ["windows", "bevel", "tahoma"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {
      desktop: "#3a6ea5",
      surface: "#d4d0c8",
      surfaceAlt: "#e6e3db",
      controlBg: "#d4d0c8",
      controlBgHover: "#e6e3db",
      controlBgActive: "#d4d0c8",
      controlBgPrimary: "#d4d0c8",
      disabled: "#d4d0c8",
      titlebarBg: "linear-gradient(to right, #0a246a, #a6caf0)",
      titlebarInactiveBg: "linear-gradient(to right, #808080, #c0c0c0)",
      accent: "#0a246a",
      selectionBg: "#0a246a",
      shadowOutset:
        "inset -1px -1px #404040, inset 1px 1px #ffffff, inset -2px -2px #808080, inset 2px 2px #d4d0c8",
      shadowInset:
        "inset -1px -1px #ffffff, inset 1px 1px #404040, inset -2px -2px #d4d0c8, inset 2px 2px #808080",
    },
  }),
  defineTheme({
    id: "windows-xp-luna",
    slug: "windows-xp-luna",
    name: "Windows XP Luna",
    year: 2001,
    era: "Desktop OS",
    description:
      "Luna Blue: olive-tan surfaces, glossy blue title bars, pill buttons, and the Bliss-era desktop blue.",
    tags: ["windows", "luna", "glossy"],
    engine: "luna",
    controls: "win",
    desktopPattern: "horizon",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {
      desktop: "#3a6ea5",
      surface: "#ece9d8",
      surfaceAlt: "#f5f4ec",
      text: "#000000",
      textMuted: "#5a5748",
      accent: "#1c5ad6",
      accentHover: "#2a6ef0",
      titlebarBg: "linear-gradient(#0997ff, #0058e6 55%, #0050d0)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "linear-gradient(#adc1dc, #7a94b5)",
      titlebarInactiveText: "#d8e4f0",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#aca899",
      borderLow: "#0054e3",
      fieldBg: "#ffffff",
      selectionBg: "#316ac5",
      selectionText: "#ffffff",
      focus: "#f6c93b",
      controlBg: "linear-gradient(#ffffff, #ece9d8)",
      controlBgHover: "linear-gradient(#ffffff, #f5f4ec)",
      controlBgActive: "#ece9d8",
      controlBgPrimary: "linear-gradient(#b8e0a0, #3c9a3c 50%, #2d7a2d)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 0 #aca899",
      shadowInset: "inset 1px 1px 2px #aca899",
      shadowWindow: "2px 2px 8px rgba(0, 0, 0, 0.35)",
      radius: "3px",
      radiusWindow: "8px 8px 0 0",
      radiusControl: "3px",
      fontSize: "12px",
      controlHeight: "24px",
      titlebarHeight: "30px",
    },
  }),
  defineTheme({
    id: "windows-7-aero",
    slug: "windows-7-aero",
    name: "Windows 7 Aero",
    year: 2009,
    era: "Desktop OS",
    description:
      "Frosted glass title bars, rounded frames, Segoe-like type, and the Aero desktop glow.",
    tags: ["windows", "aero", "glass"],
    engine: "aero",
    controls: "win",
    desktopPattern: "horizon",
    fonts: {
      ui: `"Segoe UI", Tahoma, sans-serif`,
      mono: monoStack,
      display: `"Segoe UI", Tahoma, sans-serif`,
    },
    tokens: {
      desktop: "#1b4f8a",
      surface: "rgba(240, 244, 250, 0.92)",
      surfaceAlt: "rgba(255, 255, 255, 0.78)",
      text: "#1a1a1a",
      textMuted: "#445566",
      accent: "#1b74d6",
      accentHover: "#3a8ce6",
      titlebarBg: "linear-gradient(rgba(255,255,255,0.55), rgba(170,200,230,0.28))",
      titlebarText: "#1a2a3a",
      titlebarInactiveBg: "linear-gradient(rgba(255,255,255,0.28), rgba(180,190,200,0.18))",
      titlebarInactiveText: "#445566",
      borderHigh: "rgba(255,255,255,0.85)",
      borderLight: "rgba(255,255,255,0.65)",
      borderDark: "rgba(40,70,110,0.45)",
      borderLow: "rgba(20,40,70,0.55)",
      fieldBg: "#ffffff",
      selectionBg: "#3399ff",
      selectionText: "#ffffff",
      focus: "#3a8ce6",
      controlBg: "linear-gradient(#ffffff, #e4ecf5)",
      controlBgHover: "linear-gradient(#ffffff, #f2f7fc)",
      controlBgActive: "#d5e4f3",
      controlBgPrimary: "linear-gradient(#6fb8ff, #1b74d6)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "0 1px 0 rgba(255,255,255,0.8), 0 1px 3px rgba(0,0,0,0.18)",
      shadowInset: "inset 0 1px 2px rgba(0,0,0,0.12)",
      shadowWindow: "0 8px 28px rgba(0,0,0,0.28)",
      radius: "6px",
      radiusWindow: "8px",
      radiusControl: "4px",
      borderWidth: "1px",
      fontSize: "13px",
      controlHeight: "26px",
      titlebarHeight: "32px",
    },
  }),
  defineTheme({
    id: "aqua-osx",
    slug: "aqua-osx",
    name: "Mac OS X Aqua",
    year: 2001,
    era: "Desktop OS",
    taskbarPosition: "top",
    description:
      "Gel buttons, traffic-light window controls, pinstripe surfaces, and Lucida Grande.",
    tags: ["mac", "aqua", "gel"],
    engine: "aqua",
    controls: "mac",
    desktopPattern: "pinstripe",
    fonts: { ui: lucidaStack, mono: monoStack, display: lucidaStack },
    tokens: {
      desktop: "#c8c8c8",
      surface: "#ececec",
      surfaceAlt: "#f6f6f6",
      text: "#1a1a1a",
      textMuted: "#5a5a5a",
      accent: "#4c8dff",
      accentHover: "#6aa0ff",
      titlebarBg: "linear-gradient(#f4f4f4, #c8c8c8)",
      titlebarText: "#2a2a2a",
      titlebarInactiveBg: "linear-gradient(#f0f0f0, #d8d8d8)",
      titlebarInactiveText: "#7a7a7a",
      borderHigh: "#ffffff",
      borderLight: "#e8e8e8",
      borderDark: "#8a8a8a",
      borderLow: "#5a5a5a",
      fieldBg: "#ffffff",
      selectionBg: "#4c8dff",
      selectionText: "#ffffff",
      focus: "#4c8dff",
      controlBg: "linear-gradient(#ffffff, #dcdcdc)",
      controlBgHover: "linear-gradient(#ffffff, #ececec)",
      controlBgActive: "linear-gradient(#d0d0d0, #f0f0f0)",
      controlBgPrimary: "linear-gradient(#9ec4ff, #1d5fe0 55%, #163fb0)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 2px rgba(0,0,0,0.18)",
      shadowInset: "inset 0 1px 2px rgba(0,0,0,0.2)",
      shadowWindow: "0 10px 28px rgba(0,0,0,0.28)",
      radius: "8px",
      radiusWindow: "8px",
      radiusControl: "12px",
      borderWidth: "1px",
      fontSize: "13px",
      controlHeight: "24px",
      titlebarHeight: "22px",
    },
  }),
  defineTheme({
    id: "macos9-platinum",
    slug: "macos9-platinum",
    name: "Mac OS 9 Platinum",
    year: 1999,
    era: "Desktop OS",
    taskbarPosition: "top",
    description:
      "Apple Platinum: pinstripe title bars, brushed gray controls, and Charcoal / Geneva type.",
    tags: ["mac", "platinum", "pinstripe"],
    engine: "platinum",
    controls: "mac",
    desktopPattern: "pinstripe",
    fonts: { ui: genevaStack, mono: monoStack, display: chicagoStack },
    tokens: {
      desktop: "#808080",
      surface: "#dddddd",
      surfaceAlt: "#eeeeee",
      text: "#000000",
      textMuted: "#555555",
      accent: "#3a6eab",
      accentHover: "#4a82c4",
      titlebarBg: "linear-gradient(#f0f0f0, #c0c0c0)",
      titlebarText: "#000000",
      titlebarInactiveBg: "#dddddd",
      titlebarInactiveText: "#666666",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#eeeeee",
      borderDark: "#888888",
      borderLow: "#444444",
      fieldBg: "#ffffff",
      selectionBg: "#3a6eab",
      selectionText: "#ffffff",
      focus: "#3a6eab",
      controlBg: "linear-gradient(#f5f5f5, #c8c8c8)",
      controlBgHover: "linear-gradient(#ffffff, #d8d8d8)",
      controlBgActive: "linear-gradient(#b8b8b8, #e0e0e0)",
      controlBgPrimary: "linear-gradient(#8eb4e0, #3a6eab)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 1px 1px 0 #ffffff, inset -1px -1px 0 #666666",
      shadowInset: "inset 1px 1px 0 #666666, inset -1px -1px 0 #ffffff",
      shadowWindow: "2px 2px 0 rgba(0,0,0,0.35)",
      radius: "3px",
      radiusWindow: "3px",
      radiusControl: "3px",
      borderWidth: "1px",
      fontSize: "12px",
      controlHeight: "22px",
      titlebarHeight: "20px",
    },
  }),
  defineTheme({
    id: "amiga-workbench",
    slug: "amiga-workbench",
    name: "Amiga Workbench",
    year: 1985,
    era: "Desktop OS",
    description:
      "Workbench 1.x: deep blue desktop, orange selection, chunky four-color gadgets, Topaz-like type.",
    tags: ["amiga", "orange", "blue"],
    engine: "amiga",
    controls: "amiga",
    desktopPattern: "dots",
    fonts: {
      ui: `"IBM Plex Sans", Tahoma, sans-serif`,
      mono: monoStack,
      display: `"IBM Plex Sans", Tahoma, sans-serif`,
    },
    tokens: {
      desktop: "#0050aa",
      surface: "#aaaaaa",
      surfaceAlt: "#ffffff",
      text: "#000000",
      textMuted: "#222222",
      accent: "#ff8800",
      accentHover: "#ffaa33",
      titlebarBg: "#0050aa",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#000000",
      titlebarInactiveText: "#aaaaaa",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#000000",
      borderLow: "#000000",
      fieldBg: "#ffffff",
      selectionBg: "#ff8800",
      selectionText: "#000000",
      focus: "#ff8800",
      danger: "#aa0000",
      success: "#00aa00",
      warning: "#ff8800",
      controlBg: "#aaaaaa",
      controlBgHover: "#bbbbbb",
      controlBgActive: "#888888",
      controlBgPrimary: "#ff8800",
      controlTextPrimary: "#000000",
      shadowOutset: "inset 2px 2px 0 #ffffff, inset -2px -2px 0 #000000",
      shadowInset: "inset 2px 2px 0 #000000, inset -2px -2px 0 #ffffff",
      shadowWindow: "none",
      radius: "0px",
      fontSize: "13px",
      controlHeight: "24px",
      titlebarHeight: "20px",
      letterSpacing: "0.01em",
    },
  }),
  defineTheme({
    id: "nextstep",
    slug: "nextstep",
    name: "NeXTSTEP",
    year: 1989,
    era: "Desktop OS",
    description:
      "Dark chiseled slate, black title bars, dimensional buttons, and the original Unix workstation look.",
    tags: ["next", "greyscale", "unix"],
    engine: "nextstep",
    controls: "next",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "#555561",
      surface: "#aaaaaf",
      surfaceAlt: "#c8c8ce",
      text: "#000000",
      textMuted: "#333338",
      accent: "#000000",
      accentHover: "#222226",
      titlebarBg: "#000000",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#444448",
      titlebarInactiveText: "#bbbbbb",
      borderHigh: "#f0f0f4",
      borderLight: "#d0d0d4",
      borderDark: "#606068",
      borderLow: "#2c2c30",
      fieldBg: "#ffffff",
      selectionBg: "#000000",
      selectionText: "#ffffff",
      focus: "#000000",
      controlBg: "linear-gradient(#d8d8de, #9a9aa2)",
      controlBgHover: "linear-gradient(#e8e8ee, #aaaab0)",
      controlBgActive: "linear-gradient(#8a8a92, #c8c8ce)",
      controlBgPrimary: "linear-gradient(#888890, #2c2c30)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 1px 1px 0 #f0f0f4, inset -1px -1px 0 #2c2c30",
      shadowInset: "inset 1px 1px 0 #2c2c30, inset -1px -1px 0 #f0f0f4",
      shadowWindow: "3px 3px 0 rgba(0,0,0,0.45)",
      radius: "6px",
      radiusWindow: "8px",
      radiusControl: "6px",
      borderWidth: "1px",
      fontSize: "13px",
      controlHeight: "24px",
      titlebarHeight: "24px",
    },
  }),
  defineTheme({
    id: "beos",
    slug: "beos",
    name: "BeOS",
    year: 1996,
    era: "Desktop OS",
    description:
      "Yellow tabbed title bars, teal desktop, media-native widgets, and the Be box attitude.",
    tags: ["beos", "yellow", "tab"],
    engine: "beos",
    controls: "beos",
    desktopPattern: "none",
    fonts: {
      ui: `"Swis721 BT", "IBM Plex Sans", Tahoma, sans-serif`,
      mono: monoStack,
      display: `"IBM Plex Sans", Tahoma, sans-serif`,
    },
    tokens: {
      desktop: "#336868",
      surface: "#d8d8d8",
      surfaceAlt: "#ececec",
      text: "#202020",
      textMuted: "#555555",
      accent: "#ffcc00",
      accentHover: "#ffe066",
      titlebarBg: "linear-gradient(#ffe566, #e6b800)",
      titlebarText: "#202020",
      titlebarInactiveBg: "#c8c8c8",
      titlebarInactiveText: "#555555",
      borderHigh: "#ffffff",
      borderLight: "#eeeeee",
      borderDark: "#888888",
      borderLow: "#404040",
      fieldBg: "#ffffff",
      selectionBg: "#ffcc00",
      selectionText: "#202020",
      focus: "#ffcc00",
      controlBg: "linear-gradient(#f4f4f4, #c8c8c8)",
      controlBgHover: "linear-gradient(#ffffff, #d8d8d8)",
      controlBgActive: "#c0c0c0",
      controlBgPrimary: "linear-gradient(#ffe566, #e6b800)",
      controlTextPrimary: "#202020",
      shadowOutset: "inset 1px 1px 0 #ffffff, inset -1px -1px 0 #666666",
      shadowInset: "inset 1px 1px 2px rgba(0,0,0,0.2)",
      shadowWindow: "3px 3px 0 rgba(0,0,0,0.25)",
      radius: "3px",
      radiusWindow: "4px 12px 4px 4px",
      radiusControl: "3px",
      borderWidth: "1px",
      fontSize: "12px",
      controlHeight: "22px",
      titlebarHeight: "20px",
    },
  }),
  defineTheme({
    id: "os2-warp",
    slug: "os2-warp",
    name: "OS/2 Warp",
    year: 1994,
    era: "Desktop OS",
    description:
      "IBM Warp: teal Workplace Shell desktop, silver bevels, and the navy-to-cyan title fade.",
    tags: ["os2", "ibm", "bevel"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "tiles",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {
      desktop: "#2d7a7a",
      surface: "#c0c0c0",
      titlebarBg: "linear-gradient(to right, #00007f, #1084d0)",
      accent: "#00007f",
      selectionBg: "#00007f",
    },
  }),
  defineTheme({
    id: "cde-motif",
    slug: "cde-motif",
    name: "CDE / Motif",
    year: 1993,
    era: "Desktop OS",
    description:
      "Common Desktop Environment: dusty Motif bevels, teal selection, and workstation front-panel chrome.",
    tags: ["unix", "motif", "cde"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "#4a6b6b",
      surface: "#aeb2c3",
      surfaceAlt: "#c4c8d4",
      text: "#000000",
      accent: "#4a6b8a",
      titlebarBg: "#4a6b8a",
      titlebarInactiveBg: "#7a8494",
      controlBg: "#aeb2c3",
      controlBgHover: "#c4c8d4",
      controlBgPrimary: "#aeb2c3",
      selectionBg: "#4a6b8a",
      borderHigh: "#eceef4",
      borderLight: "#c4c8d4",
      borderDark: "#6a7080",
      borderLow: "#2a2e38",
      disabled: "#aeb2c3",
      shadowOutset:
        "inset -1px -1px #2a2e38, inset 1px 1px #eceef4, inset -2px -2px #6a7080, inset 2px 2px #c4c8d4",
      shadowInset:
        "inset -1px -1px #eceef4, inset 1px 1px #2a2e38, inset -2px -2px #c4c8d4, inset 2px 2px #6a7080",
    },
  }),
  defineTheme(
    {
      id: "templeos",
      slug: "templeos",
      name: "TempleOS",
      year: 2013,
      era: "Desktop OS",
      description:
        "16-color VGA God-kernel: royal blue desktop, bright primaries, and 8x8 bitmap type.",
      tags: ["templeos", "vga", "16-color"],
      engine: "pixel",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: vtStack, mono: vtStack, display: vtStack },
      tokens: {
        desktop: "#0000aa",
        surface: "#0000aa",
        surfaceAlt: "#0000ee",
        text: "#ffffff",
        textMuted: "#ffff55",
        textOnAccent: "#000000",
        accent: "#ffff00",
        accentHover: "#ffff88",
        titlebarBg: "#0000aa",
        titlebarText: "#ffff00",
        titlebarInactiveBg: "#000055",
        titlebarInactiveText: "#aaaaaa",
        borderHigh: "#ffffff",
        borderLight: "#55ffff",
        borderDark: "#000055",
        borderLow: "#ffffff",
        fieldBg: "#000088",
        fieldText: "#ffffff",
        selectionBg: "#ffff00",
        selectionText: "#0000aa",
        focus: "#ffff00",
        danger: "#ff0000",
        success: "#00ff00",
        warning: "#ffaa00",
        disabled: "#000088",
        disabledText: "#aaaaaa",
        controlBg: "#0000aa",
        controlBgHover: "#0000cc",
        controlBgActive: "#000088",
        controlBgPrimary: "#ffff00",
        controlTextPrimary: "#0000aa",
        shadowOutset: "none",
        shadowInset: "none",
        shadowWindow: "none",
        fontSize: "18px",
        controlHeight: "28px",
        titlebarHeight: "24px",
        letterSpacing: "0.02em",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "classic-gnome",
      slug: "classic-gnome",
      name: "Classic GNOME",
      year: 2002,
      era: "Desktop OS",
    taskbarPosition: "top",
      description:
        "GNOME 2 desktop: soft gray Clearlooks panels, Tango blue selections, and a calm sky gradient.",
      tags: ["gnome", "linux", "gtk", "clearlooks"],
      engine: "bevel",
      controls: "win",
      desktopPattern: "horizon",
      fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
      tokens: {
        desktop: "#729fcf",
        surface: "#eceae6",
        surfaceAlt: "#e0ddd8",
        text: "#2e3436",
        textMuted: "#6a737b",
        accent: "#3465a4",
        accentHover: "#4a7ec2",
        titlebarBg: "linear-gradient(#f6f5f3, #d6d3ce)",
        titlebarText: "#34465e",
        titlebarInactiveBg: "#e0ddd8",
        titlebarInactiveText: "#8a9199",
        borderHigh: "#ffffff",
        borderLight: "#f6f5f3",
        borderDark: "#a8a5a0",
        borderLow: "#787572",
        fieldBg: "#ffffff",
        fieldText: "#2e3436",
        selectionBg: "#3465a4",
        selectionText: "#ffffff",
        focus: "#3465a4",
        danger: "#cc0000",
        success: "#4e9a06",
        warning: "#c4a000",
        disabled: "#e0ddd8",
        disabledText: "#8a9199",
        controlBg: "linear-gradient(#fdfdfc, #e2e0dc)",
        controlBgHover: "linear-gradient(#ffffff, #eceae6)",
        controlBgActive: "#d6d3ce",
        controlBgPrimary: "linear-gradient(#7ba3d4, #3465a4)",
        controlTextPrimary: "#ffffff",
        shadowOutset: "inset -1px -1px #a8a5a0, inset 1px 1px #ffffff",
        shadowInset: "inset 0 1px 3px rgba(0, 0, 0, 0.12)",
        shadowWindow: "0 4px 14px rgba(0, 0, 0, 0.25)",
        radius: "4px",
        radiusWindow: "6px",
        radiusControl: "4px",
        borderWidth: "1px",
        fontSize: "13px",
        controlHeight: "26px",
        titlebarHeight: "24px",
        letterSpacing: "0",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "kde-3",
      slug: "kde-3",
      name: "KDE 3",
      year: 2002,
      era: "Desktop OS",
      description:
        "Keramik desktop: brushed blue gradients, a K-menu panel, Crystal icon shine, and Konqi blue.",
      tags: ["kde", "linux", "qt", "keramik"],
      engine: "bevel",
      controls: "win",
      desktopPattern: "none",
      fonts: { ui: plexSans, mono: monoStack, display: plexSans },
      tokens: {
        desktop: "#24568a",
        surface: "#d6d2ca",
        surfaceAlt: "#e4e1da",
        text: "#101010",
        textMuted: "#5a5f66",
        accent: "#1d5aa8",
        accentHover: "#2a6ec4",
        titlebarBg: "linear-gradient(#7a9cc4, #3a6a9e)",
        titlebarText: "#ffffff",
        titlebarInactiveBg: "#b8bcc2",
        titlebarInactiveText: "#5a5f66",
        borderHigh: "#ffffff",
        borderLight: "#e8e6e2",
        borderDark: "#8a8f96",
        borderLow: "#5a5f66",
        fieldBg: "#ffffff",
        fieldText: "#101010",
        selectionBg: "#1d5aa8",
        selectionText: "#ffffff",
        focus: "#ff8c00",
        danger: "#d0342c",
        success: "#2e8b3a",
        warning: "#f39c25",
        disabled: "#c8c4bc",
        disabledText: "#8a8f96",
        controlBg: "linear-gradient(#f4f2ee, #c8c4bc)",
        controlBgHover: "linear-gradient(#ffffff, #d8d4cc)",
        controlBgActive: "#b0aca4",
        controlBgPrimary: "linear-gradient(#5a9ae0, #1d5aa8)",
        controlTextPrimary: "#ffffff",
        shadowOutset: "inset -1px -1px #8a8f96, inset 1px 1px #ffffff",
        shadowInset: "inset 0 1px 3px rgba(0, 0, 0, 0.2)",
        shadowWindow: "0 6px 16px rgba(0, 0, 0, 0.4)",
        radius: "4px",
        radiusWindow: "6px",
        radiusControl: "4px",
        borderWidth: "1px",
        fontSize: "13px",
        lineHeight: "1.4",
        controlHeight: "26px",
        titlebarHeight: "24px",
        space: "8px",
        letterSpacing: "0",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "xfce-4",
      slug: "xfce-4",
      name: "XFCE 4",
      year: 2003,
      era: "Desktop OS",
      description:
        "Lightweight GTK desktop: quiet gray panels, a slim taskbar, and the mouse-blue accent.",
      tags: ["xfce", "linux", "gtk", "lightweight"],
      engine: "bevel",
      controls: "win",
      desktopPattern: "none",
      fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
      tokens: {
        desktop: "#3f4e5c",
        surface: "#e8e6e1",
        surfaceAlt: "#dcd8d2",
        text: "#2e3436",
        textMuted: "#6a737b",
        accent: "#3d6fb0",
        accentHover: "#4d82c6",
        titlebarBg: "linear-gradient(#eef0f2, #c8ccd2)",
        titlebarText: "#2e3436",
        titlebarInactiveBg: "#dcd8d2",
        titlebarInactiveText: "#8a9199",
        borderHigh: "#ffffff",
        borderLight: "#f6f5f3",
        borderDark: "#a8a5a0",
        borderLow: "#787572",
        fieldBg: "#ffffff",
        fieldText: "#2e3436",
        selectionBg: "#3d6fb0",
        selectionText: "#ffffff",
        focus: "#3d6fb0",
        danger: "#cc0000",
        success: "#4e9a06",
        warning: "#c4a000",
        disabled: "#e0ddd8",
        disabledText: "#8a9199",
        controlBg: "linear-gradient(#fdfdfd, #e2e0dc)",
        controlBgHover: "linear-gradient(#ffffff, #eceae6)",
        controlBgActive: "#d6d3ce",
        controlBgPrimary: "linear-gradient(#6a9ad4, #3d6fb0)",
        controlTextPrimary: "#ffffff",
        shadowOutset: "inset -1px -1px #a8a5a0, inset 1px 1px #ffffff",
        shadowInset: "inset 0 1px 2px rgba(0, 0, 0, 0.1)",
        shadowWindow: "0 4px 12px rgba(0, 0, 0, 0.25)",
        radius: "3px",
        radiusWindow: "4px",
        radiusControl: "3px",
        borderWidth: "1px",
        fontSize: "13px",
        lineHeight: "1.4",
        controlHeight: "25px",
        titlebarHeight: "23px",
        space: "8px",
        letterSpacing: "0",
      },
    },
    bevelWin95,
  ),
  defineTheme({
    id: "unix-x11",
    slug: "unix-x11",
    name: "Unix / X11",
    year: 1991,
    era: "Desktop OS",
    description:
      "Bare X11 and twm: stippled black root, hairline white frames, xterm mono, zero ornament.",
    tags: ["unix", "x11", "twm", "xterm", "monochrome"],
    engine: "terminal",
    controls: "none",
    desktopPattern: "dots",
    fonts: { ui: monoStack, mono: monoStack, display: monoStack },
    tokens: {
      desktop: "#000000",
      surface: "#000000",
      surfaceAlt: "#101010",
      text: "#ffffff",
      textMuted: "#8a8a8a",
      textOnAccent: "#ffffff",
      accent: "#ffffff",
      accentHover: "#c8c8c8",
      titlebarBg: "#ffffff",
      titlebarText: "#000000",
      titlebarInactiveBg: "#5a5a5a",
      titlebarInactiveText: "#000000",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#8a8a8a",
      borderLow: "#ffffff",
      fieldBg: "#000000",
      fieldText: "#ffffff",
      selectionBg: "#ffffff",
      selectionText: "#000000",
      focus: "#ffffff",
      danger: "#c8c8c8",
      success: "#8a8a8a",
      warning: "#c8c8c8",
      disabled: "#101010",
      disabledText: "#5a5a5a",
      controlBg: "#000000",
      controlBgHover: "#101010",
      controlBgActive: "#000000",
      controlBgPrimary: "#ffffff",
      controlTextPrimary: "#000000",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "none",
      radius: "0px",
      radiusWindow: "0px",
      radiusControl: "0px",
      borderWidth: "1px",
      fontSize: "14px",
      lineHeight: "1.35",
      controlHeight: "26px",
      titlebarHeight: "22px",
      space: "8px",
      letterSpacing: "0.04em",
    },
  }),
];
