import {
  bevelWin95,
  chicagoStack,
  defineTheme,
  genevaStack,
  helveticaStack,
  lucidaStack,
  monoStack,
  plexSans,
  tahomaStack,
  vtStack,
} from "./helpers";
import type { RetroTheme } from "./types";

export const desktopOsThemes: RetroTheme[] = [
  defineTheme({
    id: "mac-system-7",
    slug: "mac-system-7",
    name: "Mac System 7",
    year: 1991,
    era: "Desktop OS",
    taskbarPosition: "top",
    description:
      "One-bit Macintosh chrome: Chicago titles, Geneva body, striped title bars, and dithered desktop grays.",
    tags: ["mac", "monochrome", "classic"],
    engine: "system7",
    controls: "mac",
    desktopPattern: "weave",
    fonts: { ui: chicagoStack, mono: monoStack, display: chicagoStack },
    tokens: {
      desktop: "#999999",
      surface: "#ffffff",
      surfaceAlt: "#dddddd",
      text: "#000000",
      textMuted: "#404040",
      accent: "#000000",
      accentHover: "#222222",
      titlebarBg: "#ffffff",
      titlebarText: "#000000",
      titlebarInactiveBg: "#ffffff",
      titlebarInactiveText: "#666666",
      titleLabelBg: "#ffffff",
      borderHigh: "#000000",
      borderLight: "#000000",
      borderDark: "#000000",
      borderLow: "#000000",
      fieldBg: "#ffffff",
      selectionBg: "#000000",
      selectionText: "#ffffff",
      focus: "#000000",
      controlBg: "#ffffff",
      controlBgHover: "#eeeeee",
      controlBgActive: "#dddddd",
      controlBgPrimary: "#ffffff",
      shadowOutset: "2px 2px 0 #000000",
      shadowInset: "inset 1px 1px 0 #000000",
      shadowWindow: "2px 2px 0 #000000",
      radius: "0px",
      fontSize: "13px",
      controlHeight: "22px",
      titlebarHeight: "20px",
    },
  }),
  defineTheme({
    id: "windows-95",
    slug: "windows-95",
    name: "Windows 95",
    year: 1995,
    era: "Desktop OS",
    description:
      "The canonical silver 3D bevel, solid navy title bars, teal desktop, and MS Sans / Tahoma chrome.",
    tags: ["windows", "bevel", "classic"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {},
  }),
  defineTheme({
    id: "windows-98",
    slug: "windows-98",
    name: "Windows 98",
    year: 1998,
    era: "Desktop OS",
    description:
      "Windows 95 chrome with the navy-to-sky title-bar gradient and slightly warmer desktop teal.",
    tags: ["windows", "bevel", "gradient"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {
      desktop: "#008080",
      titlebarBg: "linear-gradient(to right, #000080, #1084d0)",
      titlebarInactiveBg: "linear-gradient(to right, #808080, #c0c0c0)",
    },
  }),
  defineTheme({
    id: "windows-2000",
    slug: "windows-2000",
    name: "Windows 2000",
    year: 2000,
    era: "Desktop OS",
    description:
      "Warmer khaki button face, Tahoma everywhere, and the deep-blue to powder-blue title gradient.",
    tags: ["windows", "bevel", "tahoma"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {
      desktop: "#3a6ea5",
      surface: "#d4d0c8",
      surfaceAlt: "#e6e3db",
      controlBg: "#d4d0c8",
      controlBgHover: "#e6e3db",
      controlBgActive: "#d4d0c8",
      controlBgPrimary: "#d4d0c8",
      disabled: "#d4d0c8",
      titlebarBg: "linear-gradient(to right, #0a246a, #a6caf0)",
      titlebarInactiveBg: "linear-gradient(to right, #808080, #c0c0c0)",
      accent: "#0a246a",
      selectionBg: "#0a246a",
      shadowOutset:
        "inset -1px -1px #404040, inset 1px 1px #ffffff, inset -2px -2px #808080, inset 2px 2px #d4d0c8",
      shadowInset:
        "inset -1px -1px #ffffff, inset 1px 1px #404040, inset -2px -2px #d4d0c8, inset 2px 2px #808080",
    },
  }),
  defineTheme({
    id: "windows-xp-luna",
    slug: "windows-xp-luna",
    name: "Windows XP Luna",
    year: 2001,
    era: "Desktop OS",
    description:
      "Luna Blue: olive-tan surfaces, glossy blue title bars, pill buttons, and the Bliss-era desktop blue.",
    tags: ["windows", "luna", "glossy"],
    engine: "luna",
    controls: "win",
    desktopPattern: "horizon",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {
      desktop: "#3a6ea5",
      surface: "#ece9d8",
      surfaceAlt: "#f5f4ec",
      text: "#000000",
      textMuted: "#5a5748",
      accent: "#1c5ad6",
      accentHover: "#2a6ef0",
      titlebarBg: "linear-gradient(#0997ff, #0058e6 55%, #0050d0)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "linear-gradient(#adc1dc, #7a94b5)",
      titlebarInactiveText: "#d8e4f0",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#aca899",
      borderLow: "#0054e3",
      fieldBg: "#ffffff",
      selectionBg: "#316ac5",
      selectionText: "#ffffff",
      focus: "#f6c93b",
      controlBg: "linear-gradient(#ffffff, #ece9d8)",
      controlBgHover: "linear-gradient(#ffffff, #f5f4ec)",
      controlBgActive: "#ece9d8",
      controlBgPrimary: "linear-gradient(#b8e0a0, #3c9a3c 50%, #2d7a2d)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 0 #aca899",
      shadowInset: "inset 1px 1px 2px #aca899",
      shadowWindow: "2px 2px 8px rgba(0, 0, 0, 0.35)",
      radius: "3px",
      radiusWindow: "8px 8px 0 0",
      radiusControl: "3px",
      fontSize: "12px",
      controlHeight: "24px",
      titlebarHeight: "30px",
    },
  }),
  defineTheme({
    id: "windows-7-aero",
    slug: "windows-7-aero",
    name: "Windows 7 Aero",
    year: 2009,
    era: "Desktop OS",
    description:
      "Frosted glass title bars, rounded frames, Segoe-like type, and the Aero desktop glow.",
    tags: ["windows", "aero", "glass"],
    engine: "aero",
    controls: "win",
    desktopPattern: "horizon",
    fonts: {
      ui: `"Segoe UI", Tahoma, sans-serif`,
      mono: monoStack,
      display: `"Segoe UI", Tahoma, sans-serif`,
    },
    tokens: {
      desktop: "#1b4f8a",
      surface: "rgba(240, 244, 250, 0.92)",
      surfaceAlt: "rgba(255, 255, 255, 0.78)",
      text: "#1a1a1a",
      textMuted: "#445566",
      accent: "#1b74d6",
      accentHover: "#3a8ce6",
      titlebarBg: "linear-gradient(rgba(255,255,255,0.55), rgba(170,200,230,0.28))",
      titlebarText: "#1a2a3a",
      titlebarInactiveBg: "linear-gradient(rgba(255,255,255,0.28), rgba(180,190,200,0.18))",
      titlebarInactiveText: "#445566",
      borderHigh: "rgba(255,255,255,0.85)",
      borderLight: "rgba(255,255,255,0.65)",
      borderDark: "rgba(40,70,110,0.45)",
      borderLow: "rgba(20,40,70,0.55)",
      fieldBg: "#ffffff",
      selectionBg: "#3399ff",
      selectionText: "#ffffff",
      focus: "#3a8ce6",
      controlBg: "linear-gradient(#ffffff, #e4ecf5)",
      controlBgHover: "linear-gradient(#ffffff, #f2f7fc)",
      controlBgActive: "#d5e4f3",
      controlBgPrimary: "linear-gradient(#6fb8ff, #1b74d6)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "0 1px 0 rgba(255,255,255,0.8), 0 1px 3px rgba(0,0,0,0.18)",
      shadowInset: "inset 0 1px 2px rgba(0,0,0,0.12)",
      shadowWindow: "0 8px 28px rgba(0,0,0,0.28)",
      radius: "6px",
      radiusWindow: "8px",
      radiusControl: "4px",
      borderWidth: "1px",
      fontSize: "13px",
      controlHeight: "26px",
      titlebarHeight: "32px",
    },
  }),
  defineTheme({
    id: "aqua-osx",
    slug: "aqua-osx",
    name: "Mac OS X Aqua",
    year: 2001,
    era: "Desktop OS",
    taskbarPosition: "top",
    description:
      "Gel buttons, traffic-light window controls, pinstripe surfaces, and Lucida Grande.",
    tags: ["mac", "aqua", "gel"],
    engine: "aqua",
    controls: "mac",
    desktopPattern: "pinstripe",
    fonts: { ui: lucidaStack, mono: monoStack, display: lucidaStack },
    tokens: {
      desktop: "#c8c8c8",
      surface: "#ececec",
      surfaceAlt: "#f6f6f6",
      text: "#1a1a1a",
      textMuted: "#5a5a5a",
      accent: "#4c8dff",
      accentHover: "#6aa0ff",
      titlebarBg: "linear-gradient(#f4f4f4, #c8c8c8)",
      titlebarText: "#2a2a2a",
      titlebarInactiveBg: "linear-gradient(#f0f0f0, #d8d8d8)",
      titlebarInactiveText: "#7a7a7a",
      borderHigh: "#ffffff",
      borderLight: "#e8e8e8",
      borderDark: "#8a8a8a",
      borderLow: "#5a5a5a",
      fieldBg: "#ffffff",
      selectionBg: "#4c8dff",
      selectionText: "#ffffff",
      focus: "#4c8dff",
      controlBg: "linear-gradient(#ffffff, #dcdcdc)",
      controlBgHover: "linear-gradient(#ffffff, #ececec)",
      controlBgActive: "linear-gradient(#d0d0d0, #f0f0f0)",
      controlBgPrimary: "linear-gradient(#9ec4ff, #1d5fe0 55%, #163fb0)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 2px rgba(0,0,0,0.18)",
      shadowInset: "inset 0 1px 2px rgba(0,0,0,0.2)",
      shadowWindow: "0 10px 28px rgba(0,0,0,0.28)",
      radius: "8px",
      radiusWindow: "8px",
      radiusControl: "12px",
      borderWidth: "1px",
      fontSize: "13px",
      controlHeight: "24px",
      titlebarHeight: "22px",
    },
  }),
  defineTheme({
    id: "macos9-platinum",
    slug: "macos9-platinum",
    name: "Mac OS 9 Platinum",
    year: 1999,
    era: "Desktop OS",
    taskbarPosition: "top",
    description:
      "Apple Platinum: pinstripe title bars, brushed gray controls, and Charcoal / Geneva type.",
    tags: ["mac", "platinum", "pinstripe"],
    engine: "platinum",
    controls: "mac",
    desktopPattern: "pinstripe",
    fonts: { ui: genevaStack, mono: monoStack, display: chicagoStack },
    tokens: {
      desktop: "#808080",
      surface: "#dddddd",
      surfaceAlt: "#eeeeee",
      text: "#000000",
      textMuted: "#555555",
      accent: "#3a6eab",
      accentHover: "#4a82c4",
      titlebarBg: "linear-gradient(#f0f0f0, #c0c0c0)",
      titlebarText: "#000000",
      titlebarInactiveBg: "#dddddd",
      titlebarInactiveText: "#666666",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#eeeeee",
      borderDark: "#888888",
      borderLow: "#444444",
      fieldBg: "#ffffff",
      selectionBg: "#3a6eab",
      selectionText: "#ffffff",
      focus: "#3a6eab",
      controlBg: "linear-gradient(#f5f5f5, #c8c8c8)",
      controlBgHover: "linear-gradient(#ffffff, #d8d8d8)",
      controlBgActive: "linear-gradient(#b8b8b8, #e0e0e0)",
      controlBgPrimary: "linear-gradient(#8eb4e0, #3a6eab)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 1px 1px 0 #ffffff, inset -1px -1px 0 #666666",
      shadowInset: "inset 1px 1px 0 #666666, inset -1px -1px 0 #ffffff",
      shadowWindow: "2px 2px 0 rgba(0,0,0,0.35)",
      radius: "3px",
      radiusWindow: "3px",
      radiusControl: "3px",
      borderWidth: "1px",
      fontSize: "12px",
      controlHeight: "22px",
      titlebarHeight: "20px",
    },
  }),
  defineTheme(
    {
      id: "windows-vista",
      slug: "windows-vista",
      name: "Windows Vista",
      year: 2007,
      era: "Desktop OS",
      description:
        "Aero glass sheet: teal aurora wallpaper, blue-black frosted frames, glossy jet buttons, and the orb taskbar.",
      tags: ["windows", "vista", "aero", "glass"],
      engine: "aero",
      controls: "win",
      desktopPattern: "none",
      fonts: {
        ui: "Segoe UI, Tahoma, 'Segoe UI', sans-serif",
        mono: monoStack,
        display: "Segoe UI, Tahoma, sans-serif",
      },
      tokens: {
        desktop: "radial-gradient(ellipse at 50% 85%, #1e6b52 0%, #0a3830 45%, #05141c 100%)",
        surface: "rgba(168, 196, 222, 0.38)",
        surfaceAlt: "rgba(196, 214, 232, 0.45)",
        text: "#0c1a24",
        textMuted: "#42586a",
        textOnAccent: "#ffffff",
        accent: "#1c5f9e",
        accentHover: "#2f7ac0",
        titlebarBg: "linear-gradient(rgba(185, 214, 238, 0.75), rgba(78, 118, 158, 0.45))",
        titlebarText: "#0c1822",
        titlebarInactiveBg: "rgba(200, 214, 226, 0.4)",
        titlebarInactiveText: "#6a7c8a",
        titleLabelBg: "transparent",
        borderHigh: "rgba(205, 228, 245, 0.9)",
        borderLight: "rgba(160, 195, 225, 0.65)",
        borderDark: "rgba(30, 60, 90, 0.55)",
        borderLow: "rgba(15, 35, 60, 0.75)",
        fieldBg: "#ffffff",
        fieldText: "#0c1a24",
        selectionBg: "#2f6bb8",
        selectionText: "#ffffff",
        focus: "#1c5f9e",
        danger: "#c0392b",
        success: "#2e8b3a",
        warning: "#d39c2a",
        disabled: "rgba(210, 222, 232, 0.6)",
        disabledText: "#8a9aa8",
        controlBg: "linear-gradient(#5a606a, #15171d)",
        controlBgHover: "linear-gradient(#6d747e, #23262e)",
        controlBgActive: "#0c0e12",
        controlBgPrimary: "linear-gradient(#6ab0f0, #1c5f9e)",
        controlTextPrimary: "#ffffff",
        controlText: "#f2f4f8",
        shadowOutset: "inset 0 1px 0 rgba(255, 255, 255, 0.35), 0 1px 2px rgba(0, 0, 0, 0.4)",
        shadowInset: "inset 0 1px 3px rgba(0, 0, 0, 0.25)",
        shadowWindow: "0 10px 28px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(120, 160, 200, 0.55)",
        radius: "4px",
        radiusWindow: "8px 8px 3px 3px",
        radiusControl: "4px",
        borderWidth: "1px",
        fontSize: "12px",
        lineHeight: "1.35",
        controlHeight: "26px",
        titlebarHeight: "30px",
        space: "10px",
        letterSpacing: "0",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "windows-11",
      slug: "windows-11",
      name: "Windows 11 Fluent",
      year: 2021,
      era: "Desktop OS",
      description:
        "Fluent design: mica-soft windows, rounded everything, quiet hover chrome, and the centered taskbar.",
      tags: ["windows", "win11", "fluent", "mica"],
      engine: "fluent",
      controls: "win",
      desktopPattern: "none",
      fonts: {
        ui: "'Segoe UI Variable', 'Segoe UI', system-ui, sans-serif",
        mono: "'Cascadia Code', ui-monospace, Consolas, monospace",
        display: "'Segoe UI Variable', 'Segoe UI', system-ui, sans-serif",
      },
      tokens: {
        desktop: "radial-gradient(circle at 65% 35%, #5b9bd5 0%, #23477e 45%, #0d1b3e 100%)",
        surface: "rgba(250, 250, 250, 0.92)",
        surfaceAlt: "rgba(243, 243, 243, 0.95)",
        text: "#1a1a1a",
        textMuted: "#616161",
        textOnAccent: "#ffffff",
        accent: "#0067c0",
        accentHover: "#1975c5",
        titlebarBg: "transparent",
        titlebarText: "#1a1a1a",
        titlebarInactiveBg: "rgba(245, 245, 245, 0.85)",
        titlebarInactiveText: "#8a8a8a",
        titleLabelBg: "transparent",
        borderHigh: "#ffffff",
        borderLight: "#e6e6e6",
        borderDark: "#d5d5d5",
        borderLow: "#b8b8b8",
        fieldBg: "#ffffff",
        fieldText: "#1a1a1a",
        selectionBg: "#0067c0",
        selectionText: "#ffffff",
        focus: "#0067c0",
        danger: "#c42b1c",
        success: "#0f7b0f",
        warning: "#9d5d00",
        disabled: "#f0f0f0",
        disabledText: "#9a9a9a",
        controlBg: "#fdfdfd",
        controlBgHover: "#f0f0f0",
        controlBgActive: "#e5e5e5",
        controlBgPrimary: "#0067c0",
        controlTextPrimary: "#ffffff",
        shadowOutset: "inset 0 0 0 1px #ebebeb, 0 1px 2px rgba(0, 0, 0, 0.08)",
        shadowInset: "inset 0 1px 2px rgba(0, 0, 0, 0.08)",
        shadowWindow: "0 18px 44px rgba(0, 0, 0, 0.24), 0 0 0 1px rgba(0, 0, 0, 0.05)",
        radius: "6px",
        radiusWindow: "8px",
        radiusControl: "6px",
        borderWidth: "1px",
        fontSize: "13px",
        lineHeight: "1.45",
        controlHeight: "30px",
        titlebarHeight: "36px",
        space: "12px",
        letterSpacing: "0",
      },
    },
    bevelWin95,
  ),
  defineTheme({
    id: "amiga-workbench",
    slug: "amiga-workbench",
    name: "Amiga Workbench",
    year: 1985,
    era: "Desktop OS",
    description:
      "Workbench 1.x: deep blue desktop, orange selection, chunky four-color gadgets, Topaz-like type.",
    tags: ["amiga", "orange", "blue"],
    engine: "amiga",
    controls: "amiga",
    desktopPattern: "dots",
    fonts: {
      ui: `"IBM Plex Sans", Tahoma, sans-serif`,
      mono: monoStack,
      display: `"IBM Plex Sans", Tahoma, sans-serif`,
    },
    tokens: {
      desktop: "#0050aa",
      surface: "#aaaaaa",
      surfaceAlt: "#ffffff",
      text: "#000000",
      textMuted: "#222222",
      accent: "#ff8800",
      accentHover: "#ffaa33",
      titlebarBg: "#0050aa",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#000000",
      titlebarInactiveText: "#aaaaaa",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#000000",
      borderLow: "#000000",
      fieldBg: "#ffffff",
      selectionBg: "#ff8800",
      selectionText: "#000000",
      focus: "#ff8800",
      danger: "#aa0000",
      success: "#00aa00",
      warning: "#ff8800",
      controlBg: "#aaaaaa",
      controlBgHover: "#bbbbbb",
      controlBgActive: "#888888",
      controlBgPrimary: "#ff8800",
      controlTextPrimary: "#000000",
      shadowOutset: "inset 2px 2px 0 #ffffff, inset -2px -2px 0 #000000",
      shadowInset: "inset 2px 2px 0 #000000, inset -2px -2px 0 #ffffff",
      shadowWindow: "none",
      radius: "0px",
      fontSize: "13px",
      controlHeight: "24px",
      titlebarHeight: "20px",
      letterSpacing: "0.01em",
    },
  }),
  defineTheme({
    id: "nextstep",
    slug: "nextstep",
    name: "NeXTSTEP",
    year: 1989,
    era: "Desktop OS",
    description:
      "Dark chiseled slate, black title bars, dimensional buttons, and the original Unix workstation look.",
    tags: ["next", "greyscale", "unix"],
    engine: "nextstep",
    controls: "next",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "#555561",
      surface: "#aaaaaf",
      surfaceAlt: "#c8c8ce",
      text: "#000000",
      textMuted: "#333338",
      accent: "#000000",
      accentHover: "#222226",
      titlebarBg: "#000000",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#444448",
      titlebarInactiveText: "#bbbbbb",
      borderHigh: "#f0f0f4",
      borderLight: "#d0d0d4",
      borderDark: "#606068",
      borderLow: "#2c2c30",
      fieldBg: "#ffffff",
      selectionBg: "#000000",
      selectionText: "#ffffff",
      focus: "#000000",
      controlBg: "linear-gradient(#d8d8de, #9a9aa2)",
      controlBgHover: "linear-gradient(#e8e8ee, #aaaab0)",
      controlBgActive: "linear-gradient(#8a8a92, #c8c8ce)",
      controlBgPrimary: "linear-gradient(#888890, #2c2c30)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 1px 1px 0 #f0f0f4, inset -1px -1px 0 #2c2c30",
      shadowInset: "inset 1px 1px 0 #2c2c30, inset -1px -1px 0 #f0f0f4",
      shadowWindow: "3px 3px 0 rgba(0,0,0,0.45)",
      radius: "6px",
      radiusWindow: "8px",
      radiusControl: "6px",
      borderWidth: "1px",
      fontSize: "13px",
      controlHeight: "24px",
      titlebarHeight: "24px",
    },
  }),
  defineTheme({
    id: "beos",
    slug: "beos",
    name: "BeOS",
    year: 1996,
    era: "Desktop OS",
    description:
      "Yellow tabbed title bars, teal desktop, media-native widgets, and the Be box attitude.",
    tags: ["beos", "yellow", "tab"],
    engine: "beos",
    controls: "beos",
    desktopPattern: "none",
    fonts: {
      ui: `"Swis721 BT", "IBM Plex Sans", Tahoma, sans-serif`,
      mono: monoStack,
      display: `"IBM Plex Sans", Tahoma, sans-serif`,
    },
    tokens: {
      desktop: "#336868",
      surface: "#d8d8d8",
      surfaceAlt: "#ececec",
      text: "#202020",
      textMuted: "#555555",
      accent: "#ffcc00",
      accentHover: "#ffe066",
      titlebarBg: "linear-gradient(#ffe566, #e6b800)",
      titlebarText: "#202020",
      titlebarInactiveBg: "#c8c8c8",
      titlebarInactiveText: "#555555",
      borderHigh: "#ffffff",
      borderLight: "#eeeeee",
      borderDark: "#888888",
      borderLow: "#404040",
      fieldBg: "#ffffff",
      selectionBg: "#ffcc00",
      selectionText: "#202020",
      focus: "#ffcc00",
      controlBg: "linear-gradient(#f4f4f4, #c8c8c8)",
      controlBgHover: "linear-gradient(#ffffff, #d8d8d8)",
      controlBgActive: "#c0c0c0",
      controlBgPrimary: "linear-gradient(#ffe566, #e6b800)",
      controlTextPrimary: "#202020",
      shadowOutset: "inset 1px 1px 0 #ffffff, inset -1px -1px 0 #666666",
      shadowInset: "inset 1px 1px 2px rgba(0,0,0,0.2)",
      shadowWindow: "3px 3px 0 rgba(0,0,0,0.25)",
      radius: "3px",
      radiusWindow: "4px 12px 4px 4px",
      radiusControl: "3px",
      borderWidth: "1px",
      fontSize: "12px",
      controlHeight: "22px",
      titlebarHeight: "20px",
    },
  }),
  defineTheme({
    id: "os2-warp",
    slug: "os2-warp",
    name: "OS/2 Warp",
    year: 1994,
    era: "Desktop OS",
    description:
      "IBM Warp: teal Workplace Shell desktop, silver bevels, and the navy-to-cyan title fade.",
    tags: ["os2", "ibm", "bevel"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "tiles",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {
      desktop: "#2d7a7a",
      surface: "#c0c0c0",
      titlebarBg: "linear-gradient(to right, #00007f, #1084d0)",
      accent: "#00007f",
      selectionBg: "#00007f",
    },
  }),
  defineTheme({
    id: "cde-motif",
    slug: "cde-motif",
    name: "CDE / Motif",
    year: 1993,
    era: "Desktop OS",
    description:
      "Common Desktop Environment: dusty Motif bevels, teal selection, and workstation front-panel chrome.",
    tags: ["unix", "motif", "cde"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "#4a6b6b",
      surface: "#aeb2c3",
      surfaceAlt: "#c4c8d4",
      text: "#000000",
      accent: "#4a6b8a",
      titlebarBg: "#4a6b8a",
      titlebarInactiveBg: "#7a8494",
      controlBg: "#aeb2c3",
      controlBgHover: "#c4c8d4",
      controlBgPrimary: "#aeb2c3",
      selectionBg: "#4a6b8a",
      borderHigh: "#eceef4",
      borderLight: "#c4c8d4",
      borderDark: "#6a7080",
      borderLow: "#2a2e38",
      disabled: "#aeb2c3",
      shadowOutset:
        "inset -1px -1px #2a2e38, inset 1px 1px #eceef4, inset -2px -2px #6a7080, inset 2px 2px #c4c8d4",
      shadowInset:
        "inset -1px -1px #eceef4, inset 1px 1px #2a2e38, inset -2px -2px #c4c8d4, inset 2px 2px #6a7080",
    },
  }),
  defineTheme(
    {
      id: "templeos",
      slug: "templeos",
      name: "TempleOS",
      year: 2013,
      era: "Desktop OS",
      description:
        "16-color VGA God-kernel: royal blue desktop, bright primaries, and 8x8 bitmap type.",
      tags: ["templeos", "vga", "16-color"],
      engine: "pixel",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: vtStack, mono: vtStack, display: vtStack },
      tokens: {
        desktop: "#0000aa",
        surface: "#0000aa",
        surfaceAlt: "#0000ee",
        text: "#ffffff",
        textMuted: "#ffff55",
        textOnAccent: "#000000",
        accent: "#ffff00",
        accentHover: "#ffff88",
        titlebarBg: "#0000aa",
        titlebarText: "#ffff00",
        titlebarInactiveBg: "#000055",
        titlebarInactiveText: "#aaaaaa",
        borderHigh: "#ffffff",
        borderLight: "#55ffff",
        borderDark: "#000055",
        borderLow: "#ffffff",
        fieldBg: "#000088",
        fieldText: "#ffffff",
        selectionBg: "#ffff00",
        selectionText: "#0000aa",
        focus: "#ffff00",
        danger: "#ff0000",
        success: "#00ff00",
        warning: "#ffaa00",
        disabled: "#000088",
        disabledText: "#aaaaaa",
        controlBg: "#0000aa",
        controlBgHover: "#0000cc",
        controlBgActive: "#000088",
        controlBgPrimary: "#ffff00",
        controlTextPrimary: "#0000aa",
        shadowOutset: "none",
        shadowInset: "none",
        shadowWindow: "none",
        fontSize: "18px",
        controlHeight: "28px",
        titlebarHeight: "24px",
        letterSpacing: "0.02em",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "classic-gnome",
      slug: "classic-gnome",
      name: "Classic GNOME",
      year: 2002,
      era: "Desktop OS",
    taskbarPosition: "top",
      description:
        "GNOME 2 desktop: soft gray Clearlooks panels, Tango blue selections, and a calm sky gradient.",
      tags: ["gnome", "linux", "gtk", "clearlooks"],
      engine: "bevel",
      controls: "win",
      desktopPattern: "horizon",
      fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
      tokens: {
        desktop: "#729fcf",
        surface: "#eceae6",
        surfaceAlt: "#e0ddd8",
        text: "#2e3436",
        textMuted: "#6a737b",
        accent: "#3465a4",
        accentHover: "#4a7ec2",
        titlebarBg: "linear-gradient(#f6f5f3, #d6d3ce)",
        titlebarText: "#34465e",
        titlebarInactiveBg: "#e0ddd8",
        titlebarInactiveText: "#8a9199",
        borderHigh: "#ffffff",
        borderLight: "#f6f5f3",
        borderDark: "#a8a5a0",
        borderLow: "#787572",
        fieldBg: "#ffffff",
        fieldText: "#2e3436",
        selectionBg: "#3465a4",
        selectionText: "#ffffff",
        focus: "#3465a4",
        danger: "#cc0000",
        success: "#4e9a06",
        warning: "#c4a000",
        disabled: "#e0ddd8",
        disabledText: "#8a9199",
        controlBg: "linear-gradient(#fdfdfc, #e2e0dc)",
        controlBgHover: "linear-gradient(#ffffff, #eceae6)",
        controlBgActive: "#d6d3ce",
        controlBgPrimary: "linear-gradient(#7ba3d4, #3465a4)",
        controlTextPrimary: "#ffffff",
        shadowOutset: "inset -1px -1px #a8a5a0, inset 1px 1px #ffffff",
        shadowInset: "inset 0 1px 3px rgba(0, 0, 0, 0.12)",
        shadowWindow: "0 4px 14px rgba(0, 0, 0, 0.25)",
        radius: "4px",
        radiusWindow: "6px",
        radiusControl: "4px",
        borderWidth: "1px",
        fontSize: "13px",
        controlHeight: "26px",
        titlebarHeight: "24px",
        letterSpacing: "0",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "kde-3",
      slug: "kde-3",
      name: "KDE 3",
      year: 2002,
      era: "Desktop OS",
      description:
        "Keramik desktop: brushed blue gradients, a K-menu panel, Crystal icon shine, and Konqi blue.",
      tags: ["kde", "linux", "qt", "keramik"],
      engine: "bevel",
      controls: "win",
      desktopPattern: "none",
      fonts: { ui: plexSans, mono: monoStack, display: plexSans },
      tokens: {
        desktop: "#24568a",
        surface: "#d6d2ca",
        surfaceAlt: "#e4e1da",
        text: "#101010",
        textMuted: "#5a5f66",
        accent: "#1d5aa8",
        accentHover: "#2a6ec4",
        titlebarBg: "linear-gradient(#7a9cc4, #3a6a9e)",
        titlebarText: "#ffffff",
        titlebarInactiveBg: "#b8bcc2",
        titlebarInactiveText: "#5a5f66",
        borderHigh: "#ffffff",
        borderLight: "#e8e6e2",
        borderDark: "#8a8f96",
        borderLow: "#5a5f66",
        fieldBg: "#ffffff",
        fieldText: "#101010",
        selectionBg: "#1d5aa8",
        selectionText: "#ffffff",
        focus: "#ff8c00",
        danger: "#d0342c",
        success: "#2e8b3a",
        warning: "#f39c25",
        disabled: "#c8c4bc",
        disabledText: "#8a8f96",
        controlBg: "linear-gradient(#f4f2ee, #c8c4bc)",
        controlBgHover: "linear-gradient(#ffffff, #d8d4cc)",
        controlBgActive: "#b0aca4",
        controlBgPrimary: "linear-gradient(#5a9ae0, #1d5aa8)",
        controlTextPrimary: "#ffffff",
        shadowOutset: "inset -1px -1px #8a8f96, inset 1px 1px #ffffff",
        shadowInset: "inset 0 1px 3px rgba(0, 0, 0, 0.2)",
        shadowWindow: "0 6px 16px rgba(0, 0, 0, 0.4)",
        radius: "4px",
        radiusWindow: "6px",
        radiusControl: "4px",
        borderWidth: "1px",
        fontSize: "13px",
        lineHeight: "1.4",
        controlHeight: "26px",
        titlebarHeight: "24px",
        space: "8px",
        letterSpacing: "0",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "xfce-4",
      slug: "xfce-4",
      name: "XFCE 4",
      year: 2003,
      era: "Desktop OS",
      description:
        "Lightweight GTK desktop: quiet gray panels, a slim taskbar, and the mouse-blue accent.",
      tags: ["xfce", "linux", "gtk", "lightweight"],
      engine: "bevel",
      controls: "win",
      desktopPattern: "none",
      fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
      tokens: {
        desktop: "#3f4e5c",
        surface: "#e8e6e1",
        surfaceAlt: "#dcd8d2",
        text: "#2e3436",
        textMuted: "#6a737b",
        accent: "#3d6fb0",
        accentHover: "#4d82c6",
        titlebarBg: "linear-gradient(#eef0f2, #c8ccd2)",
        titlebarText: "#2e3436",
        titlebarInactiveBg: "#dcd8d2",
        titlebarInactiveText: "#8a9199",
        borderHigh: "#ffffff",
        borderLight: "#f6f5f3",
        borderDark: "#a8a5a0",
        borderLow: "#787572",
        fieldBg: "#ffffff",
        fieldText: "#2e3436",
        selectionBg: "#3d6fb0",
        selectionText: "#ffffff",
        focus: "#3d6fb0",
        danger: "#cc0000",
        success: "#4e9a06",
        warning: "#c4a000",
        disabled: "#e0ddd8",
        disabledText: "#8a9199",
        controlBg: "linear-gradient(#fdfdfd, #e2e0dc)",
        controlBgHover: "linear-gradient(#ffffff, #eceae6)",
        controlBgActive: "#d6d3ce",
        controlBgPrimary: "linear-gradient(#6a9ad4, #3d6fb0)",
        controlTextPrimary: "#ffffff",
        shadowOutset: "inset -1px -1px #a8a5a0, inset 1px 1px #ffffff",
        shadowInset: "inset 0 1px 2px rgba(0, 0, 0, 0.1)",
        shadowWindow: "0 4px 12px rgba(0, 0, 0, 0.25)",
        radius: "3px",
        radiusWindow: "4px",
        radiusControl: "3px",
        borderWidth: "1px",
        fontSize: "13px",
        lineHeight: "1.4",
        controlHeight: "25px",
        titlebarHeight: "23px",
        space: "8px",
        letterSpacing: "0",
      },
    },
    bevelWin95,
  ),
  defineTheme({
    id: "unix-x11",
    slug: "unix-x11",
    name: "Unix / X11",
    year: 1991,
    era: "Desktop OS",
    description:
      "Bare X11 and twm: stippled black root, hairline white frames, xterm mono, zero ornament.",
    tags: ["unix", "x11", "twm", "xterm", "monochrome"],
    engine: "terminal",
    controls: "none",
    desktopPattern: "dots",
    fonts: { ui: monoStack, mono: monoStack, display: monoStack },
    tokens: {
      desktop: "#000000",
      surface: "#000000",
      surfaceAlt: "#101010",
      text: "#ffffff",
      textMuted: "#8a8a8a",
      textOnAccent: "#ffffff",
      accent: "#ffffff",
      accentHover: "#c8c8c8",
      titlebarBg: "#ffffff",
      titlebarText: "#000000",
      titlebarInactiveBg: "#5a5a5a",
      titlebarInactiveText: "#000000",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#8a8a8a",
      borderLow: "#ffffff",
      fieldBg: "#000000",
      fieldText: "#ffffff",
      selectionBg: "#ffffff",
      selectionText: "#000000",
      focus: "#ffffff",
      danger: "#c8c8c8",
      success: "#8a8a8a",
      warning: "#c8c8c8",
      disabled: "#101010",
      disabledText: "#5a5a5a",
      controlBg: "#000000",
      controlBgHover: "#101010",
      controlBgActive: "#000000",
      controlBgPrimary: "#ffffff",
      controlTextPrimary: "#000000",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "none",
      radius: "0px",
      radiusWindow: "0px",
      radiusControl: "0px",
      borderWidth: "1px",
      fontSize: "14px",
      lineHeight: "1.35",
      controlHeight: "26px",
      titlebarHeight: "22px",
      space: "8px",
      letterSpacing: "0.04em",
    },
  }),
  defineTheme({
    id: "liquid-glass",
    slug: "liquid-glass",
    name: "Liquid Glass",
    year: 2026,
    era: "Desktop OS",
    description:
      "iOS 27, iPadOS 27, and macOS 27: frosted translucent materials, capsule controls, specular edges, and soft depth.",
    tags: ["apple", "ios-27", "ipados-27", "macos-27", "modern"],
    engine: "glass",
    controls: "mac",
    desktopPattern: "none",
    taskbarPosition: "top",
    fonts: {
      ui: "-apple-system, BlinkMacSystemFont, 'Helvetica Neue', Arial, sans-serif",
      mono: "ui-monospace, 'SF Mono', Menlo, monospace",
      display: "-apple-system, BlinkMacSystemFont, 'Helvetica Neue', Arial, sans-serif",
    },
    tokens: {
      desktop: "linear-gradient(160deg, #9ec3ff 0%, #d5c8ff 45%, #ffd5e4 100%)",
      surface: "rgba(255, 255, 255, 0.55)",
      surfaceAlt: "rgba(255, 255, 255, 0.35)",
      text: "#1a1c1e",
      textMuted: "rgba(60, 60, 67, 0.6)",
      textOnAccent: "#ffffff",
      accent: "#0a84ff",
      accentHover: "#409cff",
      titlebarBg: "transparent",
      titlebarText: "#1a1c1e",
      titlebarInactiveBg: "rgba(255, 255, 255, 0.25)",
      titlebarInactiveText: "rgba(60, 60, 67, 0.5)",
      titleLabelBg: "transparent",
      borderHigh: "rgba(255, 255, 255, 0.75)",
      borderLight: "rgba(255, 255, 255, 0.5)",
      borderDark: "rgba(120, 120, 128, 0.24)",
      borderLow: "rgba(120, 120, 128, 0.36)",
      fieldBg: "rgba(255, 255, 255, 0.72)",
      fieldText: "#1a1c1e",
      selectionBg: "#0a84ff",
      selectionText: "#ffffff",
      focus: "#0a84ff",
      danger: "#ff3b30",
      success: "#34c759",
      warning: "#ff9500",
      disabled: "rgba(255, 255, 255, 0.3)",
      disabledText: "rgba(60, 60, 67, 0.35)",
      controlBg: "rgba(255, 255, 255, 0.5)",
      controlBgHover: "rgba(255, 255, 255, 0.68)",
      controlBgActive: "rgba(255, 255, 255, 0.3)",
      controlBgPrimary: "#0a84ff",
      controlTextPrimary: "#ffffff",
      shadowOutset:
        "inset 0 1px 0 rgba(255, 255, 255, 0.85), 0 1px 3px rgba(0, 0, 0, 0.14)",
      shadowInset: "inset 0 1px 2px rgba(0, 0, 0, 0.08)",
      shadowWindow: "0 24px 56px rgba(0, 0, 0, 0.25), 0 0 0 0.5px rgba(0, 0, 0, 0.1)",
      radius: "12px",
      radiusWindow: "18px",
      radiusControl: "999px",
      borderWidth: "1px",
      fontSize: "14px",
      lineHeight: "1.45",
      controlHeight: "34px",
      titlebarHeight: "44px",
      space: "12px",
      letterSpacing: "-0.01em",
    },
  }),
  defineTheme({
    id: "macos-big-sur",
    slug: "macos-big-sur",
    name: "macOS Big Sur",
    year: 2020,
    era: "Desktop OS",
    description:
      "Big-radii frosted Mac: sunset wallpaper, light gray chrome, traffic lights, and rounded-rect controls.",
    tags: ["macos", "big-sur", "apple", "frost"],
    engine: "glass",
    controls: "mac",
    desktopPattern: "none",
    taskbarPosition: "top",
    fonts: {
      ui: "-apple-system, BlinkMacSystemFont, 'Helvetica Neue', Arial, sans-serif",
      mono: "ui-monospace, 'SF Mono', Menlo, monospace",
      display: "-apple-system, BlinkMacSystemFont, 'Helvetica Neue', Arial, sans-serif",
    },
    tokens: {
      desktop: "linear-gradient(180deg, #0f1f4a 0%, #3a5fa8 35%, #e8935a 72%, #f7c59f 100%)",
      surface: "rgba(246, 246, 248, 0.72)",
      surfaceAlt: "rgba(238, 238, 242, 0.6)",
      text: "#1d1d1f",
      textMuted: "rgba(60, 60, 67, 0.6)",
      textOnAccent: "#ffffff",
      accent: "#0a84ff",
      accentHover: "#3f9bff",
      titlebarBg: "rgba(246, 246, 248, 0.65)",
      titlebarText: "#1d1d1f",
      titlebarInactiveBg: "rgba(240, 240, 244, 0.5)",
      titlebarInactiveText: "rgba(60, 60, 67, 0.5)",
      titleLabelBg: "transparent",
      borderHigh: "rgba(255, 255, 255, 0.7)",
      borderLight: "rgba(255, 255, 255, 0.45)",
      borderDark: "rgba(120, 120, 128, 0.22)",
      borderLow: "rgba(120, 120, 128, 0.34)",
      fieldBg: "rgba(255, 255, 255, 0.85)",
      fieldText: "#1d1d1f",
      selectionBg: "#0a84ff",
      selectionText: "#ffffff",
      focus: "#0a84ff",
      danger: "#ff3b30",
      success: "#34c759",
      warning: "#ff9500",
      disabled: "rgba(230, 230, 235, 0.6)",
      disabledText: "rgba(60, 60, 67, 0.35)",
      controlBg: "rgba(255, 255, 255, 0.65)",
      controlBgHover: "rgba(255, 255, 255, 0.85)",
      controlBgActive: "rgba(240, 240, 244, 0.7)",
      controlBgPrimary: "#0a84ff",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 rgba(255, 255, 255, 0.7), 0 1px 2px rgba(0, 0, 0, 0.1)",
      shadowInset: "inset 0 1px 2px rgba(0, 0, 0, 0.07)",
      shadowWindow: "0 22px 60px rgba(0, 0, 0, 0.3), 0 0 0 0.5px rgba(0, 0, 0, 0.12)",
      radius: "8px",
      radiusWindow: "12px",
      radiusControl: "8px",
      borderWidth: "1px",
      fontSize: "13px",
      lineHeight: "1.45",
      controlHeight: "30px",
      titlebarHeight: "40px",
      space: "12px",
      letterSpacing: "-0.005em",
    },
  }),
  defineTheme(
    {
      id: "amigaos-4",
      slug: "amigaos-4",
      name: "AmigaOS 4",
      year: 2004,
      era: "Desktop OS",
      description:
        "PowerPC Workbench: cool gray 3D bevels, Reaction gadgets, steel gradients, and Workbench blue.",
      tags: ["amiga", "amigaos", "ppc", "reaction"],
      engine: "bevel",
      controls: "win",
      desktopPattern: "none",
      fonts: { ui: tahomaStack, mono: monoStack, display: plexSans },
      tokens: {
        desktop: "#8a97a3",
        surface: "#c8c4bc",
        surfaceAlt: "#d8d4cc",
        text: "#16181c",
        textMuted: "#4a5058",
        textOnAccent: "#ffffff",
        accent: "#2a5aa8",
        accentHover: "#3a6ec4",
        titlebarBg: "linear-gradient(#dfe3e8, #aab2bc)",
        titlebarText: "#16181c",
        titlebarInactiveBg: "#b0b4bc",
        titlebarInactiveText: "#5a6068",
        titleLabelBg: "transparent",
        borderHigh: "#eef0f2",
        borderLight: "#d8dade",
        borderDark: "#8a8f96",
        borderLow: "#5a5f66",
        fieldBg: "#ffffff",
        fieldText: "#16181c",
        selectionBg: "#2a5aa8",
        selectionText: "#ffffff",
        focus: "#2a5aa8",
        danger: "#a3281c",
        success: "#2e7a3a",
        warning: "#b08a20",
        disabled: "#b8b4ac",
        disabledText: "#7a7e86",
        controlBg: "linear-gradient(#e8eaee, #c0c4cc)",
        controlBgHover: "linear-gradient(#f2f4f6, #ced2da)",
        controlBgActive: "#a8acb4",
        controlBgPrimary: "linear-gradient(#4a7ac8, #1e4a90)",
        controlTextPrimary: "#ffffff",
        shadowOutset:
          "inset -1px -1px #5a5f66, inset 1px 1px #ffffff, inset -2px -2px #8a8f96, inset 2px 2px #e8eaee",
        shadowInset:
          "inset 1px 1px #5a5f66, inset -1px -1px #ffffff, inset 2px 2px #8a8f96, inset -2px -2px #e8eaee",
        shadowWindow: "3px 3px 0 rgba(0, 0, 0, 0.35)",
        radius: "2px",
        radiusWindow: "3px",
        radiusControl: "2px",
        borderWidth: "1px",
        fontSize: "12px",
        lineHeight: "1.35",
        controlHeight: "25px",
        titlebarHeight: "24px",
        space: "8px",
        letterSpacing: "0",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "kde-plasma",
      slug: "kde-plasma",
      name: "KDE Plasma",
      year: 2014,
      era: "Desktop OS",
      description:
        "Breeze desktop: airy whites, quiet 1px borders, Breeze-blue accents, and crisp flat panels.",
      tags: ["kde", "plasma", "linux", "breeze"],
      engine: "bevel",
      controls: "win",
      desktopPattern: "none",
      fonts: { ui: "'Noto Sans', 'Segoe UI', sans-serif", mono: monoStack, display: "'Noto Sans', sans-serif" },
      tokens: {
        desktop: "linear-gradient(180deg, #294f6e, #16283a)",
        surface: "#eff0f1",
        surfaceAlt: "#fcfcfc",
        text: "#31363b",
        textMuted: "#7f8c8d",
        textOnAccent: "#ffffff",
        accent: "#3daee9",
        accentHover: "#61c1f0",
        titlebarBg: "#eff0f1",
        titlebarText: "#31363b",
        titlebarInactiveBg: "#e2e3e5",
        titlebarInactiveText: "#9aa0a6",
        titleLabelBg: "transparent",
        borderHigh: "#ffffff",
        borderLight: "#e8eaec",
        borderDark: "#c4c7cb",
        borderLow: "#b0b3b8",
        fieldBg: "#ffffff",
        fieldText: "#31363b",
        selectionBg: "#3daee9",
        selectionText: "#ffffff",
        focus: "#3daee9",
        danger: "#da4453",
        success: "#27ae60",
        warning: "#f67400",
        disabled: "#e6e7e9",
        disabledText: "#9aa0a6",
        controlBg: "#f7f7f8",
        controlBgHover: "#e9eaec",
        controlBgActive: "#dddee0",
        controlBgPrimary: "#3daee9",
        controlTextPrimary: "#ffffff",
        shadowOutset: "none",
        shadowInset: "inset 0 1px 2px rgba(0, 0, 0, 0.06)",
        shadowWindow: "0 8px 24px rgba(0, 0, 0, 0.2), 0 0 0 1px #c4c7cb",
        radius: "2px",
        radiusWindow: "3px",
        radiusControl: "2px",
        borderWidth: "1px",
        fontSize: "13px",
        lineHeight: "1.4",
        controlHeight: "28px",
        titlebarHeight: "30px",
        space: "10px",
        letterSpacing: "0",
      },
    },
    bevelWin95,
  ),
  defineTheme({
    id: "gnome-40",
    slug: "gnome-40",
    name: "GNOME 40",
    year: 2021,
    era: "Desktop OS",
    description:
      "Adwaita desktop: big-radii white windows, flat headerbar gray, Activities panel, and GNOME blue.",
    tags: ["gnome", "adwaita", "linux", "modern"],
    engine: "web",
    controls: "none",
    desktopPattern: "none",
    taskbarPosition: "top",
    fonts: {
      ui: "Cantarell, 'Noto Sans', sans-serif",
      mono: monoStack,
      display: "Cantarell, 'Noto Sans', sans-serif",
    },
    tokens: {
      desktop: "linear-gradient(160deg, #a6b8d8, #5f6f9a)",
      surface: "#ffffff",
      surfaceAlt: "#f6f5f4",
      text: "#2e3436",
      textMuted: "#77767b",
      textOnAccent: "#ffffff",
      accent: "#3584e4",
      accentHover: "#5b9df0",
      titlebarBg: "#ebebeb",
      titlebarText: "#2e3436",
      titlebarInactiveBg: "#f6f5f4",
      titlebarInactiveText: "#9a9996",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#deddda",
      borderDark: "#c0bfbc",
      borderLow: "#9a9996",
      fieldBg: "#ffffff",
      fieldText: "#2e3436",
      selectionBg: "#3584e4",
      selectionText: "#ffffff",
      focus: "#3584e4",
      danger: "#e01b24",
      success: "#2ec27e",
      warning: "#f5c211",
      disabled: "#f0eeec",
      disabledText: "#9a9996",
      controlBg: "#ffffff",
      controlBgHover: "#f2f2f1",
      controlBgActive: "#dcdcd9",
      controlBgPrimary: "#3584e4",
      controlTextPrimary: "#ffffff",
      shadowOutset: "0 1px 2px rgba(0, 0, 0, 0.1)",
      shadowInset: "inset 0 1px 2px rgba(0, 0, 0, 0.06)",
      shadowWindow: "0 12px 32px rgba(0, 0, 0, 0.22), 0 0 0 1px rgba(0, 0, 0, 0.06)",
      radius: "8px",
      radiusWindow: "12px",
      radiusControl: "8px",
      borderWidth: "1px",
      fontSize: "13px",
      lineHeight: "1.45",
      controlHeight: "32px",
      titlebarHeight: "40px",
      space: "12px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "windows-phone-metro",
    slug: "windows-phone-metro",
    name: "Windows Phone Metro",
    year: 2011,
    era: "Web/UI",
    description:
      "Metro tiles: black void, cyan accent blocks, light lowercase type, zero chrome and zero borders.",
    tags: ["windows-phone", "metro", "flat", "tiles"],
    engine: "web",
    controls: "none",
    desktopPattern: "none",
    fonts: {
      ui: "'Segoe UI', 'Noto Sans', sans-serif",
      mono: monoStack,
      display: "'Segoe UI Light', 'Segoe UI', 'Noto Sans', sans-serif",
    },
    tokens: {
      desktop: "#0a0a0a",
      surface: "#1f1f1f",
      surfaceAlt: "#2a2a2a",
      text: "#ffffff",
      textMuted: "#a0a0a0",
      textOnAccent: "#ffffff",
      accent: "#1ba1e2",
      accentHover: "#3cb4ef",
      titlebarBg: "#1ba1e2",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#2a2a2a",
      titlebarInactiveText: "#a0a0a0",
      titleLabelBg: "transparent",
      borderHigh: "#2a2a2a",
      borderLight: "#2a2a2a",
      borderDark: "#2a2a2a",
      borderLow: "#2a2a2a",
      fieldBg: "#1f1f1f",
      fieldText: "#ffffff",
      selectionBg: "#1ba1e2",
      selectionText: "#ffffff",
      focus: "#ffffff",
      danger: "#e51400",
      success: "#60a917",
      warning: "#f0a30a",
      disabled: "#1f1f1f",
      disabledText: "#6a6a6a",
      controlBg: "#2a2a2a",
      controlBgHover: "#383838",
      controlBgActive: "#161616",
      controlBgPrimary: "#1ba1e2",
      controlTextPrimary: "#ffffff",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "none",
      radius: "0px",
      radiusWindow: "0px",
      radiusControl: "0px",
      borderWidth: "0px",
      fontSize: "15px",
      lineHeight: "1.4",
      controlHeight: "34px",
      titlebarHeight: "40px",
      space: "12px",
      letterSpacing: "0.01em",
    },
  }),
];
