import {
  bevelWin95,
  defineTheme,
  displayStack,
  helveticaStack,
  monoStack,
  orbitronStack,
  pixelStack,
  plexSans,
  serifStack,
  tahomaStack,
  vtStack,
} from "./helpers";
import type { RetroTheme } from "./types";

export const gamingThemes: RetroTheme[] = [
  defineTheme(
    {
      id: "8bit-arcade",
      slug: "8bit-arcade",
      name: "8-Bit Arcade",
      year: 1983,
      era: "Gaming",
      description: "Cabinet HUD: chunky pixels, neon insert art, and high-score chrome.",
      tags: ["arcade", "pixel", "neon"],
      engine: "pixel",
      controls: "none",
      desktopPattern: "stars",
      fonts: { ui: pixelStack, mono: pixelStack, display: pixelStack },
      tokens: {
        desktop: "#0b0b1e",
        surface: "#16162e",
        surfaceAlt: "#221a3a",
        text: "#ffffff",
        textMuted: "#8a8ab8",
        accent: "#ff2d95",
        accentHover: "#ff6bb3",
        titlebarBg: "#ff2d95",
        titlebarText: "#ffffff",
        titlebarInactiveBg: "#221a3a",
        titlebarInactiveText: "#8a8ab8",
        borderHigh: "#00e5ff",
        borderLight: "#00e5ff",
        borderDark: "#7c1dfd",
        borderLow: "#ffd300",
        fieldBg: "#0b0b1e",
        fieldText: "#ffffff",
        selectionBg: "#7c1dfd",
        selectionText: "#ffffff",
        focus: "#ffd300",
        danger: "#ff3b3b",
        success: "#2bff88",
        warning: "#ffd300",
        disabled: "#16162e",
        disabledText: "#8a8ab8",
        controlBg: "#221a3a",
        controlBgHover: "#2e2450",
        controlBgActive: "#16162e",
        controlBgPrimary: "#ff2d95",
        controlTextPrimary: "#ffffff",
        shadowOutset: "4px 4px 0 #000000",
        shadowInset: "inset 0 0 0 2px #00e5ff",
        shadowWindow: "6px 6px 0 #000000",
        borderWidth: "3px",
        fontSize: "11px",
        controlHeight: "32px",
        titlebarHeight: "28px",
        letterSpacing: "0.04em",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "gameboy-dmg",
      slug: "gameboy-dmg",
      name: "Game Boy DMG",
      year: 1989,
      era: "Gaming",
      description: "Olive brick and four-shade olive LCD. 160×144 thinking, chunky 2px rules.",
      tags: ["gameboy", "lcd", "4-shade"],
      engine: "pixel",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: pixelStack, mono: pixelStack, display: pixelStack },
      tokens: {
        desktop: "#8a8478",
        surface: "#9bbc0f",
        surfaceAlt: "#8bac0f",
        text: "#0f380f",
        textMuted: "#306230",
        accent: "#0f380f",
        accentHover: "#306230",
        titlebarBg: "#306230",
        titlebarText: "#9bbc0f",
        titlebarInactiveBg: "#8bac0f",
        titlebarInactiveText: "#306230",
        borderHigh: "#0f380f",
        borderLight: "#0f380f",
        borderDark: "#0f380f",
        borderLow: "#0f380f",
        fieldBg: "#8bac0f",
        fieldText: "#0f380f",
        selectionBg: "#0f380f",
        selectionText: "#9bbc0f",
        focus: "#0f380f",
        danger: "#0f380f",
        success: "#306230",
        warning: "#306230",
        disabled: "#8bac0f",
        disabledText: "#306230",
        controlBg: "#8bac0f",
        controlBgHover: "#9bbc0f",
        controlBgActive: "#306230",
        controlBgPrimary: "#0f380f",
        controlTextPrimary: "#9bbc0f",
        shadowOutset: "3px 3px 0 #0f380f",
        shadowInset: "inset 2px 2px 0 #306230",
        shadowWindow: "4px 4px 0 #6a6458",
        borderWidth: "3px",
        fontSize: "11px",
        controlHeight: "28px",
        titlebarHeight: "24px",
        letterSpacing: "0.02em",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "ps1-tech",
      slug: "ps1-tech",
      name: "PS1 Tech",
      year: 1994,
      era: "Gaming",
      description: "Low-poly startup energy: dithered gradients, UI meshes, and boot-logo chrome.",
      tags: ["playstation", "low-poly", "tech"],
      engine: "graphic",
      controls: "none",
      desktopPattern: "perspective",
      fonts: { ui: orbitronStack, mono: monoStack, display: orbitronStack },
      tokens: {
        desktop: "#0a0a10",
        surface: "#181820",
        surfaceAlt: "#2a2a32",
        text: "#e8e8f0",
        textMuted: "#808088",
        accent: "#00ffff",
        accentHover: "#66ffff",
        titlebarBg: "linear-gradient(90deg, #2a2a32, #00ffff22)",
        titlebarText: "#00ffff",
        titlebarInactiveBg: "#181820",
        titlebarInactiveText: "#808088",
        borderHigh: "#c0c0c0",
        borderLight: "#606068",
        borderDark: "#2a2a32",
        borderLow: "#9d4edd",
        fieldBg: "#0a0a10",
        fieldText: "#e8e8f0",
        selectionBg: "#9d4edd",
        selectionText: "#ffffff",
        focus: "#00ffff",
        danger: "#ff3355",
        success: "#39ff14",
        warning: "#ffd300",
        disabled: "#181820",
        disabledText: "#606068",
        controlBg: "#2a2a32",
        controlBgHover: "#3a3a44",
        controlBgActive: "#181820",
        controlBgPrimary: "linear-gradient(90deg, #00ffff, #9d4edd)",
        controlTextPrimary: "#0a0a10",
        shadowOutset: "0 0 0 1px #00ffff",
        shadowInset: "inset 0 0 12px rgba(0,255,255,0.15)",
        shadowWindow: "0 0 24px rgba(157, 78, 221, 0.35)",
        radius: "2px",
        radiusWindow: "2px",
        radiusControl: "2px",
        borderWidth: "1px",
        fontSize: "12px",
        controlHeight: "26px",
        titlebarHeight: "26px",
        letterSpacing: "0.12em",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "winamp-skin",
      slug: "winamp-skin",
      name: "Winamp Skin",
      year: 1997,
      era: "App",
      description: "Classic media-player skin: brushed metal, LCD green, visor buttons, and EQ chrome.",
      tags: ["winamp", "media", "lcd"],
      engine: "graphic",
      controls: "win",
      desktopPattern: "none",
      fonts: { ui: plexSans, mono: vtStack, display: plexSans },
      tokens: {
        desktop: "#1a1a1a",
        surface: "#3c3c3c",
        surfaceAlt: "#5a5a5a",
        text: "#d0d0d0",
        textMuted: "#8a8a8a",
        accent: "#00ff33",
        accentHover: "#66ff77",
        titlebarBg: "linear-gradient(#5a5a5a, #2a2a2a)",
        titlebarText: "#ffffff",
        titlebarInactiveBg: "#2a2a2a",
        titlebarInactiveText: "#8a8a8a",
        borderHigh: "#8a8a8a",
        borderLight: "#5a5a5a",
        borderDark: "#1a1a1a",
        borderLow: "#000000",
        fieldBg: "#001a08",
        fieldText: "#00ff33",
        selectionBg: "#004d11",
        selectionText: "#00ff33",
        focus: "#ffb400",
        danger: "#ff4040",
        success: "#00ff33",
        warning: "#ffb400",
        disabled: "#3c3c3c",
        disabledText: "#6a6a6a",
        controlBg: "linear-gradient(#6a6a6a, #3c3c3c)",
        controlBgHover: "linear-gradient(#7a7a7a, #4a4a4a)",
        controlBgActive: "#2a2a2a",
        controlBgPrimary: "linear-gradient(#3a3a3a, #111111)",
        controlTextPrimary: "#00ff33",
        shadowOutset: "inset 1px 1px 0 #8a8a8a, inset -1px -1px 0 #000000",
        shadowInset: "inset 0 0 8px #001a08",
        shadowWindow: "0 8px 18px rgba(0,0,0,0.55)",
        radius: "2px",
        radiusWindow: "3px",
        radiusControl: "2px",
        borderWidth: "1px",
        fontSize: "11px",
        controlHeight: "20px",
        titlebarHeight: "14px",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "red-alert",
      slug: "red-alert",
      name: "Red Alert",
      year: 1996,
      era: "Gaming",
      description:
        "Westwood command console: battle-worn steel panels, crimson alert banners, gold readouts, red-star buttons.",
      tags: ["command-conquer", "westwood", "rts", "military"],
      engine: "bevel",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: tahomaStack, mono: monoStack, display: displayStack },
      tokens: {
        desktop: "#0a0e14",
        surface: "#6e747c",
        surfaceAlt: "#7e848c",
        text: "#e8e4d8",
        textMuted: "#9aa0a8",
        textOnAccent: "#ffffff",
        accent: "#c81616",
        accentHover: "#e02a22",
        titlebarBg: "linear-gradient(#96302a, #6a1210)",
        titlebarText: "#ffdf8a",
        titlebarInactiveBg: "#4a5058",
        titlebarInactiveText: "#9aa0a8",
        titleLabelBg: "transparent",
        borderHigh: "#c8ccd2",
        borderLight: "#a8adb4",
        borderDark: "#3a3f46",
        borderLow: "#14181c",
        fieldBg: "#10161c",
        fieldText: "#d8d4c8",
        selectionBg: "#c81616",
        selectionText: "#ffffff",
        focus: "#ffd23c",
        danger: "#e03428",
        success: "#7ec850",
        warning: "#ffd23c",
        disabled: "#565c64",
        disabledText: "#9aa0a8",
        controlBg: "linear-gradient(#5a616a, #3e444c)",
        controlBgHover: "linear-gradient(#6a717a, #4a5058)",
        controlBgActive: "#2e343c",
        controlBgPrimary: "linear-gradient(#e03428, #8a120c)",
        controlTextPrimary: "#ffffff",
        shadowOutset:
          "inset -1px -1px #14181c, inset 1px 1px #b8bec6, inset -2px -2px #3a3f46, inset 2px 2px #7e848c",
        shadowInset:
          "inset 1px 1px #14181c, inset -1px -1px #b8bec6, inset 2px 2px #3a3f46, inset -2px -2px #7e848c",
        shadowWindow: "0 0 0 1px #14181c, 4px 4px 0 rgba(0, 0, 0, 0.55)",
        fontSize: "12px",
        controlHeight: "26px",
        titlebarHeight: "24px",
        letterSpacing: "0.03em",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "warcraft-2",
      slug: "warcraft-2",
      name: "Warcraft II",
      year: 1995,
      era: "Gaming",
      description:
        "Medieval command panel: carved stone bevels, gold trim, and parchment fields over dark oak.",
      tags: ["warcraft", "fantasy", "blizzard", "rts"],
      engine: "bevel",
      controls: "none",
      desktopPattern: "weave",
      fonts: { ui: serifStack, mono: monoStack, display: serifStack },
      tokens: {
        desktop: "#14100a",
        surface: "#5c4d3b",
        surfaceAlt: "#6f5f4a",
        text: "#f0e2c4",
        textMuted: "#b3a184",
        accent: "#d4a017",
        accentHover: "#f0be30",
        titlebarBg: "#241a10",
        titlebarText: "#e9c46a",
        titlebarInactiveBg: "#3a2f22",
        titlebarInactiveText: "#8a7a5e",
        borderHigh: "#a08a63",
        borderLight: "#7a6038",
        borderDark: "#241a10",
        borderLow: "#0b0705",
        fieldBg: "#ecdbb0",
        fieldText: "#2a1f10",
        selectionBg: "#d4a017",
        selectionText: "#241a10",
        focus: "#f0be30",
        danger: "#a33327",
        success: "#5a7d4a",
        warning: "#d4a017",
        disabled: "#4a3f30",
        disabledText: "#8a7a5e",
        controlBg: "linear-gradient(#7a6750, #5c4d3b)",
        controlBgHover: "linear-gradient(#8a775e, #6a5a46)",
        controlBgActive: "#443726",
        controlBgPrimary: "linear-gradient(#f0be30, #b8860b)",
        controlTextPrimary: "#241a10",
        shadowOutset:
          "inset -1px -1px #0b0705, inset 1px 1px #a08a63, inset -2px -2px #241a10, inset 2px 2px #6f5f4a",
        shadowInset:
          "inset 1px 1px #0b0705, inset -1px -1px #a08a63, inset 2px 2px #241a10, inset -2px -2px #6f5f4a",
        shadowWindow: "4px 4px 0 rgba(0, 0, 0, 0.6)",
        fontSize: "13px",
        controlHeight: "28px",
        titlebarHeight: "28px",
        letterSpacing: "0.02em",
      },
    },
    bevelWin95,
  ),

  defineTheme(
    {
      id: "pip-boy",
      slug: "pip-boy",
      name: "Pip-Boy 3000",
      year: 2008,
      era: "Gaming",
      description:
        "Vault-Tec wrist computer: monochrome green CRT, chunky instrument bezels, amber alerts, scanlines.",
      tags: ["fallout", "vault-tec", "wasteland", "instrument"],
      engine: "terminal",
      controls: "none",
      desktopPattern: "scanlines",
      fonts: { ui: "Share Tech Mono, 'IBM Plex Mono', monospace", mono: "Share Tech Mono, monospace", display: "Share Tech Mono, monospace" },
      tokens: {
        desktop: "#041207",
        surface: "#06180a",
        surfaceAlt: "#0a2410",
        text: "#41ff5a",
        textMuted: "#1d8a2e",
        textOnAccent: "#06180a",
        accent: "#2aff4f",
        accentHover: "#6aff8a",
        titlebarBg: "#0c3a14",
        titlebarText: "#41ff5a",
        titlebarInactiveBg: "#082a0e",
        titlebarInactiveText: "#1d8a2e",
        borderHigh: "#2aff4f",
        borderLight: "#1d8a2e",
        borderDark: "#0a2410",
        borderLow: "#2aff4f",
        fieldBg: "#021006",
        fieldText: "#41ff5a",
        selectionBg: "#1d7a2a",
        selectionText: "#c8ffd0",
        focus: "#ffc40d",
        danger: "#ff5a3c",
        success: "#2aff4f",
        warning: "#ffc40d",
        disabled: "#0a2410",
        disabledText: "#1d5a24",
        controlBg: "#123a18",
        controlBgHover: "#1a4a20",
        controlBgActive: "#0a2a10",
        controlBgPrimary: "#2aff4f",
        controlTextPrimary: "#06180a",
        shadowOutset: "inset 0 0 0 2px #1d8a2e",
        shadowInset: "inset 0 0 12px rgba(42, 255, 79, 0.25)",
        shadowWindow: "0 0 24px rgba(42, 255, 79, 0.25)",
        fontSize: "15px",
        controlHeight: "28px",
        titlebarHeight: "28px",
        letterSpacing: "0.08em",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "doom-hud",
      slug: "doom-hud",
      name: "DOOM HUD",
      year: 1993,
      era: "Gaming",
      description:
        "E1M1 status bar: brown metal panels, amber readouts, red health, and the face that watches you.",
      tags: ["doom", "id", "fps", "hud"],
      engine: "pixel",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: pixelStack, mono: pixelStack, display: pixelStack },
      tokens: {
        desktop: "#1a0f0a",
        surface: "#3a2a20",
        surfaceAlt: "#4a3628",
        text: "#ffcc66",
        textMuted: "#8a6a4a",
        textOnAccent: "#ffffff",
        accent: "#e03c28",
        accentHover: "#ff5a3c",
        titlebarBg: "#4a3020",
        titlebarText: "#ffcc66",
        titlebarInactiveBg: "#33241a",
        titlebarInactiveText: "#8a6a4a",
        borderHigh: "#8a6a4a",
        borderLight: "#5f4936",
        borderDark: "#1c120c",
        borderLow: "#000000",
        fieldBg: "#120a06",
        fieldText: "#ffcc66",
        selectionBg: "#8a2a1a",
        selectionText: "#ffcc66",
        focus: "#ffcc33",
        danger: "#e03c28",
        success: "#3ac06a",
        warning: "#ffcc33",
        disabled: "#2a1e16",
        disabledText: "#6a5240",
        controlBg: "#5a4432",
        controlBgHover: "#6a5240",
        controlBgActive: "#3a2a20",
        controlBgPrimary: "#a02818",
        controlTextPrimary: "#ffffff",
        shadowOutset: "3px 3px 0 #000000",
        shadowInset: "inset 2px 2px 0 #1c120c",
        shadowWindow: "4px 4px 0 #000000",
        borderWidth: "2px",
        fontSize: "11px",
        controlHeight: "30px",
        titlebarHeight: "26px",
        letterSpacing: "0.04em",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "scumm",
      slug: "scumm",
      name: "SCUMM Adventures",
      year: 1990,
      era: "Gaming",
      description:
        "LucasArts verb engine: dark VGA dialogs, cyan hotspots, and the orange sentence line under everything.",
      tags: ["lucasarts", "point-and-click", "scumm", "vga"],
      engine: "bevel",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: pixelStack, mono: pixelStack, display: pixelStack },
      tokens: {
        desktop: "#101010",
        surface: "#5a5a66",
        surfaceAlt: "#6a6a76",
        text: "#ffffff",
        textMuted: "#a8a8b4",
        textOnAccent: "#000000",
        accent: "#ff9c4a",
        accentHover: "#ffb878",
        titlebarBg: "#3a3a44",
        titlebarText: "#ffffff",
        titlebarInactiveBg: "#2a2a34",
        titlebarInactiveText: "#8a8a96",
        borderHigh: "#8a8a96",
        borderLight: "#6a6a76",
        borderDark: "#1a1a22",
        borderLow: "#000000",
        fieldBg: "#1a1a22",
        fieldText: "#ffffff",
        selectionBg: "#6ab0c8",
        selectionText: "#000000",
        focus: "#ff9c4a",
        danger: "#c85a4a",
        success: "#6ac87a",
        warning: "#ff9c4a",
        disabled: "#4a4a54",
        disabledText: "#8a8a96",
        controlBg: "#5a5a66",
        controlBgHover: "#6a6a76",
        controlBgActive: "#3a3a44",
        controlBgPrimary: "#ff9c4a",
        controlTextPrimary: "#000000",
        shadowOutset: "inset 0 0 0 1px #1a1a22",
        shadowInset: "none",
        shadowWindow: "3px 3px 0 #000000",
        fontSize: "12px",
        controlHeight: "26px",
        titlebarHeight: "26px",
        letterSpacing: "0.02em",
      },
    },
    bevelWin95,
  ),

  defineTheme({
    id: "persona-5",
    slug: "persona-5",
    name: "Persona 5",
    year: 2016,
    era: "Gaming",
    description:
      "Take your heart: jagged red-on-black collage, hard offset shadows, skewed type, and UI that fights back with style.",
    tags: ["atlus", "jrpg", "red", "collage", "typography"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "linear-gradient(120deg, #d92c2c 0%, #b51c22 40%, #0d0b0c 41%, #0d0b0c 100%)",
      surface: "#141218",
      surfaceAlt: "#1e1a22",
      text: "#f4f2ee",
      textMuted: "#9a938c",
      textOnAccent: "#ffffff",
      accent: "#e02020",
      accentHover: "#f04040",
      titlebarBg: "#d81f26",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#1a171c",
      titlebarInactiveText: "#8a837c",
      titleLabelBg: "transparent",
      borderHigh: "#f4f2ee",
      borderLight: "#3a343e",
      borderDark: "#0d0b0c",
      borderLow: "#000000",
      fieldBg: "#1a171c",
      fieldText: "#f4f2ee",
      selectionBg: "#e02020",
      selectionText: "#ffffff",
      focus: "#e02020",
      danger: "#e02020",
      success: "#3f9a5c",
      warning: "#f0c040",
      disabled: "#1a171c",
      disabledText: "#6a646c",
      controlBg: "#1c1a20",
      controlBgHover: "#2a262e",
      controlBgActive: "#332e38",
      controlBgPrimary: "#e02020",
      controlTextPrimary: "#ffffff",
      shadowOutset: "3px 3px 0 #e02020",
      shadowInset: "inset 2px 2px 0 #e02020",
      shadowWindow: "6px 6px 0 #d81f26",
      radius: "0px",
      radiusWindow: "0px",
      radiusControl: "0px",
      borderWidth: "1px",
      fontSize: "13px",
      lineHeight: "1.35",
      controlHeight: "32px",
      titlebarHeight: "30px",
      space: "10px",
      letterSpacing: "0.04em",
    },
  }),
  defineTheme({
    id: "diablo-2",
    slug: "diablo-2",
    name: "Diablo II",
    year: 2000,
    era: "Gaming",
    description:
      "Sanctuary's inventory: carved stone panels, gold filigree borders, parchment text, and blood-red orbs behind everything.",
    tags: ["blizzard", "arpg", "gothic", "parchment", "dark-fantasy"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: serifStack },
    tokens: {
      desktop: "linear-gradient(180deg, #141210, #060505)",
      surface: "#2a251d",
      surfaceAlt: "#332d24",
      text: "#d8c9a3",
      textMuted: "#8a7d5f",
      textOnAccent: "#f0e2b8",
      accent: "#8f1a12",
      accentHover: "#b02818",
      titlebarBg: "linear-gradient(#4a3d28, #241d12)",
      titlebarText: "#c8a860",
      titlebarInactiveBg: "#332d22",
      titlebarInactiveText: "#7a6c4c",
      titleLabelBg: "transparent",
      borderHigh: "#c8a860",
      borderLight: "#5f4d2f",
      borderDark: "#241d12",
      borderLow: "#100c08",
      fieldBg: "#1a160f",
      fieldText: "#e8d9b0",
      selectionBg: "#5f4718",
      selectionText: "#f0e2b8",
      focus: "#c8a860",
      danger: "#8f1a12",
      success: "#4a6a3a",
      warning: "#b8912f",
      disabled: "#2a251d",
      disabledText: "#6a5f45",
      controlBg: "linear-gradient(#3d342a, #241e16)",
      controlBgHover: "linear-gradient(#4a3f32, #2a231a)",
      controlBgActive: "#241e16",
      controlBgPrimary: "linear-gradient(#8f1a12, #5f0f0a)",
      controlTextPrimary: "#f0e2b8",
      shadowOutset: "inset 0 0 0 1px #5f4d2f, 0 2px 4px rgba(0, 0, 0, 0.6)",
      shadowInset: "inset 0 2px 4px rgba(0, 0, 0, 0.6)",
      shadowWindow: "0 6px 18px rgba(0, 0, 0, 0.7)",
      radius: "2px",
      radiusWindow: "3px",
      radiusControl: "2px",
      borderWidth: "2px",
      fontSize: "13px",
      lineHeight: "1.35",
      controlHeight: "30px",
      titlebarHeight: "28px",
      space: "10px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "ff-ps1",
    slug: "ff-ps1",
    name: "Final Fantasy PS1",
    year: 1997,
    era: "Gaming",
    description:
      "The blue menu window: gradient steel-blue panes with rounded light frames, white type, and a gold pointer hand you can still hear.",
    tags: ["square", "jrpg", "ps1", "blue-gradient", "menu"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "#0d1440",
      surface: "linear-gradient(180deg, #2a4394, #101d54)",
      surfaceAlt: "#1a2a6a",
      text: "#f4f6ff",
      textMuted: "#9fb0e0",
      textOnAccent: "#ffffff",
      accent: "#f8e878",
      accentHover: "#fdf4a8",
      titlebarBg: "linear-gradient(#3a56b0, #16246a)",
      titlebarText: "#f4f6ff",
      titlebarInactiveBg: "#1a2a5a",
      titlebarInactiveText: "#8a9ac8",
      titleLabelBg: "transparent",
      borderHigh: "#c8d8f8",
      borderLight: "#a8c0f0",
      borderDark: "#1a2a6a",
      borderLow: "#101a4a",
      fieldBg: "#101d54",
      fieldText: "#f4f6ff",
      selectionBg: "#4a68c0",
      selectionText: "#ffffff",
      focus: "#f8e878",
      danger: "#d04a3a",
      success: "#4aa85a",
      warning: "#f8e878",
      disabled: "#1a2a5a",
      disabledText: "#6a7ab0",
      controlBg: "linear-gradient(#3854a8, #1a2a6a)",
      controlBgHover: "linear-gradient(#4462b8, #22347a)",
      controlBgActive: "#1a2a6a",
      controlBgPrimary: "linear-gradient(#5a7ad0, #2a46a0)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 0 0 1px #a8c0f0",
      shadowInset: "inset 0 2px 4px rgba(6, 12, 44, 0.6)",
      shadowWindow: "0 4px 12px rgba(0, 0, 0, 0.5)",
      radius: "8px",
      radiusWindow: "8px",
      radiusControl: "8px",
      borderWidth: "2px",
      fontSize: "13px",
      lineHeight: "1.4",
      controlHeight: "30px",
      titlebarHeight: "28px",
      space: "10px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "portal-aperture",
    slug: "portal-aperture",
    name: "Portal / Aperture",
    year: 2007,
    era: "Gaming",
    description:
      "Clean test-chamber signage: white lab panels, charcoal type, safety-orange primaries, and a blue glow from somewhere it shouldn't be.",
    tags: ["valve", "portal", "aperture", "laboratory", "industrial"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "linear-gradient(180deg, #f4f6f8, #dfe4e8)",
      surface: "#ffffff",
      surfaceAlt: "#eef1f3",
      text: "#2e3338",
      textMuted: "#8a9298",
      textOnAccent: "#ffffff",
      accent: "#ff7a18",
      accentHover: "#ff9440",
      titlebarBg: "#f7f8fa",
      titlebarText: "#2e3338",
      titlebarInactiveBg: "#eef1f3",
      titlebarInactiveText: "#8a9298",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#e4e8eb",
      borderDark: "#c8cdd2",
      borderLow: "#a8b0b6",
      fieldBg: "#ffffff",
      fieldText: "#2e3338",
      selectionBg: "#e8ebee",
      selectionText: "#2e3338",
      focus: "#ff7a18",
      danger: "#e0432f",
      success: "#5aa843",
      warning: "#f0a020",
      disabled: "#eef1f3",
      disabledText: "#b8bfc4",
      controlBg: "#ffffff",
      controlBgHover: "#f4f6f8",
      controlBgActive: "#e8ebee",
      controlBgPrimary: "#ff7a18",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 0 0 1px #c8cdd2",
      shadowInset: "inset 0 1px 2px rgba(46, 51, 56, 0.06)",
      shadowWindow: "0 4px 14px rgba(46, 51, 56, 0.18)",
      radius: "2px",
      radiusWindow: "3px",
      radiusControl: "2px",
      borderWidth: "1px",
      fontSize: "13px",
      lineHeight: "1.4",
      controlHeight: "32px",
      titlebarHeight: "32px",
      space: "12px",
      letterSpacing: "0.04em",
    },
  }),
  defineTheme({
    id: "myst",
    slug: "myst",
    name: "Myst",
    year: 1993,
    era: "Gaming",
    description:
      "A book falls open: parchment panels with brass fittings, weathered serif type, and the patience of a puzzle with no timer.",
    tags: ["cyan", "point-and-click", "parchment", "puzzle", "serif"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: serifStack, mono: monoStack, display: serifStack },
    tokens: {
      desktop: "linear-gradient(180deg, #2a2620, #12100c)",
      surface: "linear-gradient(180deg, #ead9b4, #d8c498)",
      surfaceAlt: "#d0bc8c",
      text: "#3a2c18",
      textMuted: "#7a6848",
      textOnAccent: "#f4ead0",
      accent: "#7a5a2e",
      accentHover: "#96723c",
      titlebarBg: "linear-gradient(#4a3a22, #2c2214)",
      titlebarText: "#e2d4b0",
      titlebarInactiveBg: "#3a3020",
      titlebarInactiveText: "#a8987a",
      titleLabelBg: "transparent",
      borderHigh: "#f0e4c4",
      borderLight: "#8a7040",
      borderDark: "#4a3a22",
      borderLow: "#2c2214",
      fieldBg: "#f0e4c4",
      fieldText: "#3a2c18",
      selectionBg: "#8a7440",
      selectionText: "#f4ead0",
      focus: "#7a5a2e",
      danger: "#8a2a22",
      success: "#4a6a3a",
      warning: "#b8862a",
      disabled: "#c8b890",
      disabledText: "#a8987a",
      controlBg: "linear-gradient(#e8d8b4, #cdb88a)",
      controlBgHover: "linear-gradient(#f0e2c0, #d6c296)",
      controlBgActive: "#c4ae80",
      controlBgPrimary: "#5c4522",
      controlTextPrimary: "#f4ead0",
      shadowOutset: "inset 0 0 0 1px #8a7040",
      shadowInset: "inset 0 2px 3px rgba(58, 44, 24, 0.25)",
      shadowWindow: "0 6px 16px rgba(10, 8, 4, 0.55)",
      radius: "4px",
      radiusWindow: "4px",
      radiusControl: "4px",
      borderWidth: "2px",
      fontSize: "13px",
      lineHeight: "1.45",
      controlHeight: "30px",
      titlebarHeight: "28px",
      space: "10px",
      letterSpacing: "0",
    },
  }),
];
