import { bevelWin95, defineTheme, monoStack, orbitronStack, pixelStack, plexSans, vtStack } from "./helpers";
import type { RetroTheme } from "./types";

export const gamingThemes: RetroTheme[] = [
  defineTheme(
    {
      id: "8bit-arcade",
      slug: "8bit-arcade",
      name: "8-Bit Arcade",
      year: 1983,
      era: "Gaming",
      description: "Cabinet HUD: chunky pixels, neon insert art, and high-score chrome.",
      tags: ["arcade", "pixel", "neon"],
      engine: "pixel",
      controls: "none",
      desktopPattern: "stars",
      fonts: { ui: pixelStack, mono: pixelStack, display: pixelStack },
      tokens: {
        desktop: "#0b0b1e",
        surface: "#16162e",
        surfaceAlt: "#221a3a",
        text: "#ffffff",
        textMuted: "#8a8ab8",
        accent: "#ff2d95",
        accentHover: "#ff6bb3",
        titlebarBg: "#ff2d95",
        titlebarText: "#ffffff",
        titlebarInactiveBg: "#221a3a",
        titlebarInactiveText: "#8a8ab8",
        borderHigh: "#00e5ff",
        borderLight: "#00e5ff",
        borderDark: "#7c1dfd",
        borderLow: "#ffd300",
        fieldBg: "#0b0b1e",
        fieldText: "#ffffff",
        selectionBg: "#7c1dfd",
        selectionText: "#ffffff",
        focus: "#ffd300",
        danger: "#ff3b3b",
        success: "#2bff88",
        warning: "#ffd300",
        disabled: "#16162e",
        disabledText: "#8a8ab8",
        controlBg: "#221a3a",
        controlBgHover: "#2e2450",
        controlBgActive: "#16162e",
        controlBgPrimary: "#ff2d95",
        controlTextPrimary: "#ffffff",
        shadowOutset: "4px 4px 0 #000000",
        shadowInset: "inset 0 0 0 2px #00e5ff",
        shadowWindow: "6px 6px 0 #000000",
        borderWidth: "3px",
        fontSize: "11px",
        controlHeight: "32px",
        titlebarHeight: "28px",
        letterSpacing: "0.04em",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "gameboy-dmg",
      slug: "gameboy-dmg",
      name: "Game Boy DMG",
      year: 1989,
      era: "Gaming",
      description: "Olive brick and four-shade olive LCD. 160×144 thinking, chunky 2px rules.",
      tags: ["gameboy", "lcd", "4-shade"],
      engine: "pixel",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: pixelStack, mono: pixelStack, display: pixelStack },
      tokens: {
        desktop: "#8a8478",
        surface: "#9bbc0f",
        surfaceAlt: "#8bac0f",
        text: "#0f380f",
        textMuted: "#306230",
        accent: "#0f380f",
        accentHover: "#306230",
        titlebarBg: "#306230",
        titlebarText: "#9bbc0f",
        titlebarInactiveBg: "#8bac0f",
        titlebarInactiveText: "#306230",
        borderHigh: "#0f380f",
        borderLight: "#0f380f",
        borderDark: "#0f380f",
        borderLow: "#0f380f",
        fieldBg: "#8bac0f",
        fieldText: "#0f380f",
        selectionBg: "#0f380f",
        selectionText: "#9bbc0f",
        focus: "#0f380f",
        danger: "#0f380f",
        success: "#306230",
        warning: "#306230",
        disabled: "#8bac0f",
        disabledText: "#306230",
        controlBg: "#8bac0f",
        controlBgHover: "#9bbc0f",
        controlBgActive: "#306230",
        controlBgPrimary: "#0f380f",
        controlTextPrimary: "#9bbc0f",
        shadowOutset: "3px 3px 0 #0f380f",
        shadowInset: "inset 2px 2px 0 #306230",
        shadowWindow: "4px 4px 0 #6a6458",
        borderWidth: "3px",
        fontSize: "11px",
        controlHeight: "28px",
        titlebarHeight: "24px",
        letterSpacing: "0.02em",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "ps1-tech",
      slug: "ps1-tech",
      name: "PS1 Tech",
      year: 1994,
      era: "Gaming",
      description: "Low-poly startup energy: dithered gradients, UI meshes, and boot-logo chrome.",
      tags: ["playstation", "low-poly", "tech"],
      engine: "graphic",
      controls: "none",
      desktopPattern: "perspective",
      fonts: { ui: orbitronStack, mono: monoStack, display: orbitronStack },
      tokens: {
        desktop: "#0a0a10",
        surface: "#181820",
        surfaceAlt: "#2a2a32",
        text: "#e8e8f0",
        textMuted: "#808088",
        accent: "#00ffff",
        accentHover: "#66ffff",
        titlebarBg: "linear-gradient(90deg, #2a2a32, #00ffff22)",
        titlebarText: "#00ffff",
        titlebarInactiveBg: "#181820",
        titlebarInactiveText: "#808088",
        borderHigh: "#c0c0c0",
        borderLight: "#606068",
        borderDark: "#2a2a32",
        borderLow: "#9d4edd",
        fieldBg: "#0a0a10",
        fieldText: "#e8e8f0",
        selectionBg: "#9d4edd",
        selectionText: "#ffffff",
        focus: "#00ffff",
        danger: "#ff3355",
        success: "#39ff14",
        warning: "#ffd300",
        disabled: "#181820",
        disabledText: "#606068",
        controlBg: "#2a2a32",
        controlBgHover: "#3a3a44",
        controlBgActive: "#181820",
        controlBgPrimary: "linear-gradient(90deg, #00ffff, #9d4edd)",
        controlTextPrimary: "#0a0a10",
        shadowOutset: "0 0 0 1px #00ffff",
        shadowInset: "inset 0 0 12px rgba(0,255,255,0.15)",
        shadowWindow: "0 0 24px rgba(157, 78, 221, 0.35)",
        radius: "2px",
        radiusWindow: "2px",
        radiusControl: "2px",
        borderWidth: "1px",
        fontSize: "12px",
        controlHeight: "26px",
        titlebarHeight: "26px",
        letterSpacing: "0.12em",
      },
    },
    bevelWin95,
  ),
  defineTheme(
    {
      id: "winamp-skin",
      slug: "winamp-skin",
      name: "Winamp Skin",
      year: 1997,
      era: "App",
      description: "Classic media-player skin: brushed metal, LCD green, visor buttons, and EQ chrome.",
      tags: ["winamp", "media", "lcd"],
      engine: "graphic",
      controls: "win",
      desktopPattern: "none",
      fonts: { ui: plexSans, mono: vtStack, display: plexSans },
      tokens: {
        desktop: "#1a1a1a",
        surface: "#3c3c3c",
        surfaceAlt: "#5a5a5a",
        text: "#d0d0d0",
        textMuted: "#8a8a8a",
        accent: "#00ff33",
        accentHover: "#66ff77",
        titlebarBg: "linear-gradient(#5a5a5a, #2a2a2a)",
        titlebarText: "#ffffff",
        titlebarInactiveBg: "#2a2a2a",
        titlebarInactiveText: "#8a8a8a",
        borderHigh: "#8a8a8a",
        borderLight: "#5a5a5a",
        borderDark: "#1a1a1a",
        borderLow: "#000000",
        fieldBg: "#001a08",
        fieldText: "#00ff33",
        selectionBg: "#004d11",
        selectionText: "#00ff33",
        focus: "#ffb400",
        danger: "#ff4040",
        success: "#00ff33",
        warning: "#ffb400",
        disabled: "#3c3c3c",
        disabledText: "#6a6a6a",
        controlBg: "linear-gradient(#6a6a6a, #3c3c3c)",
        controlBgHover: "linear-gradient(#7a7a7a, #4a4a4a)",
        controlBgActive: "#2a2a2a",
        controlBgPrimary: "linear-gradient(#3a3a3a, #111111)",
        controlTextPrimary: "#00ff33",
        shadowOutset: "inset 1px 1px 0 #8a8a8a, inset -1px -1px 0 #000000",
        shadowInset: "inset 0 0 8px #001a08",
        shadowWindow: "0 8px 18px rgba(0,0,0,0.55)",
        radius: "2px",
        radiusWindow: "3px",
        radiusControl: "2px",
        borderWidth: "1px",
        fontSize: "11px",
        controlHeight: "20px",
        titlebarHeight: "14px",
      },
    },
    bevelWin95,
  ),
];
