import {
  chicagoStack,
  defineTheme,
  genevaStack,
  helveticaStack,
  monoStack,
  tahomaStack,
} from "./helpers";

/**
 * Mobile operating systems — the pre-iPhone stylus era through the
 * smartphone platforms that defined the 2000s and early 2010s.
 */
export const mobileThemes = [
  defineTheme({
    id: "android-holo",
    slug: "android-holo",
    name: "Android Holo",
    year: 2011,
    era: "Mobile",
    description:
      "Ice Cream Sandwich holograms: near-black blue glass, Roboto, hairline dividers, and the #33b5e5 cyan accent that made Android feel sci-fi.",
    tags: ["android", "google", "ics", "holo", "dark"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: {
      ui: "Roboto, \"Segoe UI\", sans-serif",
      mono: "\"Droid Sans Mono\", " + monoStack,
      display: "Roboto, \"Segoe UI\", sans-serif",
    },
    tokens: {
      desktop: "linear-gradient(180deg, #101a24, #060a0e)",
      surface: "#1b232c",
      surfaceAlt: "#232d38",
      text: "#f2f6f8",
      textMuted: "#8a97a0",
      textOnAccent: "#ffffff",
      accent: "#33b5e5",
      accentHover: "#4dc6f4",
      titlebarBg: "#141c24",
      titlebarText: "#cfd8de",
      titlebarInactiveBg: "#10161d",
      titlebarInactiveText: "#5a6770",
      titleLabelBg: "transparent",
      borderHigh: "rgba(255, 255, 255, 0.22)",
      borderLight: "rgba(255, 255, 255, 0.12)",
      borderDark: "rgba(0, 0, 0, 0.5)",
      borderLow: "rgba(0, 0, 0, 0.7)",
      fieldBg: "#10161d",
      fieldText: "#e8eef2",
      selectionBg: "#33b5e5",
      selectionText: "#ffffff",
      focus: "#33b5e5",
      danger: "#ff4444",
      success: "#99cc00",
      warning: "#ffbb33",
      disabled: "#1a212a",
      disabledText: "#59666f",
      controlBg: "#2a333d",
      controlBgHover: "#323d48",
      controlBgActive: "#3a4652",
      controlBgPrimary: "#33b5e5",
      controlTextPrimary: "#06121a",
      shadowOutset: "inset 0 0 0 1px rgba(255, 255, 255, 0.08)",
      shadowInset: "inset 0 2px 4px rgba(0, 0, 0, 0.5)",
      shadowWindow: "0 3px 10px rgba(0, 0, 0, 0.55)",
      radius: "2px",
      radiusWindow: "3px",
      radiusControl: "2px",
      borderWidth: "1px",
      fontSize: "14px",
      lineHeight: "1.45",
      controlHeight: "36px",
      titlebarHeight: "30px",
      space: "12px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "blackberry-os",
    slug: "blackberry-os",
    name: "BlackBerry OS",
    year: 2008,
    era: "Mobile",
    description:
      "The Bold's Precision theme: glossy black-blue chrome, pill-shaped blue selection bars, and the hardware keyboard elite's cramped confidence.",
    tags: ["rim", "blackberry", "bold", "glossy", "smartphone"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "linear-gradient(180deg, #101822, #05070c)",
      surface: "#141a22",
      surfaceAlt: "#1a2230",
      text: "#f4f6f8",
      textMuted: "#96a2ae",
      textOnAccent: "#ffffff",
      accent: "#2a75c8",
      accentHover: "#4a96e8",
      titlebarBg: "linear-gradient(#3c4650, #14181e)",
      titlebarText: "#f4f6f8",
      titlebarInactiveBg: "#1c222a",
      titlebarInactiveText: "#6a7682",
      titleLabelBg: "transparent",
      borderHigh: "rgba(255, 255, 255, 0.25)",
      borderLight: "rgba(255, 255, 255, 0.14)",
      borderDark: "#060a0e",
      borderLow: "#000000",
      fieldBg: "#10151c",
      fieldText: "#f4f6f8",
      selectionBg: "linear-gradient(#3a86d8, #1a5cb0)",
      selectionText: "#ffffff",
      focus: "#3a86d8",
      danger: "#d0342c",
      success: "#4a9a3c",
      warning: "#e8a33d",
      disabled: "#1a2028",
      disabledText: "#5a6672",
      controlBg: "linear-gradient(#47525e, #1c232c)",
      controlBgHover: "linear-gradient(#556270, #232c37)",
      controlBgActive: "#5a6672",
      controlBgPrimary: "linear-gradient(#4a9ae8, #1a5cb8)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 rgba(255, 255, 255, 0.18), 0 1px 3px rgba(0, 0, 0, 0.45)",
      shadowInset: "inset 0 2px 4px rgba(0, 0, 0, 0.5)",
      shadowWindow: "0 8px 24px rgba(0, 0, 0, 0.55)",
      radius: "6px",
      radiusWindow: "8px",
      radiusControl: "6px",
      borderWidth: "1px",
      fontSize: "12px",
      lineHeight: "1.35",
      controlHeight: "30px",
      titlebarHeight: "28px",
      space: "10px",
      letterSpacing: "0.01em",
    },
  }),
  defineTheme({
    id: "symbian-s60",
    slug: "symbian-s60",
    name: "Symbian S60",
    year: 2005,
    era: "Mobile",
    description:
      "Nokia's smartphone mainstream: pale blue-gray standby screen, blue gradient title strips, rounded popups, and the Options / Exit softkeys.",
    tags: ["nokia", "symbian", "s60", "smartphone"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "linear-gradient(180deg, #dce6ef, #c3d2df)",
      surface: "#ffffff",
      surfaceAlt: "#eef4f9",
      text: "#202b38",
      textMuted: "#6a7886",
      textOnAccent: "#ffffff",
      accent: "#0a5ba8",
      accentHover: "#1277cc",
      titlebarBg: "linear-gradient(#4a97dd, #1a63b0)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#c9d6e2",
      titlebarInactiveText: "#6a7886",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#d3deea",
      borderDark: "#9ab0c4",
      borderLow: "#74889a",
      fieldBg: "#ffffff",
      fieldText: "#202b38",
      selectionBg: "linear-gradient(#4a97dd, #1a63b0)",
      selectionText: "#ffffff",
      focus: "#0a5ba8",
      danger: "#c0392b",
      success: "#3a8a3a",
      warning: "#e8a33d",
      disabled: "#e8eef4",
      disabledText: "#9ab0c4",
      controlBg: "linear-gradient(#ffffff, #dfe8f0)",
      controlBgHover: "linear-gradient(#ffffff, #eaf1f7)",
      controlBgActive: "#d3deea",
      controlBgPrimary: "linear-gradient(#4a97dd, #1a63b0)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 2px rgba(30, 50, 70, 0.25)",
      shadowInset: "inset 0 2px 3px rgba(30, 50, 70, 0.18)",
      shadowWindow: "0 6px 18px rgba(30, 50, 70, 0.3)",
      radius: "8px",
      radiusWindow: "8px",
      radiusControl: "8px",
      borderWidth: "1px",
      fontSize: "13px",
      lineHeight: "1.4",
      controlHeight: "32px",
      titlebarHeight: "30px",
      space: "10px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "palm-webos",
    slug: "palm-webos",
    name: "Palm webOS",
    year: 2009,
    era: "Mobile",
    description:
      "Cards on a dusk wallpaper: dark rounded app headers, off-white cards you flick away, and the black status bar up top with the clock.",
    tags: ["palm", "webos", "pre", "cards", "gesture"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    taskbarPosition: "top",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "linear-gradient(180deg, #22303c 0%, #52636b 50%, #9c7a5e 82%, #b6896a 100%)",
      surface: "#f4f5f4",
      surfaceAlt: "#e8eae8",
      text: "#24282c",
      textMuted: "#808a90",
      textOnAccent: "#ffffff",
      accent: "#1a7ac8",
      accentHover: "#35a0f0",
      titlebarBg: "linear-gradient(#3a4046, #171a1e)",
      titlebarText: "#f4f5f4",
      titlebarInactiveBg: "#d4d8da",
      titlebarInactiveText: "#808a90",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#d8dcde",
      borderDark: "#b0b8be",
      borderLow: "#8a949c",
      fieldBg: "#ffffff",
      fieldText: "#24282c",
      selectionBg: "#1a7ac8",
      selectionText: "#ffffff",
      focus: "#1a7ac8",
      danger: "#d0342c",
      success: "#4a9a3c",
      warning: "#e8a33d",
      disabled: "#e8eae8",
      disabledText: "#a8b2b8",
      controlBg: "linear-gradient(#fdfdfd, #dcdfe2)",
      controlBgHover: "linear-gradient(#ffffff, #e6e9ec)",
      controlBgActive: "#cdd2d6",
      controlBgPrimary: "#1a7ac8",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 3px rgba(10, 20, 30, 0.3)",
      shadowInset: "inset 0 2px 4px rgba(10, 20, 30, 0.18)",
      shadowWindow: "0 12px 32px rgba(8, 16, 24, 0.45)",
      radius: "8px",
      radiusWindow: "12px",
      radiusControl: "8px",
      borderWidth: "1px",
      fontSize: "13px",
      lineHeight: "1.4",
      controlHeight: "32px",
      titlebarHeight: "32px",
      space: "10px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "windows-mobile",
    slug: "windows-mobile",
    name: "Windows Mobile",
    year: 2005,
    era: "Mobile",
    description:
      "Pocket PC / Windows Mobile 5: blue gradient title bar with Start, Tahoma at 12px, a softkey bar below, and the stylus-scuffed Today screen.",
    tags: ["microsoft", "pocket-pc", "stylus", "windows-mobile"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    taskbarPosition: "top",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {
      desktop: "#d7dde4",
      surface: "#f4f6f8",
      surfaceAlt: "#e8edf2",
      text: "#101820",
      textMuted: "#5a6874",
      textOnAccent: "#ffffff",
      accent: "#1c5fa8",
      accentHover: "#2a75c2",
      titlebarBg: "linear-gradient(#4a97e0, #1c5fa8)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#c3ccd6",
      titlebarInactiveText: "#5a6874",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#e2e8ee",
      borderDark: "#9aa8b6",
      borderLow: "#76848f",
      fieldBg: "#ffffff",
      fieldText: "#101820",
      selectionBg: "#2a76c2",
      selectionText: "#ffffff",
      focus: "#1c5fa8",
      danger: "#c0392b",
      success: "#2a8a4a",
      warning: "#d9982a",
      disabled: "#e8edf2",
      disabledText: "#9aa8b6",
      controlBg: "linear-gradient(#ffffff, #d8dee6)",
      controlBgHover: "linear-gradient(#ffffff, #e4eaf1)",
      controlBgActive: "#cdd6df",
      controlBgPrimary: "linear-gradient(#4a97e0, #1c5fa8)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 2px rgba(16, 24, 32, 0.25)",
      shadowInset: "inset 0 2px 3px rgba(16, 24, 32, 0.18)",
      shadowWindow: "0 4px 12px rgba(16, 24, 32, 0.3)",
      radius: "3px",
      radiusWindow: "3px",
      radiusControl: "3px",
      borderWidth: "1px",
      fontSize: "12px",
      lineHeight: "1.3",
      controlHeight: "26px",
      titlebarHeight: "26px",
      space: "8px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "newton-os",
    slug: "newton-os",
    name: "Newton OS",
    year: 1993,
    era: "Mobile",
    description:
      "Apple's MessagePad PDA: grayscale rounded panes, Chicago-style labels, beveled buttons the size of fingertips, and handwriting everywhere.",
    tags: ["apple", "newton", "pda", "grayscale", "handwriting"],
    engine: "system7",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: chicagoStack, mono: monoStack, display: chicagoStack },
    tokens: {
      desktop: "#b0b4b0",
      surface: "#e4e6e4",
      surfaceAlt: "#d2d6d2",
      text: "#1a1a1a",
      textMuted: "#5a5e5a",
      textOnAccent: "#ffffff",
      accent: "#2a2e2a",
      accentHover: "#3c403c",
      titlebarBg: "linear-gradient(#d0d4d0, #a8aca8)",
      titlebarText: "#1a1a1a",
      titlebarInactiveBg: "#c2c6c2",
      titlebarInactiveText: "#6a6e6a",
      titleLabelBg: "transparent",
      borderHigh: "#f4f6f4",
      borderLight: "#dcdedc",
      borderDark: "#8a8e8a",
      borderLow: "#565a56",
      fieldBg: "#f4f6f4",
      fieldText: "#1a1a1a",
      selectionBg: "#3c403c",
      selectionText: "#ffffff",
      focus: "#2a2e2a",
      danger: "#7a2a2a",
      success: "#2a6a3a",
      warning: "#7a5a1a",
      disabled: "#c8ccc8",
      disabledText: "#8a8e8a",
      controlBg: "#d8dcd8",
      controlBgHover: "#e4e8e4",
      controlBgActive: "#c2c6c2",
      controlBgPrimary: "#2a2e2a",
      controlTextPrimary: "#ffffff",
      shadowOutset:
        "inset -1px -1px #7a7e7a, inset 1px 1px #ffffff, inset -2px -2px #565a56, inset 2px 2px #ececec",
      shadowInset:
        "inset -1px -1px #ffffff, inset 1px 1px #7a7e7a, inset -2px -2px #ececec, inset 2px 2px #565a56",
      shadowWindow: "2px 2px 0 rgba(0, 0, 0, 0.35)",
      radius: "8px",
      radiusWindow: "10px",
      radiusControl: "8px",
      borderWidth: "0px",
      fontSize: "13px",
      lineHeight: "1.35",
      controlHeight: "30px",
      titlebarHeight: "24px",
      space: "8px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "magic-cap",
    slug: "magic-cap",
    name: "Magic Cap",
    year: 1995,
    era: "Mobile",
    description:
      "General Magic's communicator: rooms full of objects, chunky rounded bevels, and bold black labels floating on stone-blue. The phone OS from a parallel universe.",
    tags: ["general-magic", "magic-cap", "pda", "communicator", "skeuomorphic"],
    engine: "bevel",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: genevaStack, mono: monoStack, display: genevaStack },
    tokens: {
      desktop: "linear-gradient(180deg, #a8b6be, #8ea0aa)",
      surface: "#eef2f4",
      surfaceAlt: "#dde4e8",
      text: "#101418",
      textMuted: "#5a666e",
      textOnAccent: "#ffffff",
      accent: "#3a6a9e",
      accentHover: "#4a7ab5",
      titlebarBg: "linear-gradient(#76858f, #55636d)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#a8b4bc",
      titlebarInactiveText: "#e4eaee",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#f2f6f8",
      borderDark: "#6a7880",
      borderLow: "#4a565e",
      fieldBg: "#f4f6f8",
      fieldText: "#101418",
      selectionBg: "#34547e",
      selectionText: "#ffffff",
      focus: "#3a6a9e",
      danger: "#a04a30",
      success: "#3a7a4a",
      warning: "#b8862a",
      disabled: "#d2dade",
      disabledText: "#8a969e",
      controlBg: "#e2e8ec",
      controlBgHover: "#eef2f4",
      controlBgActive: "#cdd6dc",
      controlBgPrimary: "#3a6a9e",
      controlTextPrimary: "#ffffff",
      shadowOutset:
        "inset -2px -2px #6a7880, inset 2px 2px #ffffff, inset -3px -3px #4a565e, inset 3px 3px #f2f6f8",
      shadowInset:
        "inset -2px -2px #ffffff, inset 2px 2px #6a7880, inset -3px -3px #f2f6f8, inset 3px 3px #4a565e",
      shadowWindow: "3px 3px 0 rgba(16, 24, 32, 0.35)",
      radius: "8px",
      radiusWindow: "8px",
      radiusControl: "10px",
      borderWidth: "0px",
      fontSize: "13px",
      lineHeight: "1.35",
      controlHeight: "32px",
      titlebarHeight: "26px",
      space: "10px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "meego-n9",
    slug: "meego-n9",
    name: "MeeGo N9",
    year: 2011,
    era: "Mobile",
    description:
      "The phone Nokia killed: true black charcoal, one swipe instead of a home button, rounded dark tiles, and a calm nobody copied in time.",
    tags: ["nokia", "meego", "harmattan", "swipe", "dark"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "linear-gradient(180deg, #1a1e26, #05060a)",
      surface: "#1e2228",
      surfaceAlt: "#2a2f38",
      text: "#f4f6f8",
      textMuted: "#8a939e",
      textOnAccent: "#ffffff",
      accent: "#1ea7e1",
      accentHover: "#4cc0f0",
      titlebarBg: "#111418",
      titlebarText: "#f4f6f8",
      titlebarInactiveBg: "#191d23",
      titlebarInactiveText: "#6a737e",
      titleLabelBg: "transparent",
      borderHigh: "rgba(255, 255, 255, 0.18)",
      borderLight: "rgba(255, 255, 255, 0.1)",
      borderDark: "rgba(0, 0, 0, 0.6)",
      borderLow: "#000000",
      fieldBg: "#161a20",
      fieldText: "#f4f6f8",
      selectionBg: "#1ea7e1",
      selectionText: "#ffffff",
      focus: "#1ea7e1",
      danger: "#e0503a",
      success: "#48b06a",
      warning: "#f0a030",
      disabled: "#1a1e25",
      disabledText: "#5a636e",
      controlBg: "#282e37",
      controlBgHover: "#323944",
      controlBgActive: "#3a424e",
      controlBgPrimary: "#1ea7e1",
      controlTextPrimary: "#05070a",
      shadowOutset: "inset 0 0 0 1px rgba(255, 255, 255, 0.08)",
      shadowInset: "inset 0 2px 4px rgba(0, 0, 0, 0.5)",
      shadowWindow: "0 8px 24px rgba(0, 0, 0, 0.55)",
      radius: "8px",
      radiusWindow: "10px",
      radiusControl: "8px",
      borderWidth: "1px",
      fontSize: "14px",
      lineHeight: "1.45",
      controlHeight: "36px",
      titlebarHeight: "32px",
      space: "12px",
      letterSpacing: "0",
    },
  }),
];
