import { defineTheme, terminalBase, vtStack, monoStack, pixelStack } from "./helpers";
import type { RetroTheme } from "./types";

export const terminalThemes: RetroTheme[] = [
  defineTheme(
    {
      id: "teletext",
      slug: "teletext",
      name: "Teletext",
      year: 1974,
      era: "Broadcast",
      description:
        "Ceefax / ORACLE mosaic: 40×25 cells, double-height headlines, and the seven broadcast primaries.",
      tags: ["teletext", "tv", "blocky"],
      engine: "pixel",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: pixelStack, mono: vtStack, display: pixelStack },
      tokens: {
        desktop: "#000000",
        surface: "#000000",
        surfaceAlt: "#0000aa",
        text: "#ffffff",
        textMuted: "#00ffff",
        accent: "#ffff00",
        accentHover: "#ffffff",
        titlebarBg: "#0000aa",
        titlebarText: "#ffff00",
        titlebarInactiveBg: "#000000",
        titlebarInactiveText: "#aaaaaa",
        borderHigh: "#ffffff",
        borderLight: "#00ffff",
        borderDark: "#0000aa",
        borderLow: "#ff00ff",
        fieldBg: "#000000",
        fieldText: "#00ff00",
        selectionBg: "#ffff00",
        selectionText: "#000000",
        focus: "#ffff00",
        danger: "#ff0000",
        success: "#00ff00",
        warning: "#ffff00",
        disabled: "#000000",
        disabledText: "#aaaaaa",
        controlBg: "#0000aa",
        controlBgHover: "#0000ee",
        controlBgActive: "#000088",
        controlBgPrimary: "#ffff00",
        controlTextPrimary: "#000000",
        shadowOutset: "none",
        shadowInset: "none",
        shadowWindow: "none",
        fontSize: "14px",
        controlHeight: "32px",
        titlebarHeight: "32px",
        letterSpacing: "0.04em",
      },
    },
    terminalBase,
  ),
  defineTheme(
    {
      id: "crt-phosphor",
      slug: "crt-phosphor",
      name: "CRT Phosphor",
      year: 1980,
      era: "Terminal",
      description: "P1 green phosphor, bloom, scanlines, and a prompt-first terminal surface.",
      tags: ["terminal", "green", "scanline"],
      engine: "terminal",
      controls: "none",
      desktopPattern: "scanlines",
      fonts: { ui: vtStack, mono: vtStack, display: vtStack },
      tokens: {},
    },
    terminalBase,
  ),
  defineTheme(
    {
      id: "dos-cga",
      slug: "dos-cga",
      name: "DOS CGA",
      year: 1981,
      era: "Terminal",
      description: "MS-DOS on CGA: black screen, cyan/magenta/white palette, and 80-column command bars.",
      tags: ["dos", "cga", "cyan"],
      engine: "terminal",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: vtStack, mono: vtStack, display: vtStack },
      tokens: {
        desktop: "#000000",
        surface: "#000000",
        surfaceAlt: "#0000aa",
        text: "#55ffff",
        textMuted: "#00aaaa",
        accent: "#ff55ff",
        accentHover: "#ff55ff",
        titlebarBg: "#0000aa",
        titlebarText: "#ffffff",
        titlebarInactiveBg: "#000000",
        titlebarInactiveText: "#00aaaa",
        borderHigh: "#55ffff",
        borderLight: "#00aaaa",
        borderDark: "#0000aa",
        borderLow: "#ff55ff",
        fieldBg: "#000000",
        fieldText: "#ffffff",
        selectionBg: "#0000aa",
        selectionText: "#ffffff",
        focus: "#ffff55",
        danger: "#ff5555",
        success: "#55ff55",
        warning: "#ffff55",
        disabled: "#000000",
        disabledText: "#00aaaa",
        controlBg: "#0000aa",
        controlBgHover: "#0000ee",
        controlBgActive: "#000088",
        controlBgPrimary: "#00aaaa",
        controlTextPrimary: "#000000",
        shadowWindow: "none",
        fontSize: "18px",
      },
    },
    terminalBase,
  ),
  defineTheme(
    {
      id: "ibm-3270",
      slug: "ibm-3270",
      name: "IBM 3270",
      year: 1971,
      era: "Terminal",
      description: "Mainframe CICS green-screen: protected fields, cyan status, and block-addressable forms.",
      tags: ["ibm", "mainframe", "cics"],
      engine: "terminal",
      controls: "none",
      desktopPattern: "scanlines",
      fonts: { ui: `"IBM Plex Mono", ${vtStack}`, mono: `"IBM Plex Mono", ${vtStack}`, display: `"IBM Plex Mono", ${vtStack}` },
      tokens: {
        desktop: "#000000",
        surface: "#000000",
        surfaceAlt: "#001818",
        text: "#00d4d4",
        textMuted: "#00a0a0",
        accent: "#00d400",
        titlebarBg: "#000000",
        titlebarText: "#00d400",
        titlebarInactiveText: "#00a0a0",
        borderHigh: "#00d4d4",
        borderLight: "#00a0a0",
        borderDark: "#006868",
        borderLow: "#00d400",
        fieldBg: "#001010",
        fieldText: "#e4e4e4",
        selectionBg: "#00d400",
        selectionText: "#000000",
        focus: "#ffe84a",
        danger: "#ff3030",
        success: "#00d400",
        warning: "#ffe84a",
        controlBg: "#000000",
        controlBgHover: "#001818",
        controlBgPrimary: "#00d400",
        controlTextPrimary: "#000000",
        fontSize: "16px",
      },
    },
    terminalBase,
  ),
  defineTheme(
    {
      id: "nethack-ascii",
      slug: "nethack-ascii",
      name: "NetHack ASCII",
      year: 1987,
      era: "Terminal",
      description: "Roguelike dungeon chrome: `@` hero, colored ASCII, and status lines for HP and AC.",
      tags: ["ascii", "roguelike", "nethack"],
      engine: "terminal",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: monoStack, mono: monoStack, display: monoStack },
      tokens: {
        desktop: "#000000",
        surface: "#000000",
        surfaceAlt: "#141414",
        text: "#c8c8c8",
        textMuted: "#707070",
        accent: "#ffff00",
        titlebarBg: "#000000",
        titlebarText: "#ffff00",
        borderHigh: "#c8c8c8",
        borderLight: "#707070",
        borderDark: "#404040",
        borderLow: "#ffff00",
        fieldBg: "#000000",
        fieldText: "#c8c8c8",
        selectionBg: "#ffff00",
        selectionText: "#000000",
        focus: "#ffff00",
        danger: "#ff4040",
        success: "#40ff40",
        warning: "#ffff00",
        controlBg: "#000000",
        controlBgHover: "#1a1a1a",
        controlBgPrimary: "#ffff00",
        controlTextPrimary: "#000000",
        fontSize: "15px",
        letterSpacing: "0.02em",
      },
    },
    terminalBase,
  ),
  defineTheme(
    {
      id: "bbs-ansi",
      slug: "bbs-ansi",
      name: "BBS ANSI Art",
      year: 1989,
      era: "Terminal",
      description: "Dial-up board aesthetic: 16-color ANSI, shadow masks, and login-door menus.",
      tags: ["bbs", "ansi", "16-color"],
      engine: "terminal",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: vtStack, mono: vtStack, display: vtStack },
      tokens: {
        desktop: "#000000",
        surface: "#000000",
        surfaceAlt: "#0000aa",
        text: "#aaaaaa",
        textMuted: "#555555",
        accent: "#55ffff",
        titlebarBg: "#0000aa",
        titlebarText: "#ffff55",
        borderHigh: "#ffffff",
        borderLight: "#55ffff",
        borderDark: "#0000aa",
        borderLow: "#aa00aa",
        fieldBg: "#000000",
        fieldText: "#55ff55",
        selectionBg: "#aa5500",
        selectionText: "#ffffff",
        focus: "#ffff55",
        danger: "#ff5555",
        success: "#55ff55",
        warning: "#ffff55",
        controlBg: "#0000aa",
        controlBgHover: "#0000ee",
        controlBgPrimary: "#aa00aa",
        controlTextPrimary: "#ffffff",
        fontSize: "16px",
      },
    },
    terminalBase,
  ),
  defineTheme(
    {
      id: "midnight-commander",
      slug: "midnight-commander",
      name: "Midnight Commander",
      year: 1994,
      era: "Terminal",
      description: "Norton/MC dual-pane TUI: cobalt panels, cyan directories, and function-key footers.",
      tags: ["tui", "ncurses", "filemanager"],
      engine: "terminal",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: monoStack, mono: monoStack, display: monoStack },
      tokens: {
        desktop: "#0000aa",
        surface: "#0000aa",
        surfaceAlt: "#00aaaa",
        text: "#ffffff",
        textMuted: "#aaaaaa",
        accent: "#ffff55",
        titlebarBg: "#00aaaa",
        titlebarText: "#000000",
        titlebarInactiveBg: "#000088",
        titlebarInactiveText: "#aaaaaa",
        borderHigh: "#ffffff",
        borderLight: "#55ffff",
        borderDark: "#000088",
        borderLow: "#ffff55",
        fieldBg: "#000000",
        fieldText: "#ffffff",
        selectionBg: "#00aaaa",
        selectionText: "#000000",
        focus: "#ffff55",
        danger: "#ff5555",
        success: "#55ff55",
        warning: "#ffff55",
        controlBg: "#00aaaa",
        controlBgHover: "#55ffff",
        controlBgPrimary: "#ffff55",
        controlTextPrimary: "#000000",
        fontSize: "14px",
        controlHeight: "24px",
        titlebarHeight: "22px",
      },
    },
    terminalBase,
  ),
  defineTheme(
    {
      id: "matrix-rain",
      slug: "matrix-rain",
      name: "Matrix Rain",
      year: 1999,
      era: "Sci-Fi",
      description: "Digital rain: black void, katakana-adjacent glyphs, and phosphor-bright code green.",
      tags: ["matrix", "green", "code"],
      engine: "terminal",
      controls: "none",
      desktopPattern: "scanlines",
      fonts: { ui: `"Share Tech Mono", ${monoStack}`, mono: `"Share Tech Mono", ${monoStack}`, display: `"Share Tech Mono", ${monoStack}` },
      tokens: {
        desktop: "#000000",
        surface: "#001000",
        surfaceAlt: "#003b00",
        text: "#62ff9d",
        textMuted: "#00a830",
        accent: "#ccffcc",
        titlebarBg: "#001800",
        titlebarText: "#ccffcc",
        borderHigh: "#62ff9d",
        borderLight: "#00a830",
        borderDark: "#003b00",
        borderLow: "#ccffcc",
        fieldBg: "#000800",
        fieldText: "#62ff9d",
        selectionBg: "#00a830",
        selectionText: "#ccffcc",
        focus: "#ccffcc",
        danger: "#ff3860",
        success: "#62ff9d",
        warning: "#c8ff4a",
        controlBg: "#001000",
        controlBgHover: "#003b00",
        controlBgPrimary: "#00a830",
        controlTextPrimary: "#ccffcc",
        shadowWindow: "0 0 24px rgba(98, 255, 157, 0.35)",
      },
    },
    terminalBase,
  ),
  defineTheme(
    {
      id: "btop-meters",
      slug: "btop-meters",
      name: "btop Meters",
      year: 2021,
      era: "Terminal",
      description: "Modern TUI monitor: braille meters, cyan/lime graphs, and dense system telemetry.",
      tags: ["tui", "monitor", "meters"],
      engine: "terminal",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: monoStack, mono: monoStack, display: monoStack },
      tokens: {
        desktop: "#131424",
        surface: "#1a1c30",
        surfaceAlt: "#3b3e5e",
        text: "#e8ecff",
        textMuted: "#7a82b0",
        accent: "#00e4ff",
        titlebarBg: "#1a1c30",
        titlebarText: "#00e4ff",
        titlebarInactiveBg: "#131424",
        titlebarInactiveText: "#7a82b0",
        borderHigh: "#3b3e5e",
        borderLight: "#3b3e5e",
        borderDark: "#3b3e5e",
        borderLow: "#00e4ff",
        fieldBg: "#131424",
        fieldText: "#e8ecff",
        selectionBg: "#3b3e5e",
        selectionText: "#00e4ff",
        focus: "#00e4ff",
        danger: "#ff5d7a",
        success: "#6de37a",
        warning: "#e5e56a",
        disabled: "#1a1c30",
        disabledText: "#7a82b0",
        controlBg: "#1a1c30",
        controlBgHover: "#3b3e5e",
        controlBgPrimary: "#00e4ff",
        controlTextPrimary: "#131424",
        shadowWindow: "0 0 0 1px #3b3e5e",
        fontSize: "13px",
        radius: "4px",
        radiusWindow: "4px",
        radiusControl: "4px",
      },
    },
    terminalBase,
  ),
  defineTheme(
    {
      id: "c64-basic",
      slug: "c64-basic",
      name: "Commodore 64 BASIC",
      year: 1982,
      era: "Terminal",
      description: "READY. Light-blue PETSCII on the signature navy-violet C64 screen.",
      tags: ["c64", "petscii", "basic"],
      engine: "terminal",
      controls: "none",
      desktopPattern: "none",
      fonts: { ui: vtStack, mono: vtStack, display: vtStack },
      tokens: {
        desktop: "#443ec4",
        surface: "#443ec4",
        surfaceAlt: "#2e2898",
        text: "#9692d9",
        textMuted: "#6a66b0",
        accent: "#a8a0ff",
        titlebarBg: "#2e2898",
        titlebarText: "#c8c0ff",
        titlebarInactiveBg: "#2e2898",
        titlebarInactiveText: "#6a66b0",
        borderHigh: "#a8a0ff",
        borderLight: "#9692d9",
        borderDark: "#2e2898",
        borderLow: "#c8c0ff",
        fieldBg: "#2e2898",
        fieldText: "#c8c0ff",
        selectionBg: "#9692d9",
        selectionText: "#2e2898",
        focus: "#ffffff",
        danger: "#e04040",
        success: "#4aff4a",
        warning: "#e0e040",
        disabled: "#2e2898",
        disabledText: "#6a66b0",
        controlBg: "#2e2898",
        controlBgHover: "#443ec4",
        controlBgPrimary: "#9692d9",
        controlTextPrimary: "#2e2898",
        shadowWindow: "none",
        fontSize: "18px",
        letterSpacing: "0.06em",
      },
    },
    terminalBase,
  ),
];
