import {
  defineTheme,
  comicStack,
  displayStack,
  helveticaStack,
  lucidaStack,
  monoStack,
  plexSans,
  serifStack,
  tahomaStack,
} from "./helpers";
import type { RetroTheme } from "./types";

export const webUiThemes: RetroTheme[] = [
  defineTheme({
    id: "geocities-web10",
    slug: "geocities-web10",
    name: "GeoCities Web 1.0",
    year: 1996,
    era: "Web",
    description: "Tiled stars, visitor counters, hot-pink links, and construction-gif energy.",
    tags: ["web1.0", "kitsch", "tiled"],
    engine: "web",
    controls: "none",
    desktopPattern: "stars",
    fonts: { ui: comicStack, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#000000",
      surface: "#000080",
      surfaceAlt: "#000000",
      text: "#ffff00",
      textMuted: "#00ffff",
      accent: "#ff3399",
      accentHover: "#ff66b3",
      titlebarBg: "linear-gradient(90deg, #ff00ff, #00ffff, #ffff00)",
      titlebarText: "#000000",
      titlebarInactiveBg: "#000000",
      titlebarInactiveText: "#ff00ff",
      borderHigh: "#ffffff",
      borderLight: "#00ffff",
      borderDark: "#ff00ff",
      borderLow: "#ffff00",
      fieldBg: "#ffffff",
      fieldText: "#000000",
      selectionBg: "#ff3399",
      selectionText: "#ffffff",
      focus: "#00ff00",
      danger: "#ff0000",
      success: "#00ff00",
      warning: "#ffff00",
      disabled: "#000080",
      disabledText: "#808080",
      controlBg: "#c0c0c0",
      controlBgHover: "#dfdfdf",
      controlBgActive: "#808080",
      controlBgPrimary: "#ff3399",
      controlTextPrimary: "#ffffff",
      shadowOutset: "4px 4px 0 #ff00ff",
      shadowInset: "inset 2px 2px 0 #000000",
      shadowWindow: "8px 8px 0 #00ffff",
      radius: "0px",
      borderWidth: "4px",
      fontSize: "15px",
      controlHeight: "28px",
      titlebarHeight: "28px",
    },
  }),
  defineTheme({
    id: "web20-glossy",
    slug: "web20-glossy",
    name: "Web 2.0 Glossy",
    year: 2005,
    era: "Web/UI",
    description: "Candy buttons, specular reflections, Aqua-adjacent badges, and friendly blue.",
    tags: ["web2.0", "glossy", "reflection"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: lucidaStack, mono: monoStack, display: lucidaStack },
    tokens: {
      desktop: "#dce8f4",
      surface: "#ffffff",
      surfaceAlt: "#e8f0f7",
      text: "#1e3a5c",
      textMuted: "#5a7a9c",
      accent: "#2a7ac9",
      accentHover: "#62a8e8",
      titlebarBg: "linear-gradient(#62a8e8, #1e5a9c)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "linear-gradient(#c8d8e8, #8aa0b4)",
      titlebarInactiveText: "#e8f0f7",
      borderHigh: "#ffffff",
      borderLight: "#d4e8f7",
      borderDark: "#7aa8d0",
      borderLow: "#1e5a9c",
      fieldBg: "#ffffff",
      selectionBg: "#2a7ac9",
      selectionText: "#ffffff",
      focus: "#ff8c1a",
      controlBg: "linear-gradient(#ffffff, #d4e8f7)",
      controlBgHover: "linear-gradient(#ffffff, #eaf4fc)",
      controlBgActive: "#d4e8f7",
      controlBgPrimary: "linear-gradient(#ffc04a, #ff8c1a 50%, #e07000)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 2px 0 #7aa8d0, 0 8px 16px rgba(30,90,156,0.18)",
      shadowInset: "inset 0 2px 4px rgba(30,90,156,0.15)",
      shadowWindow: "0 12px 32px rgba(30,90,156,0.22)",
      radius: "12px",
      radiusWindow: "12px",
      radiusControl: "18px",
      borderWidth: "1px",
      fontSize: "14px",
      controlHeight: "32px",
      titlebarHeight: "36px",
    },
  }),
  defineTheme({
    id: "frutiger-aero",
    slug: "frutiger-aero",
    name: "Frutiger Aero",
    year: 2007,
    era: "Web/UI",
    description: "Sky glass, dewdrop orbs, nature stock, and optimistic aqua-green UI.",
    tags: ["aero", "nature", "glass"],
    engine: "aero",
    controls: "none",
    desktopPattern: "horizon",
    fonts: { ui: plexSans, mono: monoStack, display: plexSans },
    tokens: {
      desktop: "#7fcfff",
      surface: "rgba(255,255,255,0.72)",
      surfaceAlt: "rgba(199,240,255,0.65)",
      text: "#0b2a3c",
      textMuted: "#3a6a80",
      accent: "#0ea5ff",
      accentHover: "#3dd36b",
      titlebarBg: "linear-gradient(rgba(255,255,255,0.7), rgba(127,207,255,0.35))",
      titlebarText: "#0b2a3c",
      titlebarInactiveBg: "rgba(255,255,255,0.35)",
      titlebarInactiveText: "#3a6a80",
      borderHigh: "rgba(255,255,255,0.9)",
      borderLight: "rgba(255,255,255,0.7)",
      borderDark: "rgba(14,165,255,0.35)",
      borderLow: "rgba(11,42,60,0.2)",
      fieldBg: "rgba(255,255,255,0.85)",
      selectionBg: "#0ea5ff",
      selectionText: "#ffffff",
      focus: "#3dd36b",
      danger: "#ff5d7a",
      success: "#3dd36b",
      warning: "#ffd36b",
      controlBg: "linear-gradient(#ffffff, #c7f0ff)",
      controlBgHover: "linear-gradient(#ffffff, #e8fbff)",
      controlBgActive: "#c7f0ff",
      controlBgPrimary: "linear-gradient(#8ef0a8, #3dd36b)",
      controlTextPrimary: "#0b2a3c",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 8px 24px rgba(14,165,255,0.25)",
      shadowInset: "inset 0 1px 3px rgba(11,42,60,0.12)",
      shadowWindow: "0 18px 40px rgba(14,165,255,0.28)",
      radius: "16px",
      radiusWindow: "18px",
      radiusControl: "999px",
      borderWidth: "1px",
      fontSize: "14px",
      controlHeight: "32px",
      titlebarHeight: "36px",
    },
  }),
  defineTheme({
    id: "flat-2013",
    slug: "flat-2013",
    name: "Flat Design 2013",
    year: 2013,
    era: "Web/UI",
    description: "iOS 7 / Metro-era flats: bright tiles, no bevels, and generous whitespace.",
    tags: ["flat", "ios7", "metro"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: plexSans, mono: monoStack, display: plexSans },
    tokens: {
      desktop: "#ecf0f1",
      surface: "#ffffff",
      surfaceAlt: "#ecf0f1",
      text: "#34495e",
      textMuted: "#7f8c8d",
      accent: "#3498db",
      accentHover: "#5dade2",
      titlebarBg: "#3498db",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#95a5a6",
      titlebarInactiveText: "#ffffff",
      borderHigh: "#ecf0f1",
      borderLight: "#ecf0f1",
      borderDark: "#bdc3c7",
      borderLow: "#bdc3c7",
      fieldBg: "#ffffff",
      selectionBg: "#3498db",
      selectionText: "#ffffff",
      focus: "#1abc9c",
      danger: "#e74c3c",
      success: "#2ecc71",
      warning: "#f1c40f",
      controlBg: "#ecf0f1",
      controlBgHover: "#dfe6e9",
      controlBgActive: "#bdc3c7",
      controlBgPrimary: "#3498db",
      controlTextPrimary: "#ffffff",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "0 8px 24px rgba(52,73,94,0.12)",
      radius: "4px",
      radiusWindow: "4px",
      radiusControl: "4px",
      borderWidth: "0px",
      fontSize: "14px",
      controlHeight: "36px",
      titlebarHeight: "48px",
    },
  }),
  defineTheme({
    id: "glassmorphism",
    slug: "glassmorphism",
    name: "Glassmorphism",
    year: 2020,
    era: "Web/UI",
    description: "Frosted panels, vivid blobs behind blur, thin luminous strokes.",
    tags: ["glass", "blur", "frosted"],
    engine: "aero",
    controls: "none",
    desktopPattern: "horizon",
    fonts: { ui: plexSans, mono: monoStack, display: plexSans },
    tokens: {
      desktop: "#1a1030",
      surface: "rgba(255,255,255,0.12)",
      surfaceAlt: "rgba(255,255,255,0.08)",
      text: "#f8f8ff",
      textMuted: "#c8c0e0",
      accent: "#ff6ec4",
      accentHover: "#7873f5",
      titlebarBg: "rgba(255,255,255,0.08)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "rgba(255,255,255,0.04)",
      titlebarInactiveText: "#c8c0e0",
      borderHigh: "rgba(255,255,255,0.45)",
      borderLight: "rgba(255,255,255,0.28)",
      borderDark: "rgba(255,255,255,0.12)",
      borderLow: "rgba(255,110,196,0.45)",
      fieldBg: "rgba(0,0,0,0.25)",
      fieldText: "#ffffff",
      selectionBg: "#7873f5",
      selectionText: "#ffffff",
      focus: "#ff6ec4",
      danger: "#ff6b8a",
      success: "#5ef0c0",
      warning: "#ffd36b",
      disabled: "rgba(255,255,255,0.06)",
      disabledText: "#8a82a8",
      controlBg: "rgba(255,255,255,0.12)",
      controlBgHover: "rgba(255,255,255,0.2)",
      controlBgActive: "rgba(255,255,255,0.08)",
      controlBgPrimary: "linear-gradient(90deg, #ff6ec4, #7873f5)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 rgba(255,255,255,0.35)",
      shadowInset: "inset 0 0 0 1px rgba(255,255,255,0.12)",
      shadowWindow: "0 20px 50px rgba(0,0,0,0.35)",
      radius: "20px",
      radiusWindow: "24px",
      radiusControl: "14px",
      borderWidth: "1px",
      fontSize: "14px",
      controlHeight: "36px",
      titlebarHeight: "40px",
    },
  }),
  defineTheme({
    id: "neumorphism",
    slug: "neumorphism",
    name: "Neumorphism",
    year: 2020,
    era: "Web/UI",
    description: "Soft extruded UI: same-hue lights and shadows, pill controls, low contrast.",
    tags: ["neumorph", "soft", "shadow"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: plexSans, mono: monoStack, display: plexSans },
    tokens: {
      desktop: "#e0e5ec",
      surface: "#e0e5ec",
      surfaceAlt: "#e0e5ec",
      text: "#4a5568",
      textMuted: "#8a94a6",
      accent: "#6c8cff",
      accentHover: "#8aa4ff",
      titlebarBg: "#e0e5ec",
      titlebarText: "#4a5568",
      titlebarInactiveBg: "#e0e5ec",
      titlebarInactiveText: "#8a94a6",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#a3b1c6",
      borderLow: "#a3b1c6",
      fieldBg: "#e0e5ec",
      selectionBg: "#6c8cff",
      selectionText: "#ffffff",
      focus: "#6c8cff",
      controlBg: "#e0e5ec",
      controlBgHover: "#e8edf4",
      controlBgActive: "#d4dbe6",
      controlBgPrimary: "#e0e5ec",
      controlTextPrimary: "#6c8cff",
      shadowOutset: "8px 8px 16px #a3b1c6, -8px -8px 16px #ffffff",
      shadowInset: "inset 6px 6px 12px #a3b1c6, inset -6px -6px 12px #ffffff",
      shadowWindow: "12px 12px 24px #a3b1c6, -12px -12px 24px #ffffff",
      radius: "18px",
      radiusWindow: "24px",
      radiusControl: "14px",
      borderWidth: "0px",
      fontSize: "14px",
      controlHeight: "40px",
      titlebarHeight: "48px",
    },
  }),
  defineTheme({
    id: "claymorphism",
    slug: "claymorphism",
    name: "Claymorphism",
    year: 2021,
    era: "Web/UI",
    description: "Squishy 3D clay chunks, inner glow, pastel fills, playful radii.",
    tags: ["clay", "3d", "playful"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: plexSans, mono: monoStack, display: plexSans },
    tokens: {
      desktop: "#f0e9ff",
      surface: "#f7f2ff",
      surfaceAlt: "#ffe8f4",
      text: "#3a2e5c",
      textMuted: "#7c6ba8",
      accent: "#c9a8ff",
      accentHover: "#ffb3d1",
      titlebarBg: "linear-gradient(#ffe8f4, #c9a8ff)",
      titlebarText: "#3a2e5c",
      titlebarInactiveBg: "#f0e9ff",
      titlebarInactiveText: "#7c6ba8",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#c9a8ff",
      borderLow: "#7c6ba8",
      fieldBg: "#ffffff",
      selectionBg: "#c9a8ff",
      selectionText: "#3a2e5c",
      focus: "#ffb3d1",
      danger: "#ff8aa0",
      success: "#a8f0d0",
      warning: "#ffe58a",
      controlBg: "linear-gradient(#ffffff, #e8d9ff)",
      controlBgHover: "linear-gradient(#ffffff, #ffe8f4)",
      controlBgActive: "#e8d9ff",
      controlBgPrimary: "linear-gradient(#ffd0e8, #c9a8ff)",
      controlTextPrimary: "#3a2e5c",
      shadowOutset: "inset 0 -8px 16px rgba(122,90,180,0.18), 0 12px 0 #c9a8ff",
      shadowInset: "inset 0 8px 16px rgba(122,90,180,0.12)",
      shadowWindow: "0 18px 0 #c9a8ff, 0 28px 40px rgba(58,46,92,0.18)",
      radius: "28px",
      radiusWindow: "32px",
      radiusControl: "22px",
      borderWidth: "3px",
      fontSize: "14px",
      controlHeight: "40px",
      titlebarHeight: "44px",
    },
  }),
  defineTheme({
    id: "brutalist-web",
    slug: "brutalist-web",
    name: "Brutalist Web",
    year: 2016,
    era: "Web/UI",
    description: "Raw HTML attitude: system fonts, thick rules, default-link blue, no decoration.",
    tags: ["brutalist", "raw", "highcontrast"],
    engine: "web",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#ffffff",
      surface: "#ffffff",
      surfaceAlt: "#f0f0f0",
      text: "#000000",
      textMuted: "#333333",
      accent: "#0000ee",
      accentHover: "#551a8b",
      titlebarBg: "#000000",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#c0c0c0",
      titlebarInactiveText: "#000000",
      borderHigh: "#000000",
      borderLight: "#000000",
      borderDark: "#000000",
      borderLow: "#000000",
      fieldBg: "#ffffff",
      selectionBg: "#000000",
      selectionText: "#ffffff",
      focus: "#ff0000",
      danger: "#ff0000",
      success: "#008000",
      warning: "#000000",
      controlBg: "#ffffff",
      controlBgHover: "#f0f0f0",
      controlBgActive: "#e0e0e0",
      controlBgPrimary: "#000000",
      controlTextPrimary: "#ffffff",
      shadowOutset: "6px 6px 0 #000000",
      shadowInset: "inset 0 0 0 2px #000000",
      shadowWindow: "10px 10px 0 #000000",
      radius: "0px",
      borderWidth: "3px",
      fontSize: "16px",
      controlHeight: "40px",
      titlebarHeight: "40px",
    },
  }),
  defineTheme({
    id: "default-browser",
    slug: "default-browser",
    name: "Default Browser",
    year: 1994,
    era: "Web",
    description: "Unstyled user-agent: Times, blue links, purple visited, and native form widgets.",
    tags: ["html", "unstyled", "ua"],
    engine: "web",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: serifStack, mono: `"Courier New", Courier, monospace`, display: serifStack },
    tokens: {
      desktop: "#ffffff",
      surface: "#ffffff",
      surfaceAlt: "#ffffff",
      text: "#000000",
      textMuted: "#000000",
      accent: "#0000ee",
      accentHover: "#551a8b",
      titlebarBg: "#ffffff",
      titlebarText: "#000000",
      titlebarInactiveBg: "#ffffff",
      titlebarInactiveText: "#000000",
      borderHigh: "#808080",
      borderLight: "#808080",
      borderDark: "#808080",
      borderLow: "#808080",
      fieldBg: "#ffffff",
      selectionBg: "#316ac5",
      selectionText: "#ffffff",
      focus: "#000000",
      danger: "#000000",
      success: "#000000",
      warning: "#000000",
      controlBg: "#efefef",
      controlBgHover: "#e0e0e0",
      controlBgActive: "#d0d0d0",
      controlBgPrimary: "#efefef",
      controlTextPrimary: "#000000",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "none",
      radius: "0px",
      borderWidth: "2px",
      fontSize: "16px",
      controlHeight: "auto",
      titlebarHeight: "auto",
      lineHeight: "1.4",
    },
  }),
  defineTheme({
    id: "y2k-chrome",
    slug: "y2k-chrome",
    name: "Y2K Chrome",
    year: 2000,
    era: "Aesthetic",
    description: "Bubble metal, iridescent gradients, pink gloss, and millennium orb buttons.",
    tags: ["y2k", "chrome", "bubble"],
    engine: "soft",
    controls: "none",
    desktopPattern: "horizon",
    fonts: { ui: lucidaStack, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#d7f0ff",
      surface: "linear-gradient(#ffffff, #e8d9ff)",
      surfaceAlt: "#ffccee",
      text: "#202030",
      textMuted: "#5a6478",
      accent: "#ff6ab8",
      accentHover: "#ff8fd0",
      titlebarBg: "linear-gradient(90deg, #d7f0ff, #ffccee, #e8d9ff)",
      titlebarText: "#202030",
      titlebarInactiveBg: "#e8d9ff",
      titlebarInactiveText: "#5a6478",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#b8c4d8",
      borderLow: "#ff6ab8",
      fieldBg: "#ffffff",
      selectionBg: "#ff6ab8",
      selectionText: "#ffffff",
      focus: "#5a9fff",
      controlBg: "linear-gradient(#ffffff, #c8d4e8 50%, #f0f4ff)",
      controlBgHover: "linear-gradient(#ffffff, #ffe0f4)",
      controlBgActive: "#e8d9ff",
      controlBgPrimary: "linear-gradient(#ffffff, #ff6ab8 55%, #c04090)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 6px 16px rgba(255,106,184,0.28)",
      shadowInset: "inset 0 2px 6px rgba(90,100,120,0.2)",
      shadowWindow: "0 16px 40px rgba(90,100,120,0.25)",
      radius: "16px",
      radiusWindow: "20px",
      radiusControl: "999px",
      borderWidth: "2px",
      fontSize: "13px",
      controlHeight: "32px",
      titlebarHeight: "32px",
    },
  }),
  defineTheme({
    id: "maximalist-banners",
    slug: "maximalist-banners",
    name: "Maximalist 90s Banner",
    year: 1997,
    era: "Web",
    description: "Too many marquees, colliding primaries, beveled GIF buttons, and banner-ad density.",
    tags: ["maximalist", "banner", "90s"],
    engine: "web",
    controls: "none",
    desktopPattern: "checker",
    fonts: { ui: displayStack, mono: comicStack, display: displayStack },
    tokens: {
      desktop: "#ff00ff",
      surface: "#ffff00",
      surfaceAlt: "#00ffff",
      text: "#000000",
      textMuted: "#0000aa",
      accent: "#ff0000",
      accentHover: "#aa0000",
      titlebarBg: "linear-gradient(90deg, #ff0000, #ffff00, #00ff00, #00ffff, #0000ff, #ff00ff)",
      titlebarText: "#000000",
      titlebarInactiveBg: "#000000",
      titlebarInactiveText: "#ffff00",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#000000",
      borderLow: "#000000",
      fieldBg: "#ffffff",
      selectionBg: "#0000ff",
      selectionText: "#ffff00",
      focus: "#ff0000",
      danger: "#ff0000",
      success: "#00aa00",
      warning: "#ffff00",
      controlBg: "#00ffff",
      controlBgHover: "#ffff00",
      controlBgActive: "#ff00ff",
      controlBgPrimary: "#ff0000",
      controlTextPrimary: "#ffffff",
      shadowOutset: "4px 4px 0 #000000",
      shadowInset: "inset 2px 2px 0 #ffffff",
      shadowWindow: "8px 8px 0 #0000ff",
      radius: "0px",
      borderWidth: "5px",
      fontSize: "16px",
      controlHeight: "36px",
      titlebarHeight: "36px",
      letterSpacing: "0.04em",
    },
  }),
];
