import {
  defineTheme,
  comicStack,
  displayStack,
  helveticaStack,
  lucidaStack,
  monoStack,
  plexSans,
  serifStack,
  tahomaStack,
  verdanaStack,
} from "./helpers";
import type { RetroTheme } from "./types";

export const webUiThemes: RetroTheme[] = [
  defineTheme({
    id: "geocities-web10",
    slug: "geocities-web10",
    name: "GeoCities Web 1.0",
    year: 1996,
    era: "Web",
    description: "Tiled stars, visitor counters, hot-pink links, and construction-gif energy.",
    tags: ["web1.0", "kitsch", "tiled"],
    engine: "web",
    controls: "none",
    desktopPattern: "stars",
    fonts: { ui: comicStack, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#000000",
      surface: "#000080",
      surfaceAlt: "#000000",
      text: "#ffff00",
      textMuted: "#00ffff",
      accent: "#ff3399",
      accentHover: "#ff66b3",
      titlebarBg: "linear-gradient(90deg, #ff00ff, #00ffff, #ffff00)",
      titlebarText: "#000000",
      titlebarInactiveBg: "#000000",
      titlebarInactiveText: "#ff00ff",
      borderHigh: "#ffffff",
      borderLight: "#00ffff",
      borderDark: "#ff00ff",
      borderLow: "#ffff00",
      fieldBg: "#ffffff",
      fieldText: "#000000",
      selectionBg: "#ff3399",
      selectionText: "#ffffff",
      focus: "#00ff00",
      danger: "#ff0000",
      success: "#00ff00",
      warning: "#ffff00",
      disabled: "#000080",
      disabledText: "#808080",
      controlBg: "#c0c0c0",
      controlBgHover: "#dfdfdf",
      controlBgActive: "#808080",
      controlBgPrimary: "#ff3399",
      controlTextPrimary: "#ffffff",
      shadowOutset: "4px 4px 0 #ff00ff",
      shadowInset: "inset 2px 2px 0 #000000",
      shadowWindow: "8px 8px 0 #00ffff",
      radius: "0px",
      borderWidth: "4px",
      fontSize: "15px",
      controlHeight: "28px",
      titlebarHeight: "28px",
    },
  }),
  defineTheme({
    id: "web20-glossy",
    slug: "web20-glossy",
    name: "Web 2.0 Glossy",
    year: 2005,
    era: "Web/UI",
    description: "Candy buttons, specular reflections, Aqua-adjacent badges, and friendly blue.",
    tags: ["web2.0", "glossy", "reflection"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: lucidaStack, mono: monoStack, display: lucidaStack },
    tokens: {
      desktop: "#dce8f4",
      surface: "#ffffff",
      surfaceAlt: "#e8f0f7",
      text: "#1e3a5c",
      textMuted: "#5a7a9c",
      accent: "#2a7ac9",
      accentHover: "#62a8e8",
      titlebarBg: "linear-gradient(#62a8e8, #1e5a9c)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "linear-gradient(#c8d8e8, #8aa0b4)",
      titlebarInactiveText: "#e8f0f7",
      borderHigh: "#ffffff",
      borderLight: "#d4e8f7",
      borderDark: "#7aa8d0",
      borderLow: "#1e5a9c",
      fieldBg: "#ffffff",
      selectionBg: "#2a7ac9",
      selectionText: "#ffffff",
      focus: "#ff8c1a",
      controlBg: "linear-gradient(#ffffff, #d4e8f7)",
      controlBgHover: "linear-gradient(#ffffff, #eaf4fc)",
      controlBgActive: "#d4e8f7",
      controlBgPrimary: "linear-gradient(#ffc04a, #ff8c1a 50%, #e07000)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 2px 0 #7aa8d0, 0 8px 16px rgba(30,90,156,0.18)",
      shadowInset: "inset 0 2px 4px rgba(30,90,156,0.15)",
      shadowWindow: "0 12px 32px rgba(30,90,156,0.22)",
      radius: "12px",
      radiusWindow: "12px",
      radiusControl: "18px",
      borderWidth: "1px",
      fontSize: "14px",
      controlHeight: "32px",
      titlebarHeight: "36px",
    },
  }),
  defineTheme({
    id: "frutiger-aero",
    slug: "frutiger-aero",
    name: "Frutiger Aero",
    year: 2007,
    era: "Web/UI",
    description: "Sky glass, dewdrop orbs, nature stock, and optimistic aqua-green UI.",
    tags: ["aero", "nature", "glass"],
    engine: "aero",
    controls: "none",
    desktopPattern: "horizon",
    fonts: { ui: plexSans, mono: monoStack, display: plexSans },
    tokens: {
      desktop: "#7fcfff",
      surface: "rgba(255,255,255,0.72)",
      surfaceAlt: "rgba(199,240,255,0.65)",
      text: "#0b2a3c",
      textMuted: "#3a6a80",
      accent: "#0ea5ff",
      accentHover: "#3dd36b",
      titlebarBg: "linear-gradient(rgba(255,255,255,0.7), rgba(127,207,255,0.35))",
      titlebarText: "#0b2a3c",
      titlebarInactiveBg: "rgba(255,255,255,0.35)",
      titlebarInactiveText: "#3a6a80",
      borderHigh: "rgba(255,255,255,0.9)",
      borderLight: "rgba(255,255,255,0.7)",
      borderDark: "rgba(14,165,255,0.35)",
      borderLow: "rgba(11,42,60,0.2)",
      fieldBg: "rgba(255,255,255,0.85)",
      selectionBg: "#0ea5ff",
      selectionText: "#ffffff",
      focus: "#3dd36b",
      danger: "#ff5d7a",
      success: "#3dd36b",
      warning: "#ffd36b",
      controlBg: "linear-gradient(#ffffff, #c7f0ff)",
      controlBgHover: "linear-gradient(#ffffff, #e8fbff)",
      controlBgActive: "#c7f0ff",
      controlBgPrimary: "linear-gradient(#8ef0a8, #3dd36b)",
      controlTextPrimary: "#0b2a3c",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 8px 24px rgba(14,165,255,0.25)",
      shadowInset: "inset 0 1px 3px rgba(11,42,60,0.12)",
      shadowWindow: "0 18px 40px rgba(14,165,255,0.28)",
      radius: "16px",
      radiusWindow: "18px",
      radiusControl: "999px",
      borderWidth: "1px",
      fontSize: "14px",
      controlHeight: "32px",
      titlebarHeight: "36px",
    },
  }),
  defineTheme({
    id: "flat-2013",
    slug: "flat-2013",
    name: "Flat Design 2013",
    year: 2013,
    era: "Web/UI",
    description: "iOS 7 / Metro-era flats: bright tiles, no bevels, and generous whitespace.",
    tags: ["flat", "ios7", "metro"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: plexSans, mono: monoStack, display: plexSans },
    tokens: {
      desktop: "#ecf0f1",
      surface: "#ffffff",
      surfaceAlt: "#ecf0f1",
      text: "#34495e",
      textMuted: "#7f8c8d",
      accent: "#3498db",
      accentHover: "#5dade2",
      titlebarBg: "#3498db",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#95a5a6",
      titlebarInactiveText: "#ffffff",
      borderHigh: "#ecf0f1",
      borderLight: "#ecf0f1",
      borderDark: "#bdc3c7",
      borderLow: "#bdc3c7",
      fieldBg: "#ffffff",
      selectionBg: "#3498db",
      selectionText: "#ffffff",
      focus: "#1abc9c",
      danger: "#e74c3c",
      success: "#2ecc71",
      warning: "#f1c40f",
      controlBg: "#ecf0f1",
      controlBgHover: "#dfe6e9",
      controlBgActive: "#bdc3c7",
      controlBgPrimary: "#3498db",
      controlTextPrimary: "#ffffff",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "0 8px 24px rgba(52,73,94,0.12)",
      radius: "4px",
      radiusWindow: "4px",
      radiusControl: "4px",
      borderWidth: "0px",
      fontSize: "14px",
      controlHeight: "36px",
      titlebarHeight: "48px",
    },
  }),
  defineTheme({
    id: "glassmorphism",
    slug: "glassmorphism",
    name: "Glassmorphism",
    year: 2020,
    era: "Web/UI",
    description: "Frosted panels, vivid blobs behind blur, thin luminous strokes.",
    tags: ["glass", "blur", "frosted"],
    engine: "aero",
    controls: "none",
    desktopPattern: "horizon",
    fonts: { ui: plexSans, mono: monoStack, display: plexSans },
    tokens: {
      desktop: "#1a1030",
      surface: "rgba(255,255,255,0.12)",
      surfaceAlt: "rgba(255,255,255,0.08)",
      text: "#f8f8ff",
      textMuted: "#c8c0e0",
      accent: "#ff6ec4",
      accentHover: "#7873f5",
      titlebarBg: "rgba(255,255,255,0.08)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "rgba(255,255,255,0.04)",
      titlebarInactiveText: "#c8c0e0",
      borderHigh: "rgba(255,255,255,0.45)",
      borderLight: "rgba(255,255,255,0.28)",
      borderDark: "rgba(255,255,255,0.12)",
      borderLow: "rgba(255,110,196,0.45)",
      fieldBg: "rgba(0,0,0,0.25)",
      fieldText: "#ffffff",
      selectionBg: "#7873f5",
      selectionText: "#ffffff",
      focus: "#ff6ec4",
      danger: "#ff6b8a",
      success: "#5ef0c0",
      warning: "#ffd36b",
      disabled: "rgba(255,255,255,0.06)",
      disabledText: "#8a82a8",
      controlBg: "rgba(255,255,255,0.12)",
      controlBgHover: "rgba(255,255,255,0.2)",
      controlBgActive: "rgba(255,255,255,0.08)",
      controlBgPrimary: "linear-gradient(90deg, #ff6ec4, #7873f5)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 rgba(255,255,255,0.35)",
      shadowInset: "inset 0 0 0 1px rgba(255,255,255,0.12)",
      shadowWindow: "0 20px 50px rgba(0,0,0,0.35)",
      radius: "20px",
      radiusWindow: "24px",
      radiusControl: "14px",
      borderWidth: "1px",
      fontSize: "14px",
      controlHeight: "36px",
      titlebarHeight: "40px",
    },
  }),
  defineTheme({
    id: "neumorphism",
    slug: "neumorphism",
    name: "Neumorphism",
    year: 2020,
    era: "Web/UI",
    description: "Soft extruded UI: same-hue lights and shadows, pill controls, low contrast.",
    tags: ["neumorph", "soft", "shadow"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: plexSans, mono: monoStack, display: plexSans },
    tokens: {
      desktop: "#e0e5ec",
      surface: "#e0e5ec",
      surfaceAlt: "#e0e5ec",
      text: "#4a5568",
      textMuted: "#8a94a6",
      accent: "#6c8cff",
      accentHover: "#8aa4ff",
      titlebarBg: "#e0e5ec",
      titlebarText: "#4a5568",
      titlebarInactiveBg: "#e0e5ec",
      titlebarInactiveText: "#8a94a6",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#a3b1c6",
      borderLow: "#a3b1c6",
      fieldBg: "#e0e5ec",
      selectionBg: "#6c8cff",
      selectionText: "#ffffff",
      focus: "#6c8cff",
      controlBg: "#e0e5ec",
      controlBgHover: "#e8edf4",
      controlBgActive: "#d4dbe6",
      controlBgPrimary: "#e0e5ec",
      controlTextPrimary: "#6c8cff",
      shadowOutset: "8px 8px 16px #a3b1c6, -8px -8px 16px #ffffff",
      shadowInset: "inset 6px 6px 12px #a3b1c6, inset -6px -6px 12px #ffffff",
      shadowWindow: "12px 12px 24px #a3b1c6, -12px -12px 24px #ffffff",
      radius: "18px",
      radiusWindow: "24px",
      radiusControl: "14px",
      borderWidth: "0px",
      fontSize: "14px",
      controlHeight: "40px",
      titlebarHeight: "48px",
    },
  }),
  defineTheme({
    id: "claymorphism",
    slug: "claymorphism",
    name: "Claymorphism",
    year: 2021,
    era: "Web/UI",
    description: "Squishy 3D clay chunks, inner glow, pastel fills, playful radii.",
    tags: ["clay", "3d", "playful"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: plexSans, mono: monoStack, display: plexSans },
    tokens: {
      desktop: "#f0e9ff",
      surface: "#f7f2ff",
      surfaceAlt: "#ffe8f4",
      text: "#3a2e5c",
      textMuted: "#7c6ba8",
      accent: "#c9a8ff",
      accentHover: "#ffb3d1",
      titlebarBg: "linear-gradient(#ffe8f4, #c9a8ff)",
      titlebarText: "#3a2e5c",
      titlebarInactiveBg: "#f0e9ff",
      titlebarInactiveText: "#7c6ba8",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#c9a8ff",
      borderLow: "#7c6ba8",
      fieldBg: "#ffffff",
      selectionBg: "#c9a8ff",
      selectionText: "#3a2e5c",
      focus: "#ffb3d1",
      danger: "#ff8aa0",
      success: "#a8f0d0",
      warning: "#ffe58a",
      controlBg: "linear-gradient(#ffffff, #e8d9ff)",
      controlBgHover: "linear-gradient(#ffffff, #ffe8f4)",
      controlBgActive: "#e8d9ff",
      controlBgPrimary: "linear-gradient(#ffd0e8, #c9a8ff)",
      controlTextPrimary: "#3a2e5c",
      shadowOutset: "inset 0 -8px 16px rgba(122,90,180,0.18), 0 12px 0 #c9a8ff",
      shadowInset: "inset 0 8px 16px rgba(122,90,180,0.12)",
      shadowWindow: "0 18px 0 #c9a8ff, 0 28px 40px rgba(58,46,92,0.18)",
      radius: "28px",
      radiusWindow: "32px",
      radiusControl: "22px",
      borderWidth: "3px",
      fontSize: "14px",
      controlHeight: "40px",
      titlebarHeight: "44px",
    },
  }),
  defineTheme({
    id: "brutalist-web",
    slug: "brutalist-web",
    name: "Brutalist Web",
    year: 2016,
    era: "Web/UI",
    description: "Raw HTML attitude: system fonts, thick rules, default-link blue, no decoration.",
    tags: ["brutalist", "raw", "highcontrast"],
    engine: "web",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#ffffff",
      surface: "#ffffff",
      surfaceAlt: "#f0f0f0",
      text: "#000000",
      textMuted: "#333333",
      accent: "#0000ee",
      accentHover: "#551a8b",
      titlebarBg: "#000000",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#c0c0c0",
      titlebarInactiveText: "#000000",
      borderHigh: "#000000",
      borderLight: "#000000",
      borderDark: "#000000",
      borderLow: "#000000",
      fieldBg: "#ffffff",
      selectionBg: "#000000",
      selectionText: "#ffffff",
      focus: "#ff0000",
      danger: "#ff0000",
      success: "#008000",
      warning: "#000000",
      controlBg: "#ffffff",
      controlBgHover: "#f0f0f0",
      controlBgActive: "#e0e0e0",
      controlBgPrimary: "#000000",
      controlTextPrimary: "#ffffff",
      shadowOutset: "6px 6px 0 #000000",
      shadowInset: "inset 0 0 0 2px #000000",
      shadowWindow: "10px 10px 0 #000000",
      radius: "0px",
      borderWidth: "3px",
      fontSize: "16px",
      controlHeight: "40px",
      titlebarHeight: "40px",
    },
  }),
  defineTheme({
    id: "default-browser",
    slug: "default-browser",
    name: "Default Browser",
    year: 1994,
    era: "Web",
    description: "Unstyled user-agent: Times, blue links, purple visited, and native form widgets.",
    tags: ["html", "unstyled", "ua"],
    engine: "web",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: serifStack, mono: `"Courier New", Courier, monospace`, display: serifStack },
    tokens: {
      desktop: "#ffffff",
      surface: "#ffffff",
      surfaceAlt: "#ffffff",
      text: "#000000",
      textMuted: "#000000",
      accent: "#0000ee",
      accentHover: "#551a8b",
      titlebarBg: "#ffffff",
      titlebarText: "#000000",
      titlebarInactiveBg: "#ffffff",
      titlebarInactiveText: "#000000",
      borderHigh: "#808080",
      borderLight: "#808080",
      borderDark: "#808080",
      borderLow: "#808080",
      fieldBg: "#ffffff",
      selectionBg: "#316ac5",
      selectionText: "#ffffff",
      focus: "#000000",
      danger: "#000000",
      success: "#000000",
      warning: "#000000",
      controlBg: "#efefef",
      controlBgHover: "#e0e0e0",
      controlBgActive: "#d0d0d0",
      controlBgPrimary: "#efefef",
      controlTextPrimary: "#000000",
      shadowOutset: "none",
      shadowInset: "none",
      shadowWindow: "none",
      radius: "0px",
      borderWidth: "2px",
      fontSize: "16px",
      controlHeight: "auto",
      titlebarHeight: "auto",
      lineHeight: "1.4",
    },
  }),
  defineTheme({
    id: "y2k-chrome",
    slug: "y2k-chrome",
    name: "Y2K Chrome",
    year: 2000,
    era: "Aesthetic",
    description: "Bubble metal, iridescent gradients, pink gloss, and millennium orb buttons.",
    tags: ["y2k", "chrome", "bubble"],
    engine: "soft",
    controls: "none",
    desktopPattern: "horizon",
    fonts: { ui: lucidaStack, mono: monoStack, display: displayStack },
    tokens: {
      desktop: "#d7f0ff",
      surface: "linear-gradient(#ffffff, #e8d9ff)",
      surfaceAlt: "#ffccee",
      text: "#202030",
      textMuted: "#5a6478",
      accent: "#ff6ab8",
      accentHover: "#ff8fd0",
      titlebarBg: "linear-gradient(90deg, #d7f0ff, #ffccee, #e8d9ff)",
      titlebarText: "#202030",
      titlebarInactiveBg: "#e8d9ff",
      titlebarInactiveText: "#5a6478",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#b8c4d8",
      borderLow: "#ff6ab8",
      fieldBg: "#ffffff",
      selectionBg: "#ff6ab8",
      selectionText: "#ffffff",
      focus: "#5a9fff",
      controlBg: "linear-gradient(#ffffff, #c8d4e8 50%, #f0f4ff)",
      controlBgHover: "linear-gradient(#ffffff, #ffe0f4)",
      controlBgActive: "#e8d9ff",
      controlBgPrimary: "linear-gradient(#ffffff, #ff6ab8 55%, #c04090)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 6px 16px rgba(255,106,184,0.28)",
      shadowInset: "inset 0 2px 6px rgba(90,100,120,0.2)",
      shadowWindow: "0 16px 40px rgba(90,100,120,0.25)",
      radius: "16px",
      radiusWindow: "20px",
      radiusControl: "999px",
      borderWidth: "2px",
      fontSize: "13px",
      controlHeight: "32px",
      titlebarHeight: "32px",
    },
  }),
  defineTheme({
    id: "maximalist-banners",
    slug: "maximalist-banners",
    name: "Maximalist 90s Banner",
    year: 1997,
    era: "Web",
    description: "Too many marquees, colliding primaries, beveled GIF buttons, and banner-ad density.",
    tags: ["maximalist", "banner", "90s"],
    engine: "web",
    controls: "none",
    desktopPattern: "checker",
    fonts: { ui: displayStack, mono: comicStack, display: displayStack },
    tokens: {
      desktop: "#ff00ff",
      surface: "#ffff00",
      surfaceAlt: "#00ffff",
      text: "#000000",
      textMuted: "#0000aa",
      accent: "#ff0000",
      accentHover: "#aa0000",
      titlebarBg: "linear-gradient(90deg, #ff0000, #ffff00, #00ff00, #00ffff, #0000ff, #ff00ff)",
      titlebarText: "#000000",
      titlebarInactiveBg: "#000000",
      titlebarInactiveText: "#ffff00",
      borderHigh: "#ffffff",
      borderLight: "#ffffff",
      borderDark: "#000000",
      borderLow: "#000000",
      fieldBg: "#ffffff",
      selectionBg: "#0000ff",
      selectionText: "#ffff00",
      focus: "#ff0000",
      danger: "#ff0000",
      success: "#00aa00",
      warning: "#ffff00",
      controlBg: "#00ffff",
      controlBgHover: "#ffff00",
      controlBgActive: "#ff00ff",
      controlBgPrimary: "#ff0000",
      controlTextPrimary: "#ffffff",
      shadowOutset: "4px 4px 0 #000000",
      shadowInset: "inset 2px 2px 0 #ffffff",
      shadowWindow: "8px 8px 0 #0000ff",
      radius: "0px",
      borderWidth: "5px",
      fontSize: "16px",
      controlHeight: "36px",
      titlebarHeight: "36px",
      letterSpacing: "0.04em",
    },
  }),

  defineTheme({
    id: "msn-messenger",
    slug: "msn-messenger",
    name: "MSN Messenger",
    year: 1999,
    era: "App",
    description:
      "Butterfly-era chat: soft blue gradients, glossy toolbar chrome, and the buddy list that ruled 2003.",
    tags: ["msn", "chat", "messenger", "glossy"],
    engine: "graphic",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: tahomaStack, mono: monoStack, display: plexSans },
    tokens: {
      desktop: "linear-gradient(180deg, #7ab3d9, #cfe3f2)",
      surface: "#f4f8fc",
      surfaceAlt: "#e4eef6",
      text: "#0a3d62",
      textMuted: "#5a7a94",
      textOnAccent: "#ffffff",
      accent: "#0066cc",
      accentHover: "#1a7ee0",
      titlebarBg: "linear-gradient(#5a9fd4, #2a6ea8)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#c4d4e0",
      titlebarInactiveText: "#5a7a94",
      borderHigh: "#ffffff",
      borderLight: "#d8e4ec",
      borderDark: "#8aa8bc",
      borderLow: "#5a7a94",
      fieldBg: "#ffffff",
      fieldText: "#0a3d62",
      selectionBg: "#0066cc",
      selectionText: "#ffffff",
      focus: "#0066cc",
      danger: "#c0392b",
      success: "#2e8b3a",
      warning: "#d39c2a",
      disabled: "#e4eef6",
      disabledText: "#8aa8bc",
      controlBg: "linear-gradient(#f0f6fa, #d0e0ec)",
      controlBgHover: "linear-gradient(#f8fcfe, #dcebf4)",
      controlBgActive: "#c0d4e2",
      controlBgPrimary: "linear-gradient(#7ab8e8, #2a6ea8)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 2px rgba(0, 0, 0, 0.12)",
      shadowInset: "inset 0 1px 2px rgba(0, 0, 0, 0.08)",
      shadowWindow: "0 8px 24px rgba(10, 61, 98, 0.25)",
      radius: "6px",
      radiusWindow: "8px",
      radiusControl: "6px",
      borderWidth: "1px",
      fontSize: "12px",
      lineHeight: "1.4",
      controlHeight: "26px",
      titlebarHeight: "28px",
      space: "10px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "aim",
    slug: "aim",
    name: "AIM",
    year: 1997,
    era: "App",
    description:
      "Running-man era: pale yellow buddy window, glossy blue title bars, and away messages as an art form.",
    tags: ["aim", "aol", "chat", "buddy-list"],
    engine: "graphic",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: tahomaStack, mono: monoStack, display: plexSans },
    tokens: {
      desktop: "#f5f3e4",
      surface: "#ffffff",
      surfaceAlt: "#f0eddc",
      text: "#1a1a3a",
      textMuted: "#6a6a8a",
      textOnAccent: "#ffffff",
      accent: "#2f5fd0",
      accentHover: "#4a78e0",
      titlebarBg: "linear-gradient(#8ab0f0, #3a6ad0)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#c8c8d8",
      titlebarInactiveText: "#6a6a8a",
      borderHigh: "#ffffff",
      borderLight: "#e4e4ee",
      borderDark: "#9a9ab4",
      borderLow: "#6a6a8a",
      fieldBg: "#ffffff",
      fieldText: "#1a1a3a",
      selectionBg: "#2f5fd0",
      selectionText: "#ffffff",
      focus: "#2f5fd0",
      danger: "#c0392b",
      success: "#2e8b3a",
      warning: "#e0a030",
      disabled: "#f0eddc",
      disabledText: "#9a9ab4",
      controlBg: "linear-gradient(#f8f8fc, #dcdce8)",
      controlBgHover: "linear-gradient(#ffffff, #e8e8f2)",
      controlBgActive: "#c8c8d8",
      controlBgPrimary: "linear-gradient(#6a92e8, #2f5fd0)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 2px rgba(0, 0, 0, 0.1)",
      shadowInset: "inset 0 1px 2px rgba(0, 0, 0, 0.08)",
      shadowWindow: "0 8px 22px rgba(26, 26, 58, 0.22)",
      radius: "6px",
      radiusWindow: "8px",
      radiusControl: "6px",
      borderWidth: "1px",
      fontSize: "12px",
      lineHeight: "1.4",
      controlHeight: "26px",
      titlebarHeight: "28px",
      space: "10px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "mirc",
    slug: "mirc",
    name: "mIRC",
    year: 1995,
    era: "App",
    description:
      "Classic IRC: navy caption bars, white channel buffers, green join/part noise, and the switchbar.",
    tags: ["irc", "mirc", "chat", "90s"],
    engine: "bevel",
    controls: "win",
    desktopPattern: "none",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {
      desktop: "#4a6a8a",
      surface: "#c0c0c0",
      surfaceAlt: "#d4d0c8",
      text: "#000000",
      textMuted: "#404040",
      textOnAccent: "#ffffff",
      accent: "#000080",
      accentHover: "#0000a0",
      titlebarBg: "#000080",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#808080",
      titlebarInactiveText: "#c0c0c0",
      borderHigh: "#ffffff",
      borderLight: "#dfdfdf",
      borderDark: "#808080",
      borderLow: "#000000",
      fieldBg: "#ffffff",
      fieldText: "#000000",
      selectionBg: "#000080",
      selectionText: "#ffffff",
      focus: "#000080",
      danger: "#800000",
      success: "#008040",
      warning: "#808000",
      disabled: "#c0c0c0",
      disabledText: "#808080",
      controlBg: "#c0c0c0",
      controlBgHover: "#dfdfdf",
      controlBgActive: "#a8a8a8",
      controlBgPrimary: "#000080",
      controlTextPrimary: "#ffffff",
      shadowOutset:
        "inset -1px -1px #000000, inset 1px 1px #ffffff, inset -2px -2px #808080, inset 2px 2px #dfdfdf",
      shadowInset:
        "inset -1px -1px #ffffff, inset 1px 1px #000000, inset -2px -2px #dfdfdf, inset 2px 2px #808080",
      shadowWindow: "2px 2px 0 rgba(0, 0, 0, 0.4)",
      fontSize: "12px",
      controlHeight: "23px",
      titlebarHeight: "20px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "ios-6",
    era: "Mobile",
    slug: "ios-6",
    name: "iOS 6",
    year: 2012,
    description:
      "Peak skeuomorphic iPhone: striped blue-gray nav bars, linen backgrounds, glossy gel buttons, stitched detail.",
    tags: ["apple", "iphone", "skeuomorphic", "linen"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "linear-gradient(180deg, #1a2a4a, #3a5a8c)",
      surface: "#e2e3e8",
      surfaceAlt: "#ffffff",
      text: "#000000",
      textMuted: "#7c8696",
      textOnAccent: "#ffffff",
      accent: "#0a67d2",
      accentHover: "#2a83e8",
      titlebarBg: "linear-gradient(#a8b4c8, #6a7e9a)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#d0d4dc",
      titlebarInactiveText: "#7c8696",
      borderHigh: "#ffffff",
      borderLight: "#e8e8ee",
      borderDark: "#a8b0be",
      borderLow: "#7c8696",
      fieldBg: "#ffffff",
      fieldText: "#000000",
      selectionBg: "#3a80d8",
      selectionText: "#ffffff",
      focus: "#0a67d2",
      danger: "#d04030",
      success: "#4a9a50",
      warning: "#d9a03c",
      disabled: "#e0e0e6",
      disabledText: "#a8b0be",
      controlBg: "linear-gradient(#fdfdfd, #c8ccd4)",
      controlBgHover: "linear-gradient(#ffffff, #d6dae2)",
      controlBgActive: "#b0b6c0",
      controlBgPrimary: "linear-gradient(#5a9ae8, #1a5cb0)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 rgba(255, 255, 255, 0.9), 0 1px 2px rgba(0, 0, 0, 0.15)",
      shadowInset: "inset 0 2px 4px rgba(0, 0, 0, 0.12)",
      shadowWindow: "0 12px 32px rgba(0, 0, 0, 0.35)",
      radius: "6px",
      radiusWindow: "8px",
      radiusControl: "6px",
      borderWidth: "1px",
      fontSize: "13px",
      lineHeight: "1.4",
      controlHeight: "32px",
      titlebarHeight: "38px",
      space: "10px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "ios-7",
    era: "Mobile",
    slug: "ios-7",
    name: "iOS 7 Flat",
    year: 2013,
    description:
      "The great flattening: white panes, hairline separators, ultra-light type, and #007aff links everywhere.",
    tags: ["apple", "iphone", "flat", "jony-ive"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: "HelveticaNeue-Light, Helvetica, Arial, sans-serif" },
    tokens: {
      desktop: "linear-gradient(180deg, #f8f8fa, #dcdce2)",
      surface: "#ffffff",
      surfaceAlt: "#f2f2f4",
      text: "#000000",
      textMuted: "#8e8e93",
      textOnAccent: "#ffffff",
      accent: "#007aff",
      accentHover: "#3395ff",
      titlebarBg: "rgba(249, 249, 251, 0.94)",
      titlebarText: "#000000",
      titlebarInactiveBg: "#f2f2f4",
      titlebarInactiveText: "#8e8e93",
      borderHigh: "#ffffff",
      borderLight: "#e5e5ea",
      borderDark: "#d1d1d6",
      borderLow: "#aeaeb2",
      fieldBg: "#ffffff",
      fieldText: "#000000",
      selectionBg: "#007aff",
      selectionText: "#ffffff",
      focus: "#007aff",
      danger: "#ff3b30",
      success: "#34c759",
      warning: "#ff9500",
      disabled: "#f2f2f4",
      disabledText: "#c7c7cc",
      controlBg: "#ffffff",
      controlBgHover: "#f2f2f4",
      controlBgActive: "#e5e5ea",
      controlBgPrimary: "#007aff",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 0 0 1px #d9d9de",
      shadowInset: "inset 0 1px 2px rgba(0, 0, 0, 0.04)",
      shadowWindow: "0 8px 24px rgba(0, 0, 0, 0.12)",
      radius: "6px",
      radiusWindow: "10px",
      radiusControl: "6px",
      borderWidth: "1px",
      fontSize: "14px",
      lineHeight: "1.45",
      controlHeight: "32px",
      titlebarHeight: "38px",
      space: "12px",
      letterSpacing: "-0.01em",
    },
  }),
  defineTheme({
    id: "skeuomorphic-2010",
    slug: "skeuomorphic-2010",
    name: "Skeuomorphic 2010",
    year: 2010,
    era: "Web/UI",
    description:
        "Linen and leather era: beige stitching textures, glossy gel controls, embossed labels, warm materials.",
    tags: ["skeuomorphic", "linen", "leather", "ipad"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "noise",
    fonts: { ui: helveticaStack, mono: monoStack, display: serifStack },
    tokens: {
      desktop: "linear-gradient(#e8e2d4, #c9bfa8)",
      surface: "#f2ede2",
      surfaceAlt: "#e4ddcc",
      text: "#3a3226",
      textMuted: "#8a7f6a",
      textOnAccent: "#ffffff",
      accent: "#1c5fa8",
      accentHover: "#2a75c4",
      titlebarBg: "linear-gradient(#f6f1e6, #d8d0bc)",
      titlebarText: "#3a3226",
      titlebarInactiveBg: "#ddd5c2",
      titlebarInactiveText: "#8a7f6a",
      borderHigh: "#ffffff",
      borderLight: "#f6f1e6",
      borderDark: "#b0a68c",
      borderLow: "#8a7f6a",
      fieldBg: "#ffffff",
      fieldText: "#3a3226",
      selectionBg: "#1c5fa8",
      selectionText: "#ffffff",
      focus: "#1c5fa8",
      danger: "#a83a2a",
      success: "#4a8a3a",
      warning: "#b0862a",
      disabled: "#e4ddcc",
      disabledText: "#a89e86",
      controlBg: "linear-gradient(#fdfbf5, #d8d0bc)",
      controlBgHover: "linear-gradient(#ffffff, #e2dac6)",
      controlBgActive: "#c8bfa8",
      controlBgPrimary: "linear-gradient(#5aa8e8, #1c5fa8)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 rgba(255, 255, 255, 0.8), 0 1px 3px rgba(58, 50, 38, 0.25)",
      shadowInset: "inset 0 2px 4px rgba(58, 50, 38, 0.18)",
      shadowWindow: "0 14px 36px rgba(58, 50, 38, 0.35)",
      radius: "8px",
      radiusWindow: "10px",
      radiusControl: "8px",
      borderWidth: "1px",
      fontSize: "13px",
      lineHeight: "1.45",
      controlHeight: "30px",
      titlebarHeight: "36px",
      space: "12px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "material-design",
    slug: "material-design",
    name: "Material Design",
    year: 2014,
    era: "Web/UI",
    description:
        "Google's paper: indigo app bars, elevation shadows, teal FAB accents, Roboto, and 2px corners.",
    tags: ["google", "android", "material", "elevation"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: "Roboto, 'Noto Sans', sans-serif", mono: monoStack, display: "Roboto, sans-serif" },
    tokens: {
      desktop: "#cfd8dc",
      surface: "#ffffff",
      surfaceAlt: "#f5f5f5",
      text: "#212121",
      textMuted: "#727272",
      textOnAccent: "#ffffff",
      accent: "#3f51b5",
      accentHover: "#5c6bc0",
      titlebarBg: "#3f51b5",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#b0bec5",
      titlebarInactiveText: "#eceff1",
      borderHigh: "#ffffff",
      borderLight: "#eceff1",
      borderDark: "#cfd8dc",
      borderLow: "#b0bec5",
      fieldBg: "#ffffff",
      fieldText: "#212121",
      selectionBg: "#3f51b5",
      selectionText: "#ffffff",
      focus: "#3f51b5",
      danger: "#f44336",
      success: "#4caf50",
      warning: "#ffc107",
      disabled: "#f5f5f5",
      disabledText: "#bdbdbd",
      controlBg: "#ffffff",
      controlBgHover: "#f5f5f5",
      controlBgActive: "#e0e0e0",
      controlBgPrimary: "#ff4081",
      controlTextPrimary: "#ffffff",
      shadowOutset: "0 2px 4px rgba(0, 0, 0, 0.18), 0 1px 2px rgba(0, 0, 0, 0.1)",
      shadowInset: "inset 0 0 0 0 transparent",
      shadowWindow: "0 6px 18px rgba(0, 0, 0, 0.22)",
      radius: "2px",
      radiusWindow: "2px",
      radiusControl: "2px",
      borderWidth: "0px",
      fontSize: "14px",
      lineHeight: "1.45",
      controlHeight: "36px",
      titlebarHeight: "48px",
      space: "12px",
      letterSpacing: "0.01em",
    },
  }),
  defineTheme({
    id: "material-you",
    slug: "material-you",
    name: "Material You",
    year: 2021,
    era: "Web/UI",
    description:
      "M3 dynamic color: tonal purples, stadium controls, 28px window radii, and friendly oversized type.",
    tags: ["google", "android", "material-3", "dynamic-color"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: "Roboto, 'Noto Sans', sans-serif", mono: monoStack, display: "Roboto, sans-serif" },
    tokens: {
      desktop: "linear-gradient(160deg, #e7d7f5, #cfe3f7)",
      surface: "#fef7ff",
      surfaceAlt: "#f3edf7",
      text: "#1d1b20",
      textMuted: "#49454f",
      textOnAccent: "#ffffff",
      accent: "#6750a4",
      accentHover: "#7f67be",
      titlebarBg: "#eaddff",
      titlebarText: "#21005d",
      titlebarInactiveBg: "#e8def8",
      titlebarInactiveText: "#79747e",
      borderHigh: "#ffffff",
      borderLight: "#e7e0ec",
      borderDark: "#cac4d0",
      borderLow: "#9f94a8",
      fieldBg: "#ffffff",
      fieldText: "#1d1b20",
      selectionBg: "#6750a4",
      selectionText: "#ffffff",
      focus: "#6750a4",
      danger: "#b3261e",
      success: "#386a20",
      warning: "#7d5260",
      disabled: "#f3edf7",
      disabledText: "#9f94a8",
      controlBg: "#eaddff",
      controlBgHover: "#f4e9ff",
      controlBgActive: "#d0bcff",
      controlBgPrimary: "#6750a4",
      controlTextPrimary: "#ffffff",
      shadowOutset: "0 1px 3px rgba(0, 0, 0, 0.12)",
      shadowInset: "none",
      shadowWindow: "0 10px 30px rgba(29, 27, 32, 0.18)",
      radius: "12px",
      radiusWindow: "28px",
      radiusControl: "999px",
      borderWidth: "0px",
      fontSize: "14px",
      lineHeight: "1.5",
      controlHeight: "40px",
      titlebarHeight: "56px",
      space: "14px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "bootstrap-3",
    slug: "bootstrap-3",
    name: "Bootstrap 3",
    year: 2013,
    era: "Web/UI",
    description:
      "The default dashboard decade: #337ab7 blue, panel headings, btn-default chrome, and jumbotron confidence.",
    tags: ["bootstrap", "dashboard", "saas", "2010s"],
    engine: "web",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "#f5f5f5",
      surface: "#ffffff",
      surfaceAlt: "#f5f5f5",
      text: "#333333",
      textMuted: "#777777",
      textOnAccent: "#ffffff",
      accent: "#337ab7",
      accentHover: "#286090",
      titlebarBg: "#337ab7",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#dddddd",
      titlebarInactiveText: "#777777",
      borderHigh: "#ffffff",
      borderLight: "#dddddd",
      borderDark: "#cccccc",
      borderLow: "#adadad",
      fieldBg: "#ffffff",
      fieldText: "#333333",
      selectionBg: "#337ab7",
      selectionText: "#ffffff",
      focus: "#66afe9",
      danger: "#d9534f",
      success: "#5cb85c",
      warning: "#f0ad4e",
      disabled: "#eeeeee",
      disabledText: "#999999",
      controlBg: "#ffffff",
      controlBgHover: "#e6e6e6",
      controlBgActive: "#d4d4d4",
      controlBgPrimary: "#337ab7",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 rgba(255, 255, 255, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05)",
      shadowInset: "inset 0 1px 1px rgba(0, 0, 0, 0.075)",
      shadowWindow: "0 6px 16px rgba(0, 0, 0, 0.15)",
      radius: "4px",
      radiusWindow: "4px",
      radiusControl: "4px",
      borderWidth: "1px",
      fontSize: "14px",
      lineHeight: "1.45",
      controlHeight: "32px",
      titlebarHeight: "38px",
      space: "12px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "modern-saas",
    slug: "modern-saas",
    name: "Modern SaaS",
    year: 2022,
    era: "Web/UI",
    description:
      "Linear-era product UI: near-mono neutrals, hairline borders, quiet purple accents, and Inter everywhere.",
    tags: ["linear", "notion", "minimal", "inter"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: "Inter, 'Noto Sans', sans-serif", mono: monoStack, display: "Inter, sans-serif" },
    tokens: {
      desktop: "#f7f7f8",
      surface: "#ffffff",
      surfaceAlt: "#fafafa",
      text: "#18191b",
      textMuted: "#6b6f76",
      textOnAccent: "#ffffff",
      accent: "#5e6ad2",
      accentHover: "#7580dc",
      titlebarBg: "#ffffff",
      titlebarText: "#18191b",
      titlebarInactiveBg: "#fafafa",
      titlebarInactiveText: "#8a8e98",
      borderHigh: "#ffffff",
      borderLight: "#e8e8ea",
      borderDark: "#dcdce0",
      borderLow: "#c2c4ca",
      fieldBg: "#ffffff",
      fieldText: "#18191b",
      selectionBg: "#5e6ad2",
      selectionText: "#ffffff",
      focus: "#5e6ad2",
      danger: "#d4442e",
      success: "#20865c",
      warning: "#b8860b",
      disabled: "#f2f2f4",
      disabledText: "#a8abb2",
      controlBg: "#ffffff",
      controlBgHover: "#f2f2f4",
      controlBgActive: "#e8e8ea",
      controlBgPrimary: "#5e6ad2",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 0 0 1px #e8e8ea",
      shadowInset: "inset 0 1px 2px rgba(0, 0, 0, 0.05)",
      shadowWindow: "0 1px 2px rgba(0, 0, 0, 0.05), 0 8px 24px rgba(0, 0, 0, 0.06)",
      radius: "8px",
      radiusWindow: "10px",
      radiusControl: "8px",
      borderWidth: "1px",
      fontSize: "13px",
      lineHeight: "1.5",
      controlHeight: "32px",
      titlebarHeight: "40px",
      space: "12px",
      letterSpacing: "-0.005em",
    },
  }),
  defineTheme({
    id: "ai-chat",
    slug: "ai-chat",
    name: "AI Chat",
    year: 2023,
    era: "Web/UI",
    description:
      "Post-2022 assistant: markdown panes, streaming responses, suggestion chips, and one confident violet accent.",
    tags: ["ai", "assistant", "chat", "llm"],
    engine: "graphic",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: "Inter, 'Noto Sans', sans-serif", mono: monoStack, display: "Inter, sans-serif" },
    tokens: {
      desktop: "#ffffff",
      surface: "#ffffff",
      surfaceAlt: "#f4f4f5",
      text: "#18181b",
      textMuted: "#71717a",
      textOnAccent: "#ffffff",
      accent: "#7c5cff",
      accentHover: "#927aff",
      titlebarBg: "#ffffff",
      titlebarText: "#18181b",
      titlebarInactiveBg: "#fafafa",
      titlebarInactiveText: "#a1a1aa",
      borderHigh: "#ffffff",
      borderLight: "#e4e4e7",
      borderDark: "#d4d4d8",
      borderLow: "#a1a1aa",
      fieldBg: "#ffffff",
      fieldText: "#18181b",
      selectionBg: "#7c5cff",
      selectionText: "#ffffff",
      focus: "#7c5cff",
      danger: "#dc2626",
      success: "#16a34a",
      warning: "#d97706",
      disabled: "#f4f4f5",
      disabledText: "#a1a1aa",
      controlBg: "#ffffff",
      controlBgHover: "#f4f4f5",
      controlBgActive: "#e4e4e7",
      controlBgPrimary: "#7c5cff",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 0 0 1px #e4e4e7",
      shadowInset: "none",
      shadowWindow: "0 4px 16px rgba(0, 0, 0, 0.07)",
      radius: "10px",
      radiusWindow: "12px",
      radiusControl: "10px",
      borderWidth: "1px",
      fontSize: "14px",
      lineHeight: "1.55",
      controlHeight: "34px",
      titlebarHeight: "42px",
      space: "14px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "phpbb-forum",
    slug: "phpbb-forum",
    name: "phpBB Forums",
    year: 2003,
    era: "Web/UI",
    description:
      "subSilver forever: blue category bars, alternating row tints, Verdana 11px, orange new-post icons, and a signature that quotes your whole post.",
    tags: ["phpbb", "forum", "subsilver", "community", "2000s"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: verdanaStack, mono: monoStack, display: verdanaStack },
    tokens: {
      desktop: "#e5e5e5",
      surface: "#ffffff",
      surfaceAlt: "#dee3e7",
      text: "#111111",
      textMuted: "#666666",
      textOnAccent: "#ffffff",
      accent: "#006699",
      accentHover: "#0f87c0",
      titlebarBg: "linear-gradient(#3f87c2, #0f5a9c)",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#d1d7dc",
      titlebarInactiveText: "#666666",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#eff3f8",
      borderDark: "#a5b0ba",
      borderLow: "#8a97a4",
      fieldBg: "#ffffff",
      fieldText: "#111111",
      selectionBg: "#e5ebf0",
      selectionText: "#111111",
      focus: "#006699",
      danger: "#c20000",
      success: "#006600",
      warning: "#ffa34f",
      disabled: "#e5e5e5",
      disabledText: "#9aa4ad",
      controlBg: "linear-gradient(#fafbfd, #d5dde5)",
      controlBgHover: "linear-gradient(#ffffff, #e2e9f0)",
      controlBgActive: "#c8d2db",
      controlBgPrimary: "linear-gradient(#3f87c2, #0f5a9c)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 2px rgba(20, 40, 60, 0.2)",
      shadowInset: "inset 0 1px 2px rgba(20, 40, 60, 0.15)",
      shadowWindow: "0 3px 8px rgba(20, 40, 60, 0.25)",
      radius: "2px",
      radiusWindow: "3px",
      radiusControl: "2px",
      borderWidth: "1px",
      fontSize: "11px",
      lineHeight: "1.4",
      controlHeight: "24px",
      titlebarHeight: "24px",
      space: "8px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "myspace-profile",
    slug: "myspace-profile",
    name: "MySpace Profile",
    year: 2006,
    era: "Web/UI",
    description:
      "Tom's default layout: pale blue page, white tables with #6698cb borders, Verdana 11, and a Top 8 worth fighting over.",
    tags: ["myspace", "social", "profile", "2000s", "tables"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: verdanaStack, mono: monoStack, display: verdanaStack },
    tokens: {
      desktop: "#d5e8fb",
      surface: "#ffffff",
      surfaceAlt: "#eef4fb",
      text: "#000000",
      textMuted: "#666666",
      textOnAccent: "#ffffff",
      accent: "#003399",
      accentHover: "#0f4ac0",
      titlebarBg: "#6698cb",
      titlebarText: "#ffffff",
      titlebarInactiveBg: "#c8dcf0",
      titlebarInactiveText: "#666666",
      titleLabelBg: "transparent",
      borderHigh: "#ffffff",
      borderLight: "#eaf2fb",
      borderDark: "#6698cb",
      borderLow: "#4a76a8",
      fieldBg: "#ffffff",
      fieldText: "#000000",
      selectionBg: "#c0d8f0",
      selectionText: "#003399",
      focus: "#003399",
      danger: "#cc0000",
      success: "#008800",
      warning: "#ff9900",
      disabled: "#eef4fb",
      disabledText: "#9ab4d4",
      controlBg: "linear-gradient(#ffffff, #dce8f4)",
      controlBgHover: "linear-gradient(#ffffff, #e8f1f9)",
      controlBgActive: "#c8dcf0",
      controlBgPrimary: "linear-gradient(#6da0d4, #4a7cb4)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #ffffff, 0 1px 2px rgba(30, 60, 100, 0.18)",
      shadowInset: "inset 0 1px 2px rgba(30, 60, 100, 0.14)",
      shadowWindow: "0 2px 6px rgba(30, 60, 100, 0.2)",
      radius: "3px",
      radiusWindow: "3px",
      radiusControl: "3px",
      borderWidth: "1px",
      fontSize: "11px",
      lineHeight: "1.4",
      controlHeight: "24px",
      titlebarHeight: "24px",
      space: "8px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "limewire",
    slug: "limewire",
    name: "LimeWire",
    year: 2004,
    era: "Web/UI",
    description:
      "Java Swing on the desktop of a dorm room: brushed gray chrome, four search fields, lime-green accents, and 47 redownloads of the same file.",
    tags: ["limewire", "p2p", "java", "swing", "file-sharing"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: tahomaStack, mono: monoStack, display: tahomaStack },
    tokens: {
      desktop: "#8a98a0",
      surface: "linear-gradient(#dcdbd9, #b8b8b6)",
      surfaceAlt: "#b0b0ae",
      text: "#1a1a1a",
      textMuted: "#606060",
      textOnAccent: "#ffffff",
      accent: "#3aa535",
      accentHover: "#52c04c",
      titlebarBg: "linear-gradient(#e2e2e0, #a8a8a6)",
      titlebarText: "#1a1a1a",
      titlebarInactiveBg: "#c0c0be",
      titlebarInactiveText: "#606060",
      titleLabelBg: "transparent",
      borderHigh: "#f4f4f2",
      borderLight: "#dcdcd9",
      borderDark: "#8a8a88",
      borderLow: "#6a6a68",
      fieldBg: "#ffffff",
      fieldText: "#1a1a1a",
      selectionBg: "#a0d09a",
      selectionText: "#111111",
      focus: "#3aa535",
      danger: "#c0392b",
      success: "#3aa535",
      warning: "#e8a33d",
      disabled: "#c8c8c6",
      disabledText: "#8a8a88",
      controlBg: "linear-gradient(#e6e5e3, #c2c1bf)",
      controlBgHover: "linear-gradient(#eeeded, #cccccb)",
      controlBgActive: "#b4b3b1",
      controlBgPrimary: "linear-gradient(#52b84c, #2c8a28)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #f8f8f6, 0 1px 2px rgba(0, 0, 0, 0.25)",
      shadowInset: "inset 0 2px 3px rgba(0, 0, 0, 0.2)",
      shadowWindow: "0 4px 10px rgba(20, 28, 32, 0.35)",
      radius: "4px",
      radiusWindow: "5px",
      radiusControl: "4px",
      borderWidth: "1px",
      fontSize: "12px",
      lineHeight: "1.35",
      controlHeight: "26px",
      titlebarHeight: "26px",
      space: "8px",
      letterSpacing: "0",
    },
  }),
  defineTheme({
    id: "quicktime-4",
    slug: "quicktime-4",
    name: "QuickTime 4",
    year: 1999,
    era: "Web/UI",
    description:
      "The brushed-metal half-puck: capsule controls, a thumbwheel volume, and chrome so pretty you forgave the Pro nag screen.",
    tags: ["apple", "quicktime", "brushed-metal", "media-player", "1999"],
    engine: "soft",
    controls: "none",
    desktopPattern: "none",
    fonts: { ui: helveticaStack, mono: monoStack, display: helveticaStack },
    tokens: {
      desktop: "linear-gradient(180deg, #4a4e54, #2a2e34)",
      surface: "repeating-linear-gradient(180deg, #c9cdd2 0px, #c9cdd2 1px, #d4d8dd 1px, #d4d8dd 3px)",
      surfaceAlt: "#b8bcc2",
      text: "#2a2e34",
      textMuted: "#6a7078",
      textOnAccent: "#ffffff",
      accent: "#3a6ea5",
      accentHover: "#4a82bd",
      titlebarBg: "repeating-linear-gradient(180deg, #c9cdd2 0px, #c9cdd2 1px, #d4d8dd 1px, #d4d8dd 3px)",
      titlebarText: "#2a2e34",
      titlebarInactiveBg: "#b8bcc2",
      titlebarInactiveText: "#6a7078",
      titleLabelBg: "transparent",
      borderHigh: "#eceef0",
      borderLight: "#d8dce0",
      borderDark: "#8a929a",
      borderLow: "#6a727a",
      fieldBg: "#ffffff",
      fieldText: "#2a2e34",
      selectionBg: "#c8d4e0",
      selectionText: "#2a2e34",
      focus: "#3a6ea5",
      danger: "#b04a3a",
      success: "#4a8a3a",
      warning: "#d9982a",
      disabled: "#c4c8cc",
      disabledText: "#8a9298",
      controlBg: "repeating-linear-gradient(180deg, #c9cdd2 0px, #c9cdd2 1px, #d4d8dd 1px, #d4d8dd 3px)",
      controlBgHover: "repeating-linear-gradient(180deg, #d2d6db 0px, #d2d6db 1px, #dde1e6 1px, #dde1e6 3px)",
      controlBgActive: "#b0b4ba",
      controlBgPrimary: "linear-gradient(#4a82bd, #2c5a8e)",
      controlTextPrimary: "#ffffff",
      shadowOutset: "inset 0 1px 0 #f0f2f4, 0 1px 2px rgba(0, 0, 0, 0.3)",
      shadowInset: "inset 0 2px 3px rgba(42, 46, 52, 0.25)",
      shadowWindow: "0 6px 16px rgba(16, 20, 26, 0.4)",
      radius: "8px",
      radiusWindow: "8px",
      radiusControl: "999px",
      borderWidth: "1px",
      fontSize: "12px",
      lineHeight: "1.35",
      controlHeight: "30px",
      titlebarHeight: "26px",
      space: "10px",
      letterSpacing: "0",
    },
  }),
];
